### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by wbednarski** [KronicDeth/intellij-elixir#737] opened 2017-07-18 21:39 UTC
# Version

5.1.0

# Exception

## Message

Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null

## Stacktrace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'obj' of com/intellij/util/containers/SmartHashSet.add must not be null
	at com.intellij.util.containers.SmartHashSet.add(SmartHashSet.java)
	at org.elixir_lang.psi.stub.type.call.Stub.readNameSet(Stub.java:38)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:94)
	at org.elixir_lang.beam.psi.stubs.ModuleStubElementTypes$2.deserialize(ModuleStubElementTypes.java:70)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:197)
	at com.intellij.psi.stubs.StubSerializationHelper.a(StubSerializationHelper.java:203)
	at com.intellij.psi.stubs.StubSerializationHelper.deserialize(StubSerializationHelper.java:151)
	at com.intellij.psi.stubs.SerializationManagerImpl.deserialize(SerializationManagerImpl.java:164)
	at com.intellij.psi.stubs.SerializedStubTree.getStub(SerializedStubTree.java:89)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:52)
	at org.elixir_lang.beam.psi.BeamFileImpl.getStubTree(BeamFileImpl.java:261)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:331)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:615)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:603)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.elixir_lang.reference.Module.namedElementCollection(Module.java:104)
	at org.elixir_lang.reference.Module.forEachNavigationElement(Module.java:60)
	at org.elixir_lang.psi.scope.CallDefinitionClause.implicitImports(CallDefinitionClause.java:132)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:122)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.java:44)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1555)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:147)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:42)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:32)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:705)
	at org.elixir_lang.reference.Callable.resolve(Callable.java:730)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:125)
	at org.jetbrains.plugins.ruby.rails.search.RailsDoubleExtFileReferenceSearch.lambda$searchReferencesFor$2(RailsDoubleExtFileReferenceSearch.java:60)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:138)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:225)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processElementsWithWord$1(PsiSearchHelperImpl.java:167)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:247)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:238)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$5(PsiSearchHelperImpl.java:421)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:40)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:405)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:323)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$3(PsiSearchHelperImpl.java:351)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by KronicDeth** [comment] 2017-07-18 22:21
Duplicate of #718.  Please subscribe to that issue.

**Closed by KronicDeth** 2017-07-18 22:21 UTC
