### ISSUE TITLE
Cannot find enclosing Modular at org.elixir_lang.navigation.ChooseByNameContributor.error(ChooseByNameContributor.kt:286) at phoenix/lib/phoenix/router/helpers.ex:118-120

### ISSUE THREAD

**Issue by rajatdeshpande** [KronicDeth/intellij-elixir#2861] opened 2022-09-19 01:42 UTC
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Community Edition (2021.3.2)
Operating System: Mac OS X (12.6)

# Event

### Excerpt

```
def unquote(:"#{helper}_path")(conn_or_endpoint, unquote(Macro.escape(opts)), unquote_splicing(vars)) do
          unquote(:"#{helper}_path")(conn_or_endpoint, unquote(Macro.escape(opts)), unquote_splicing(vars), [])
        end
```

From: `/Users/rajatdeshpande/Desktop/Work/elixir/story_mapper/deps/phoenix/lib/phoenix/router/helpers.ex:118`
To: `/Users/rajatdeshpande/Desktop/Work/elixir/story_mapper/deps/phoenix/lib/phoenix/router/helpers.ex:120`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl
```

### Stacktrace

```
java.lang.Throwable: Cannot find enclosing Modular
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.navigation.ChooseByNameContributor.error(ChooseByNameContributor.kt:286)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsFromCallDefinitionClause(ChooseByNameContributor.kt:146)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByNameFromCall(ChooseByNameContributor.kt:92)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:68)
```

**Comment by KronicDeth** [comment] 2023-03-17 20:13
Duplicate of #2923

**Closed by KronicDeth** 2023-03-17 20:13 UTC
Labels: Kind:Bug
