### ISSUE TITLE
java.lang.NullPointerException at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:189)

### ISSUE THREAD

**Issue by jshickey** [KronicDeth/intellij-elixir#2692] opened 2022-05-29 11:02 UTC
# System

Plugin Version: 13.0.0
Application: IntelliJ IDEA Community Edition (2022.1.1)
Operating System: Mac OS X (12.4)

# Event

## Message

Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@3dc0cd71, Dispatchers.Default]

### Stacktrace

```
java.lang.NullPointerException
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:189)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

**Comment by KronicDeth** [comment] 2022-05-30 04:28
Duplicate of #2564

**Closed by KronicDeth** 2022-05-30 04:28 UTC
