### ISSUE TITLE
Failed to run formatter

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#3192] opened 2023-04-24 20:02 UTC
It happened when I ran the reformat command.

# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1)
Operating System: Mac OS X (13.3.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
</summary>

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 99,4,main] 168212952 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 376509485
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:219)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:213)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.workingDirectory(MixFormatExternalFormatProcessor.kt:77)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$workingDirectory(MixFormatExternalFormatProcessor.kt:70)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
```

</details>

----

Here is the broken code:

```elixir
defmodule Web.Api.RequestIamOauthGoogle do
  use Web, :controller

  alias Iam.Identity
  alias Repo
  alias Web.IdentityAuth

  def handle(conn, params) do
    command = Command.new!(params)

    config =  [
    client_id: "REPLACE_WITH_CLIENT_ID",
                             client_secret: "REPLACE_WITH_CLIENT_SECRET",
                             auth_method: :client_secret_post,
                                           site: "https://auth.example.com",
                             authorization_params: [scope: "user:read user:write"],
                             user_url: "https://example.com/api/user"
                             ]

                             {:ok, {url: url, session_params: session_params}} =
                                                              config
                                                              |> Assent.Config.put(:redirect_uri, "http://localhost:4000/auth/callback")
                             |> Assent.Strategy.OAuth2.authorize_url()
end
end
```

```
** (SyntaxError) lib/web/api/request_iam_oauth_google.ex:30:37: syntax error before: url
    |
 30 |                              {:ok, {url: url, session_params: session_params}} =
    |                                     ^
    (elixir 1.14.4) lib/code.ex:776: Code.format_string!/2
```

**Comment by yordis** [comment] 2023-04-24 20:15
Actually it is failing regardless if the code is broken or not:

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 133,4,main] 603401621 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 376509485
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:219)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:213)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.workingDirectory(MixFormatExternalFormatProcessor.kt:77)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$workingDirectory(MixFormatExternalFormatProcessor.kt:70)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by KronicDeth** [comment] 2023-05-06 02:44
Duplicate of #3189

**Closed by KronicDeth** 2023-05-06 02:44 UTC
