### ISSUE TITLE
java.lang.ClassCastException: class org.elixir_lang.beam.psi.impl.ModuleImpl cannot be cast to class org.elixir_lang.psi.call.Call (org.elixir_lang.beam.psi.impl.ModuleImpl and org.elixir_lang.psi.call.Call are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @792c48d5) at org.elixir_lang.code_insight.line_marker_provider.Implementation.getLineMarkerInfo$lambda-6$lambda-5$lambda-4$lambda-3(Implementation.kt:56)

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [KronicDeth/intellij-elixir#2744] opened 2022-07-10 10:09 UTC
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Community Edition (2022.1.3)
Operating System: Linux (5.4.0-121-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.ClassCastException: class org.elixir_lang.beam.psi.impl.ModuleImpl cannot be cast to class org.elixir_lang.psi.call.Call (org.elixir_lang.beam.psi.impl.ModuleImpl and org.elixir_lang.psi.call.Call are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @792c48d5)
</summary>

```
java.lang.ClassCastException: class org.elixir_lang.beam.psi.impl.ModuleImpl cannot be cast to class org.elixir_lang.psi.call.Call (org.elixir_lang.beam.psi.impl.ModuleImpl and org.elixir_lang.psi.call.Call are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @792c48d5)
	at org.elixir_lang.code_insight.line_marker_provider.Implementation.getLineMarkerInfo$lambda-6$lambda-5$lambda-4$lambda-3(Implementation.kt:56)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:74)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:140)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:187)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:50)
	at org.elixir_lang.psi.Implementation.processProtocols(Implementation.kt:97)
	at org.elixir_lang.code_insight.line_marker_provider.Implementation.getLineMarkerInfo$lambda-6$lambda-5$lambda-4(Implementation.kt:55)
	at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:60)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder$1.create(NavigationGutterIconBuilder.java:264)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.lambda$createPointersThunk$4(NavigationGutterIconBuilder.java:331)
	at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:60)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.codeInsight.navigation.NavigationGutterIconRenderer.getTargetElements(NavigationGutterIconRenderer.java:100)
	at org.elixir_lang.code_insight.line_marker_provider.Implementation$ProtocolsNavigationGutterIconRenderer.navigate(Implementation.kt:127)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-01 14:16
Duplicate of #2417

**Closed by KronicDeth** 2022-08-01 14:16 UTC
