### ISSUE TITLE
 Read access is allowed from event dispatch thread or inside read-action only at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173)

### ISSUE THREAD

**Issue by BesaBoldwin** [KronicDeth/intellij-elixir#2430] opened 2021-12-29 06:57 UTC
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.getSortedModules(ModuleManagerImpl.java:601)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.getContentRootsFromAllModules(ProjectRootManagerImpl.java:184)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureRootOtpApp$2.run(DirectoryConfigurator.kt:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:482)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:77)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment] 2022-01-07 17:25
Duplicate of #1900

**Closed by KronicDeth** 2022-01-07 17:25 UTC
