### ISSUE TITLE
The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elixir_lang.espec.configuration.Factory'

### ISSUE THREAD

**Issue by ulmentflam** [KronicDeth/intellij-elixir#2361] opened 2021-12-06 20:52 UTC
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elixir_lang.espec.configuration.Factory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: org.elixir_lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.getName(RunnerAndConfigurationSettingsImpl.kt:154)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.getSchemeKey(RunConfigurationSchemeManager.kt:37)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.getSchemeKey(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.schemeManager.SchemeListManager.addScheme(SchemeListManager.kt:35)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.addScheme(SchemeManagerImpl.kt:615)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.addScheme(SchemeManagerImpl.kt:42)
	at com.intellij.openapi.options.SchemeManager.addScheme(SchemeManager.kt:38)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:337)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:261)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic(RunConfigurationProducer.java:259)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration(RunConfigurationProducer.java:249)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:98)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:199)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:110)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:93)
	at com.intellij.execution.actions.ConfigurationContext.getConfigurationsFromContext(ConfigurationContext.java:414)
	at com.intellij.execution.actions.ConfigurationContext.findPreferredConfiguration(ConfigurationContext.java:292)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:285)
	at com.intellij.execution.actions.BaseRunConfigurationAction.findExisting(BaseRunConfigurationAction.java:62)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:232)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:198)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:89)
	at com.intellij.execution.lineMarker.RunLineMarkerContributor.getText(RunLineMarkerContributor.java:87)
	at me.serce.solidity.ide.run.SolidityRunLineMarkerProvider.access$getText$s-1171017470(SolidityRunConfigProducer.kt:67)
	at me.serce.solidity.ide.run.SolidityRunLineMarkerProvider$getInfo$1$1.fun(SolidityRunConfigProducer.kt:77)
	at me.serce.solidity.ide.run.SolidityRunLineMarkerProvider$getInfo$1$1.fun(SolidityRunConfigProducer.kt:67)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1870)
	at me.serce.solidity.ide.run.SolidityRunLineMarkerProvider$getInfo$1.fun(SolidityRunConfigProducer.kt:77)
	at me.serce.solidity.ide.run.SolidityRunLineMarkerProvider$getInfo$1.fun(SolidityRunConfigProducer.kt:67)
	at com.intellij.execution.lineMarker.RunLineMarkerContributor$Info.lambda$new$0(RunLineMarkerContributor.java:46)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.lambda$createLineMarker$2(RunLineMarkerProvider.java:133)
	at com.intellij.codeInsight.daemon.LineMarkerInfo.getLineMarkerTooltip(LineMarkerInfo.java:194)
	at com.intellij.codeInsight.daemon.LineMarkerInfo$LineMarkerGutterIconRenderer.getTooltipText(LineMarkerInfo.java:256)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.lambda$run$0(EditorGutterComponentImpl.java:1853)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.run(EditorGutterComponentImpl.java:1853)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment] 2021-12-07 02:45
Duplicate of #2105

**Closed by KronicDeth** 2021-12-07 02:45 UTC
