### ISSUE TITLE
Can't choose SDK (Idea, Windows, Elixir)

### ISSUE THREAD

**Issue by Wulpo** [KronicDeth/intellij-elixir#242] opened 2016-02-16 17:18 UTC
I install elixir (elixir-websetup.exe  version 1.2.2) and when I want to choose SDK it will write a message:
"That selected directory is not valid home for Elixir SDK"

![sdkelixir](https://cloud.githubusercontent.com/assets/13139016/13084360/7675c568-d4d9-11e5-91a1-9f24fcbaedb8.png)

**Comment by NobbZ** [comment] 2016-02-16 20:03
The SDK lives in Elixir, not Elixir/bin

Wulpo <notifications@github.com> schrieb am Di., 16. Feb. 2016 18:18:

**Comment by KronicDeth** [comment] 2016-02-19 03:00
@NobbZ that issue is already known.  I already identified the problem (http://stackoverflow.com/a/35434464/470451) as the `Elixir` directory showing "Corrupted SDK", which usually means the version can't be parsed.

**Comment by KronicDeth** [comment] 2016-02-19 04:54
Hmm... now I can't repro the problem when debugging from a build off of master.

**Comment by KronicDeth** [comment] 2016-03-03 06:19
I can't reproduce the problem using the pre-release build of v2.2.0, so I'm closing it for now.

**Closed by KronicDeth** 2016-03-03 06:19 UTC
Labels: bug

**Comment by KronicDeth** [comment] 2016-03-04 03:31
@Wulpo can you verify that v2.2.0 that I just released works for you?
