### ISSUE TITLE
Don't know how to resolve variable in match `key:, value:})`

### ISSUE THREAD

**Issue by andybeak** [KronicDeth/intellij-elixir#451] opened 2016-10-08 14:35 UTC
# Version

4.4.0

# Description

The plugin is having problems picking up the Elixir SDK.  

I think the problem could be because I mistyped an atom.

# Exception

## Message

Don't know how to resolve variable in match

### Excerpt

```
 key:, value:})

```
 Line(s) 9-10

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:48)
org.elixir_lang.errorreport.Logger.error(Logger.java:31)
org.elixir_lang.psi.scope.Variable.execute(Variable.java:141)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1644)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1543)
org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1046)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:84)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
org.elixir_lang.reference.Callable.multiResolve(Callable.java:800)
org.elixir_lang.reference.Callable.resolve(Callable.java:824)
org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:60)
org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:48)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:41)
org.elixir_lang.annonator.Callable.annotate(Callable.java:39)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:334)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:269)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:293)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:268)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2016-10-08 17:29
Could you please include the full Module or file around the excerpt?

**Comment by andybeak** [comment] 2016-10-08 17:45
Sure, it's the file [worker.ex](https://github.com/andybeak/cache_exercise/blob/master/lib/worker.ex).  I was busy writing the prototype for the function and mistyped the parameters

**Comment by KronicDeth** [comment] 2016-10-09 21:43
The version of `worker.ex` you posted is the corrected version with valid code in it.  I need the incorrect version that caused the error.  The current line 9 is

```
 def write(pid, key, value) do
```

The error says part of it was `key:, value:})`, but what was the full version of that line when the error occurred?

**Comment by andybeak** [comment] 2016-10-10 07:04
Sorry, I don't have a commit from when the IDE threw that error.  I'm
pretty sure that the line was the same, with just the snippet replaced
though.

~a


[image: --]

Andy Beak
[image: https://]about.me/andy.beak
<https://about.me/andy.beak?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by KronicDeth** [comment] 2016-10-15 01:37
#464 won't fix your issue, since I can't reproduce it, but it will ensure that the element class is included in any future reports, and it's the element class/interfaces that are being matched in the method that logs the error, so knowing the class, it will help figure out what `key:, value:})` was in the PSI.

**Closed** 2016-10-15 01:50 UTC
Labels: bug
