### ISSUE TITLE
Compilation on already created Mix project fails

### ISSUE THREAD

**Issue by antani** [KronicDeth/intellij-elixir#253] opened 2016-03-14 12:12 UTC
From the elixir tutorial, I created a new project with-
     
    mix new elixir_tutorial

I imported this project in to IntelliJ IDEA 14CE (with plugin installed), selected Elixir 1.2.1 as the SDK. When I click on Run, I get following error.

    Information:14/03/16, 5:35 PM - Compilation completed with 2 errors and 0 warnings in 1s 712ms
    Error:mix: String.to_char_list/1
    Error:mix: Code.require_file/2

The same project can be compiled from command line.

**Comment by KronicDeth** [comment] 2016-03-14 12:17
1) Which operating system?
2) Did you import as a Mix project?

**Comment by antani** [comment] 2016-03-14 12:25
I am on OSX El Capitan- 10.11.3
Yes, I imported the mix project

**Comment by KronicDeth** [comment] 2016-03-15 15:10
You said you clicked on ![Run](https://raw.githubusercontent.com/JetBrains/intellij-community/master/platform/icons/src/general/run.png) Run, which implies you're using a Run configuration.  What's the settings in that configuration?  The Name shouldn't matter, but the Command might.

**Comment by antani** [comment] 2016-03-15 16:42
http://imgur.com/kZYxT2h

**Comment by KronicDeth** [comment] 2016-03-15 16:51
`Gauge Execution` Run Configuration don't come from IntelliJ Elixir.  That comes from the the [Gauge plugin](https://plugins.jetbrains.com/plugin/7535).   Do you have anything under the `Elixir Mix` part of the tree?

**Comment by antani** [comment] 2016-03-15 16:53
Created an Elixir Mix run configuration - http://imgur.com/8SxHXR8
Error:

    /Users/8288/source_code/elixir_tutorial/elixir-1.2.1/bin/elixir /Users/8288/Downloads/mix run
       ** (UnicodeConversionError) invalid encoding starting at <<150, 14, 161, 70, 186, 65, 5, 62, 50, 11, 0, 0, 12, 14, 0, 0, 16, 0, 0, 0, 109, 105, 120, 95, 101, 115, 99, 114, 105, 112, 116, 46, 98, 101, 97, 109, 125, 86, 9, 88, 19, 215, 22, 158, 100, 66, 18, 194, 54, 73, ...>>
        (elixir) lib/string.ex:1634: String.to_char_list/1
        (elixir) lib/code.ex:363: Code.require_file/2

**Comment by KronicDeth** [comment] 2016-03-15 16:58
Ah, the infamous and unexplainable `UnicodeConversionError`.  Looks like this is a duplicate of #192 then.  I'm closing this issue, and we can continue talking on #192.

**Closed by KronicDeth** 2016-03-15 16:58 UTC
Labels: duplicate
