### ISSUE TITLE
Don't know how to find ancestorTypeSpec at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245) for ElixirMultipleAliasesImpl

### ISSUE THREAD

**Issue by PavelBugaian** [KronicDeth/intellij-elixir#2489] opened 2022-01-28 08:50 UTC
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Mac OS X (11.6.1)

# Event

### Excerpt

```
{:ok, m}
```

From: `/Users/pavelbugaian/IdeaProjects/rtp_exam/lib/printer_actor.ex:16`
To: `/Users/pavelbugaian/IdeaProjects/rtp_exam/lib/printer_actor.ex:16`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMultipleAliasesImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find ancestorTypeSpec
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeCallableReference(CallImpl.kt:122)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeReference(CallImpl.kt:77)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference$lambda-4(CallImpl.kt:149)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference(CallImpl.kt:148)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1048)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.getReference(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:96)
```

**Comment by KronicDeth** [comment] 2022-01-29 16:38
This must be a mid-typing transient syntax.  I always like making those work as it is a place I can make the editor succeed where the compiler would fail.

**Comment by KronicDeth** [comment] 2022-05-06 16:24
Duplicate of #2464

**Closed by KronicDeth** 2022-05-06 16:24 UTC
Labels: Kind:Bug
