### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by hiddewie** [KronicDeth/intellij-elixir#2862] opened 2022-09-19 08:44 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Linux (5.10.0-18-amd64)

# Event

### Element

```
,
```

From: `templates/runtime.exs:4`

#### Context

```
import Config

# Note: the nodes will be replaced by the deploy script:
config :peerage,
  via: Peerage.Via.List,
  node_list: [
    {% for node in ERLANG_CLUSTER_NODES %}
      :"{{ node }}",
    {% endfor %}
  ],
```

From: `templates/runtime.exs:0-9`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-01 19:16
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-10-01 19:16 UTC
