### ISSUE TITLE
Keyword pairs should not assert they have 2 children because they don't when error handling occurs

### ISSUE THREAD

**Issue by ykhrustalev** [KronicDeth/intellij-elixir#917] opened 2017-11-22 22:26 UTC
# Version

6.5.1

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getKeywordValue(ElixirPsiImplUtil.java:3039)
	at org.elixir_lang.psi.impl.ElixirKeywordPairImpl.getKeywordValue(ElixirKeywordPairImpl.java:47)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:520)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:509)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:113)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:375)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:420)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:82)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:440)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:476)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:90)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1896)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1792)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:58)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:142)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:666)
	at org.elixir_lang.annotator.Callable$1.visitPlainCall(Callable.java:172)
	at org.elixir_lang.annotator.Callable$1.visitNonModuleAttributeCall(Callable.java:156)
	at org.elixir_lang.annotator.Callable$1.visitCall(Callable.java:114)
	at org.elixir_lang.annotator.Callable$1.visitElement(Callable.java:148)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
	at org.elixir_lang.annotator.Callable.annotate(Callable.java:105)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by KronicDeth** [comment] 2017-12-01 01:44
https://github.com/KronicDeth/intellij-elixir/blob/314807fbfafc0ed34597406dd2c7bd16e2426e5e/src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java#L3039

The `assert` is likely false when error handling is occurring.  It needs to be loosened to handle error handling nodes correctly.

**Comment by KronicDeth** [comment] 2021-06-30 15:49
Duplicate of #1611

**Closed by KronicDeth** 2021-06-30 15:49 UTC
Labels: Kind:Bug
