### ISSUE TITLE
[auto-generated] Error in intellij (clion)

### ISSUE THREAD

**Issue by nitingupta910** [KronicDeth/intellij-elixir#652] opened 2017-03-23 15:38 UTC
# Version

4.7.0

# Exception

## Message

Don't know how to resolve variable in match

### Excerpt

```
{:reply, "open_index called with path #{path}", nil}
```
 Line(s) 11-11

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMultipleAliasesImpl
```

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:51)
org.elixir_lang.errorreport.Logger.error(Logger.java:34)
org.elixir_lang.psi.scope.Variable.execute(Variable.java:141)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsRecursively(ElixirPsiImplUtil.java:1708)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1574)
org.elixir_lang.psi.impl.ElixirMultipleAliasesImpl.processDeclarations(ElixirMultipleAliasesImpl.java:52)
com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1058)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
org.elixir_lang.reference.Callable.multiResolve(Callable.java:644)
org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:69)
org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:52)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
org.elixir_lang.annonator.Callable.annotate(Callable.java:43)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:425)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2017-03-27 18:33
Duplicate of #568.  Fixed by #600.  Wait for next release.

**Closed by KronicDeth** 2017-03-27 18:33 UTC
