### ISSUE TITLE
After upgrading to 12.1.0, Intellij completely locks up after a minute or so

### ISSUE THREAD

**Issue by briefjudofox** [KronicDeth/intellij-elixir#2457] opened 2022-01-07 23:50 UTC
**Describe the bug**
After upgrading to 12.1.0, Intellij completely locks up after a minute or so.  When I disable the elixir plugin, the IDE does not freeze.  Downgrading to 12.0.1 also resolves the issue.

**To Reproduce**
1. Upgrade the intellij-elixir plugin on IntelliJ IDEA 2021.3.1 (Ultimate Edition)
2. Wait about a minute and the entire IDE locks up requiring a force quit to recover

**Expected behavior**
IDE doesn't freeze with intellij-elixir plugin enabled

**Screenshots**
N/A

**Logs**
[intellij_thread_dumps_01072022.zip](https://github.com/KronicDeth/intellij-elixir/files/7831853/intellij_thread_dumps_01072022.zip)

**Desktop:**
 - OS: macOS
 - Version 11.6

**Erlang:**
- Installer asdf
- Version 22.3.4

**Elixir:**
- Installer asdf
- Version 1.10.3

**Plugin:**
- Version 12.1.0

**Additional context**
```
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Non-Bundled Plugins:
    org.jetbrains.plugins.localization (213.5744.190)
    com.intellij.plugins.watcher (213.6461.19)
    org.elixir_lang (12.1.0)
    intellij.prettierJS (213.6461.6)

Kotlin: 213-1.5.10-release-949-IJ6461.79
```

**Comment by cliftonmcintosh** [comment] 2022-01-09 16:06
I am having the same issue.

For me, it is only happening with some of my projects. Both of the projects I've seen it happen with are using Elixir 1.10.4 and Erlang 23. But I also have two other projects on those same Elixir and Erlang versions that haven't frozen.

One thing that happens before it freezes is that the syntax highlighting stops working. Generally speaking, when I scroll down through a file, the font colors change to indicate that the code has been parsed as new sections are loaded into view. In the projects that freeze, the font color changes that indicate the file has been parsed stop as I continue scrolling. I can still continue to navigate in the file for a little while after that, but it isn't long before IntelliJ becomes unresponsive.

**Thread dump logs from IntelliJ**
[threadDumps-freeze-20220109-093135-IU-213.6461.79.zip](https://github.com/KronicDeth/intellij-elixir/files/7835367/threadDumps-freeze-20220109-093135-IU-213.6461.79.zip)

**System information**
Plugin Version: 12.1.0
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (10.15.7)

**Details from the About IntelliJ dialog**
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2250M
Cores: 12

Non-Bundled Plugins:
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
    org.jetbrains.erlang (0.11.1129)
    org.elixir_lang (12.1.0)
    IdeaVIM (1.9.3)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (6.12.2)

Kotlin: 213-1.6.10-release-923-IJ5744.223

**Elixir and Erlang installed via asdf**
elixir 1.10.4-otp-23
erlang 23.2.7

**Comment by KronicDeth** [comment] 2022-01-14 15:49
From the first four thread dumps I've checked, it appears that this is happening when a the `Callable` annotator hits something that needs to be decompiled and parsed

```
	at com.intellij.psi.util.PsiTreeUtil.getChildrenOfTypeAsList(PsiTreeUtil.java:412)
	at com.intellij.psi.util.PsiTreeUtil.getChildrenOfType(PsiTreeUtil.java:390)
	at org.elixir_lang.psi.ElixirFile.modulars(ElixirFile.kt:116)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:411)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror$lambda-6$lambda-5(BeamFileImpl.kt:392)
	at org.elixir_lang.beam.psi.BeamFileImpl$$Lambda$9253/0x0000000803b4dc40.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$910/0x0000000800a1e840.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.kt:391)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:115)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.getNavigationElement(ModuleImpl.kt:111)
	at org.elixir_lang.reference.resolver.Module.multiResolveProject$lambda-10(Module.kt:116)
	at org.elixir_lang.reference.resolver.Module$$Lambda$9210/0x0000000803a5f440.process(Unknown Source)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:74)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:300)
	at com.intellij.psi.stubs.StubIndexImpl$$Lambda$8135/0x00000008014b1440.process(Unknown Source)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:346)
	at org.elixir_lang.reference.resolver.Module.multiResolveProject(Module.kt:113)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:75)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:67)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:34)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:30)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:22)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$9122/0x0000000803971c40.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$9123/0x0000000803971040.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:92)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:80)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:181)
	at org.elixir_lang.psi.Import.modulars(Import.kt:229)
	at org.elixir_lang.psi.Import.treeWalkUp(Import.kt:48)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:135)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:159)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:38)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:147)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:600)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:203)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:190)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:148)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:98)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:88)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:84)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:74)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:39)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:35)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$9122/0x0000000803971c40.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$9123/0x0000000803971040.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:97)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirMatchedQualifiedParenthesesCallImpl.accept(ElixirMatchedQualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
```

**Comment by KronicDeth** [comment] 2022-01-29 17:02
The ones I’ve looked at this is due to a reference resolution during the highlighting causing a file to be decompiled.  The decompiling is triggered because `.navigationElement` is called to make sure a source (either actual or decompile) is used as you can’t Go To Definition to a `PsiCompiledElement` that represent that binary `.beam` file modules and call definitions.

For the 2 weeks I’ve been placing a breakpoint in the decompiler and running the Elixir References inspection to see where it hits.  I’ve removed the `.navigationElement` calls as they have been hit, but I’ve also moved on to a larger change.

Currently, the tree is walked up for each reference as this walk API part of the JetBrains API, but the API is designed for much more static languages where the `PsiElement` in the tree are specific subclasses like `PsiClass` for the Java `class` syntax.  This is not possible with Elixir because everything is macros and almost everything, variables and function/macro calls are `Call`.  The tree walking checks if a `Call` is calling `defmodule` or `alias`, but there is no layer of just “give me all the modules” or “give me all the functions”.  This becomes slower for things that need to check `import` or `use` calls as they are all walked **for each function** that is not resolved by the time the `import` or `use` is hit.


I’m sick of the highlighting paint being noticeable, so during these past 2 weeks I’ve been rewriting the whole resolve layer and anything that checks if something was an definition, alias, import, etc to use cached `Semantic`s so the walk doesn’t have to recompute stuff.  Importantly the `Import`, `Use`, and `Modular` all cache what functions they define, so there’s no reason to walk into the `import` or `use` more than once.  This will speed up normal source to source resolution in addition to source to binary resolution.

This is a big re-write, it will take more weeks to complete as I only get 1-4 hours a night with extra time on DockYard Fridays between meetings.

**Comment by suryatejamuthyala** [comment] 2022-01-29 17:55
https://github.com/KronicDeth/intellij-elixir/issues/2484#issue-1111591446
[logs.zip](https://github.com/KronicDeth/intellij-elixir/files/7964264/logs.zip)

adding logs here

**Comment by steveops** [comment] 2022-01-29 18:50
Thanks for the update. Much appreciation for your time/effort on this project!

**Comment by cliftonmcintosh** [comment] 2022-01-29 20:38
@KronicDeth 

Thank you for the update. I really appreciate your efforts maintaining this plug-in. I find this plug-in extremely valuable.

**Comment by KronicDeth** [comment] 2022-01-30 14:06
Thought of something for the people that get lock up instead of just slow: older versions of IntelliJ shipped with a default max memory of 750M while newer versions ship with a default of 2G.  If you upgraded and transferred your settings through those versions you might be stuck at 750M.

I run with half (either 8G or 16G) my available laptop memory, use between 1.3-2.3G.  I don’t experience lock-up, only slowness sometimes.  Everyone try [increasing your max IDE JVM memory](https://www.jetbrains.com/help/idea/increasing-memory-heap.html) if you can.  Giving the JVM a little headroom helps keeping it from garbage collecting all the time.

**Comment by briefjudofox** [comment] 2022-02-01 01:08
@KronicDeth, thanks for the update and suggestion!  I usually set/adjust the heap size based on what I see on the [memory indicator](https://www.jetbrains.com/help/idea/increasing-memory-heap.html#enable-memory-indicator), but hearing that you run w/8G makes me feel like I'm not being generous enough with IntelliJ so I bumped it up a bit more 😃 .  

Thanks again for your work on this.  I really appreciate it!  When the time comes please lmk if I can help test any related changes.

**Comment by pjar** [comment] 2022-02-03 19:40
@KronicDeth Thank you for all the work!
Based on you suggestion about memory I've looked into setting and indeed it had been 750M. I've upped it to 2000M and the freeze happened like before. I have memory indicator in the IDE showing that it uses about 500M of 2000M.

**Comment by KronicDeth** [comment] 2022-02-03 19:46
@pjar please upload your thread dump logs and your `mix.lock` in a zip.  There might be a different reason or a different dependency that is more problematic.

**Comment by pjar** [comment] 2022-02-03 19:56
Here it is. It's hard to get it as the freeze sometimes is quicker than me when getting to the thread dump window: [report.zip](https://github.com/KronicDeth/intellij-elixir/files/7997737/report.zip)

**Comment by KronicDeth** [comment] 2022-02-03 20:07
@pjar any chance your project is open source OR a private repo you can add me to?  Being able to attach the debugger to a project exhibiting this problem would make it WAY faster to fix.

My current client project that is huge (221,296 lines) and I don't get lockup, so some specific dependency is affect you that I don't have.

**Comment by pjar** [comment] 2022-02-03 20:20
@KronicDeth I'd need to strip it out from implementation details, it's also a client project - I can do that tomorrow I guess, or over the weekend and push in this shape to temp private repo so I can add you to `it.` For now I'm almost sure that the issue is with the Coherence as I was getting errors about it in earlier versions and now this thread dump also suggests it.

**Comment by bobbybobbypangang** [comment] 2022-02-14 16:37
Hi, I also have this problem. Here are my logs and mix.lock:
[log.zip](https://github.com/KronicDeth/intellij-elixir/files/8062427/log.zip)
I'm working on a private project, so giving you access is not trivial, let me know if it would still help you a lot.

**Comment by mithereal** [comment] 2022-03-24 23:33
i am experiencing this issue since the new version of intellj, i noticed if i do not set the elixir facade sdk it doesnt freeze up anymore, still sucks the memory down but i guess its ti be expected. maybe this will help someone

**Comment by the-destro** [comment] 2022-03-29 19:17
Would a process sampling, ran when it is hung, be at all useful? I'll also see if I can replicate it.

**Comment by KronicDeth** [comment] 2022-03-29 21:41
@the-destro I know what's wrong.  I've known for since I posted on Jan 29th and I've been working on the rewrite since then.  It's a matter of time. If people want me to have more time to work on this you or your company need to hire me through DockYard to work on it because the only way for me to find more free time in my day is to be able to work on this Monday-Thursday during work hour.  Otherwise I get the time after my kid goes to bed and I've finished all my house work, so 0-4 hours a night with a stronger emphasis on 0-1 hours on most nights.

**Comment by elvanja** [comment] 2022-03-30 10:17
> i noticed if i do not set the elixir facade sdk it doesnt freeze up anymore, or crash due to an invalid cache

same here, thanks for the tip!

**Comment by the-destro** [comment] 2022-03-30 13:29
@the-destro totally understand. Family >> an IntelliJ plugin.  I'll also try giving even more headroom to IntelliJ(already at 8GB but I'll try more)

**Comment by KronicDeth** [comment] 2022-04-08 16:04
The Semantic layering was taking too long. I've shelved it at https://github.com/KronicDeth/intellij-elixir/tree/semantic.  

I'm re-attempting a minimal change of having everything that expects Modulars to be `Call`s to be `PsiElement` and see where I need to handle both `Call` and `ModuleImpl` without changing them otherwise.  There is still a chance that this could cause hidden bugs where I did `as? Call` which will silently fail if something isn't a `Call`.

**Comment by KronicDeth** [comment] 2022-04-08 16:21
Also `Call` and `CallDefinitionImpl` for call definition clauses

**Comment by KronicDeth** [comment] 2022-04-14 17:11
I stopped hitting `.navlgationElement` and `decompile` calls in the debugger when using `Elixir References` on `ecto/lib`, so I'm testing this on a client project for lock ups now.  Anyone else is free to try it out to see if it fixes their issues.

[intellij-elixir-12.2.1-pre+20220414170406.zip](https://github.com/KronicDeth/intellij-elixir/files/8491038/intellij-elixir-12.2.1-pre%2B20220414170406.zip)

If we do see more lock ups then it's not just the `.navigationElement` and we have more than one issue really.

**Comment by elvanja** [comment] 2022-04-14 17:39
Checked with a project that was previously freezing after about 1-2 minutes. After 30 minutes still working normally, no hiccups whatsoever. I am on IntelliJ IDEA 2021.3.3 (Ultimate Edition), build #IU-213.7172.25 from March 15, runtime version: 11.0.14.1+1-b1751.46 x86_64, VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. So, it sounds like a success, at least from this one small sample 👍🏼 ❤️ 🙇🏼

**Comment by KronicDeth** [comment] 2022-04-14 18:02
There’s a TODO I need to fix and a freeze I hit on the client project.  I need to reproduce it under the debugger.  I think it’s related to callable completion off of an Alias

**Comment by briefjudofox** [comment] 2022-04-14 19:45
@KronicDeth I've been using your pre-release build for a couple of hours and so far I've seen no issues!!! 🙇 🙏 

I'm on:
```
Build #IU-213.7172.25, built on March 15, 2022
Runtime version: 11.0.14.1+1-b1751.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

Thanks again for all your work on this!

**Closed** 2022-04-18 01:55 UTC
Labels: Category:Performance

**Comment by pjar** [comment] 2022-04-19 14:49
Unfortunately it freezes for me still. I'll try to push some details later.

**Comment by KronicDeth** [comment] 2022-04-19 15:05
> Unfortunately it freezes for me still. I'll try to push some details later.

Please open it as a new issue.  If you’re still having an issue it’s root cause is unrelated to this issue.
