### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by pdmoore** [KronicDeth/intellij-elixir#2791] opened 2022-08-12 04:15 UTC
# System

Plugin Version: 13.2.0
Application: RubyMine (2022.2)
Operating System: Mac OS X (12.3.1)

# Event

### Element

```
,
```

From: `/Users/pdm/Code/exercism/elixir/freelancer-rates/lib/freelancer_rates.ex:14`

#### Context

```

  def monthly_rate(hourly_rate, discount) do
    before_discount = ceil(@hours_per_day * hourly_rate * 22)
  end

  def days_in_budget(budget, hourly_rate, discount) do
    first = Float.floor(budget / (hourly_rate * @hours_per_day), 1)
    apply_discount(first, )
  end
end

```

From: `/Users/pdm/Code/exercism/elixir/freelancer-rates/lib/freelancer_rates.ex:9-19`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by styx** [comment] 2022-08-12 07:29
#2792 I attached my mix.ex there.

**Comment by KronicDeth** [comment] 2022-08-12 12:40
Duplicate of #2774

**Closed by KronicDeth** 2022-08-12 12:40 UTC
