### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.13.4-otp-25` is missing Erlang SDK at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)

### ISSUE THREAD

**Issue by chwarner-jg** [KronicDeth/intellij-elixir#2786] opened 2022-08-09 17:50 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.5)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.13.4-otp-25` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.13.4-otp-25` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:85)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-24 14:14
Duplicate of #2747

**Closed by KronicDeth** 2022-08-24 14:14 UTC
