### ISSUE TITLE
[auto-generated] java.lang.AssertionError at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement

### ISSUE THREAD

**Issue by dabaer** [KronicDeth/intellij-elixir#593] opened 2017-01-22 03:41 UTC
# Version

4.7.0

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:38)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:147)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.components.WideSelectionListUI.paintCell(WideSelectionListUI.java:47)
	at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:317)
	at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
	at com.intellij.ui.components.WideSelectionListUI.paint(WideSelectionListUI.java:31)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:181)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at com.intellij.ui.components.JBList.paint(JBList.java:114)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:129)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuf

**Comment by KronicDeth** [comment] 2017-01-29 01:05
Duplicate of #563

**Closed by KronicDeth** 2017-01-29 01:05 UTC
