### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#2850] opened 2022-09-12 17:38 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (12.4)

# Event

### Element

```
->
```

From: `/Users/ubi/Developer/code.hmbradley.io/core/backend/hmbradley_umbrella/apps/hmbradley/lib/hmbradley/dev_ops/thought_machine.ex:12`

#### Context

```

  def create_all_posting_api_clients do
    request_id = 

    Task.await_many([
      Task.async(fn -> create_plan_transfers_postings_api_client(Uniq.UUID.uuid4()) end),
      Task.async(fn -> create_operational_transfers_postings_api_client(Uniq.UUID.uuid4()) end),
      Task.async(fn -> create_internal_transfers_postings_api_client(Uniq.UUID.uuid4()) end),
      Task.async(fn -> create_odfi_ach_transfers_postings_api_client(Uniq.UUID.uuid4()) end),
      Task.async(fn -> create_remediation_transfers_postings_api_client(Uniq.UUID.uuid4()) end),
      Task.async(fn -> create_rdfi_ach_transfers_postings_api_clientUniq.UUID.uuid4()request_id) end)
```

From: `/Users/ubi/Developer/code.hmbradley.io/core/backend/hmbradley_umbrella/apps/hmbradley/lib/hmbradley/dev_ops/thought_machine.ex:7-17`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-16 16:28
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-09-16 16:28 UTC
