### ISSUE TITLE
java.lang.IllegalStateException: seed must not be null at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)

### ISSUE THREAD

**Issue by sandergol** [KronicDeth/intellij-elixir#2829] opened 2022-09-01 09:22 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (11.6.8)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: seed must not be null
</summary>

```
java.lang.IllegalStateException: seed must not be null
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions$default(PsiElementImpl.kt:213)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-11 14:53
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2773

**Closed by KronicDeth** 2022-09-11 14:53 UTC
