### ISSUE TITLE
The plugin works very slow with the new version

### ISSUE THREAD

**Issue by gazoon** [KronicDeth/intellij-elixir#979] opened 2018-01-06 11:39 UTC
Hi! I updated the plugin to the last version (7.2.0). And after that every my input has 2-3 seconds delay and this only happens when i am editing Elixir files (*.ex). I downgraded to the old version 6.7.0 and now it works acceptable, there are still some delays on input compered to the java code typing, but it's fine. Am i the only one who has that problem?

**Comment by jamiecurle** [comment] 2018-01-06 13:33
As mentioned by [KronicDeth in this issue](https://github.com/KronicDeth/intellij-elixir/issues/967#issuecomment-354617813), try [turning off the credo annotator](https://github.com/KronicDeth/intellij-elixir#configuration).

I had similar issues to what you were describing which were solved by the above advice.

**Comment by KronicDeth** [comment] 2018-01-06 15:49
Duplicate of #970.  Subscribe to that issue.

**Closed by KronicDeth** 2018-01-06 15:49 UTC
