### ISSUE TITLE
Elixir SDK not found on OSX Yosemite with Intellij 14

### ISSUE THREAD

**Issue by chrisatcodedmarkets** [KronicDeth/intellij-elixir#190] opened 2015-09-13 22:05 UTC
Given:
- Plugin installed
- Elixir installed via Brew
- 'which elixir' returns '/usr/local/bin/elixir' 
- 'elixir --version' returns 'Elixir 1.0.5'

When:
- New Elixir project in Intellij with Bash Support and SQL Support

Then:
- Project SDK dialog says 'Nothing to Show'

---

Workaround:
- Create symlink to elixir: ln -s /usr/local/Cellar/elixir/1.0.5 elixir-1.0.5 (reason for the symlink is that the Intellij folder dialog does not show or allow selection from hidden directories, like /usr/)
- On Project SDK dialog, hit Configure and select the elixir-1.0.5 directory

**Comment by KronicDeth** [comment] 2015-09-14 02:42
Thanks you, this is a very nice bug report.  My directory structure appears the same as yours.  What are the permissions on `/usr/local/Cellar/1.0.5`?  Mine (`ls -la /usr/local/Cellar/elixir`) are

```
total 0
drwxr-xr-x   3 luke.imhoff  admin   102 Aug  9 18:49 .
drwxr-xr-x  97 luke.imhoff  admin  3298 Sep  4 21:55 ..
drwxr-xr-x   8 luke.imhoff  admin   272 Jul 29 20:27 1.0.5
```

**Comment by chrisatcodedmarkets** [comment] 2015-09-14 03:06
No problem. Thanks for the plugin! Here are my perms:

```
$ ls -la /usr/local/Cellar/elixir
```
```
total 0
drwxr-xr-x   3 chris  admin   102B Sep 13 17:45 .
drwxr-xr-x  30 chris  admin   1.0K Sep 13 19:07 ..
drwxr-xr-x   8 chris  admin   272B Sep 13 17:45 1.0.5
```

**Comment by KronicDeth** [comment] 2015-09-14 23:53
I recall sometimes IntelliJ and Websphere can't see my home directory in the Open Project dialog.  I'm wondering if it's a general JetBrains' API level bug and not just my plugin since I'm not see any reason your setup is different from my setup and mine works except for the weird hiccups when sometimes directories don't show up in the picker.

**Comment by KronicDeth** [comment] 2015-09-14 23:54
If you don't use the work-around can you reliably reproduce the bug?

**Comment by zyuyou** [comment] 2015-09-15 01:06
I had try `New Elixir project in Intellij with Bash Support and SQL Support` on Ubuntu, also with symlink, but it works fine. I will try it on my mac tonight.

**Comment by lrhazi** [comment] 2015-12-20 23:01
I have same issue (using El Capitan)... IntelliJ (15.0.2) says the SDK it found in (/usr/local/Cellar/elixir/1.1.1) maybe corrupt. It says "Unknown Elixir version".

```
Workaround:

Create symlink to elixir: ln -s /usr/local/Cellar/elixir/1.0.5 elixir-1.0.5 (reason for the symlink is that the Intellij folder dialog does not show or allow selection from hidden directories, like /usr/)
```

Where is this symlink created at?

**Comment by KronicDeth** [comment] 2015-12-21 00:34
@lrhazi, it's a standard terminal command to create a symlink in the current directory.  So, just run it when the current working directory is a directory that IntelliJ can see, such as your home directory, which should be the default directory when opening Terminal or iTerm.

**Comment by KronicDeth** [comment] 2016-03-21 00:25
Closing due to no feedback for 3 months

**Comment by iliaznk** [comment] 2016-08-19 11:51
That button shows hidden files and folders.
<img width="485" alt="screen shot 2016-08-19 at 14 49 38" src="https://cloud.githubusercontent.com/assets/6253368/17809042/79d5c8d2-661c-11e6-98b9-08b91cccbf9e.png">

**Comment by RyanKim01** [comment] 2017-05-14 19:12
Was this ever got figured out? I've installed Elixir plugin in IntelliJ IDE and not seeing and SDK to run on. I did install Elixir via Homebrew on my Mac OS.

**Comment by KronicDeth** [comment] 2017-05-15 12:25
@RyanKim01 no, because it's not reproducible on any of the core team's machines and feedback stopped.  Have you tried the hidden folders button @iliaznk posted a screenshot of?

**Comment by RyanKim01** [comment] 2017-05-15 16:53
@KronicDeth I'm not sure where I can find that button in the Settings. Can you tell me where that is? I've deleted and reinstalled the Elixir plugin for Intellij several times and SDKs do now show up everytime.

**Comment by KronicDeth** [comment] 2017-05-15 16:57
@RyanKim01 this is easiest if you just screenshare with me. Can you screenshare over Google Hangouts?  My emails on my profile https://github.com/KronicDeth if you want to connect and screenshare, so I can see what's happening myself.

**Comment by raul782** [comment] 2017-05-20 07:46
Hello guys, were this issue solved?
@KronicDeth , I'm having the same issue:
- macOS Sierra
- IntelliJ IDEA Ultimate 2017.1.3
- Plugin installed - version 5.1.0
- Elixir installed via Brew
- 'which elixir' returns '/usr/local/bin/elixir'
- 'elixir --version' returns 'Elixir 1.4.2'

Project finds the folder but I get the following message:
Cannot Detect SDK Version: Probably SDK installed in '/usr/local/Cellar/elixir/1.4.2' is corrupt.

What is supposed to be the workaround, what should be the absolute path for the link:
I tried the following:
$ln -s /usr/local/Cellar/elixir/1.4.2 /usr/local/Cellar/elixir/elixir-1.4.2
But that made IntelliJ throw a different error.

**Comment by KronicDeth** [comment] 2017-05-20 12:37
The `"Cannot Detect SDK Version: Probably SDK installed in '{homePath}' is corrupt"` message is provided by intellij-community's `com.intellij.openapi.projectRoots.ui.SdkEditor.doSetHomePath`

> ```java
>  myVersionString = dummySdk.getVersionString();
>      if (myVersionString == null) {
>        Messages.showMessageDialog(ProjectBundle.message("sdk.java.corrupt.error", homePath),
>                                   ProjectBundle.message("sdk.java.corrupt.title"), Messages.getErrorIcon());
>      }
> ```
> -- https://github.com/JetBrains/intellij-community/blob/171.4424/java/idea-ui/src/com/intellij/openapi/projectRoots/ui/SdkEditor.java#L330-L334

So, I can't really make it clearer in the dialog without completely replacing the dialog.  (If you're wondering why the translation key, `sdk.java.corrupt.title`, has `java` in it: sometimes IntellIJ still shows its history of being a Java IDE first)

The `getVersionString` that matters in `intellij-elixir` is 

> ```java
>  @Nullable
>  @Override
>  public String getVersionString(@NotNull String sdkHome) {
>    return getVersionString(detectSdkVersion(sdkHome));
>  }
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/src/org/elixir_lang/sdk/ElixirSdkType.java#L99-L103

Which means that it's really `detectSdkVersion` that fails

> ```java
>  @Nullable
>  public ElixirSdkRelease detectSdkVersion(@NotNull String sdkHome){
>    ElixirSdkRelease cachedRelease = mySdkHomeToReleaseCache.get(getVersionCacheKey(sdkHome));
>    if(cachedRelease != null){
>      return cachedRelease;
>    }
>
>    File elixir = JpsElixirSdkType.getScriptInterpreterExecutable(sdkHome);
>    if(!elixir.canExecute()){
>      String reason = elixir.getPath() + (elixir.exists() ? " is not executable." : " is missing.");
>      LOG.warn("Can't detect Elixir version: " + reason);
>      return null;
>    }
>
>    ElixirSdkRelease release = transformStdoutLine(
>            new Function<String, ElixirSdkRelease>() {
>              @Override
>              public ElixirSdkRelease fun(String line) {
>                return ElixirSdkRelease.fromString(line);
>              }
>            },
>            STANDARD_TIMEOUT,
>            sdkHome,
>            elixir.getAbsolutePath(),
>            "-e",
>            "IO.puts System.build_info[:version]"
>    );
>
>    if (release != null) {
>      mySdkHomeToReleaseCache.put(getVersionCacheKey(sdkHome), release);
>    }
>
>    return release;
>  }
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/src/org/elixir_lang/sdk/ElixirSdkType.java#L213-L246

So, the two ways to get a `null` is either
1. The computed `File elixir` is not executable or missing, in which case you should be able to see an warning in the IntelliJ log due to the `LOG.warn` call.
2. Calling `elixir -e "IO.puts System.build_info[:version]"` either
  a. Does not work 
  b. Does not have a dotted version format that `ElixirSdkRelease.fromString(line)` can parse

So, if there's no warning on your log, run `elixir -e "IO.puts System.build_info[:version]"` and post it

**Comment by raul782** [comment] 2017-05-20 14:46
1. I don't see any LOG.warn call in the Event Log
2. The result for running this command: elixir -e "IO.puts System.build_info[:version]" : `1.4.2`

**Comment by rafaelbarreto87** [comment] 2017-05-21 05:29
I'm seeing exact same thing with same configuration. In the logs I get this stack trace:

```
2017-05-20 22:26:32,876 [1731888]   WARN - n.process.BaseOSProcessHandler - Must specify non-empty 'commandLine' parameter
java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
        at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:65)
        at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:67)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:58)
        at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:45)
        at org.elixir_lang.sdk.ElixirSystemUtil.execute(ElixirSystemUtil.java:95)
        at org.elixir_lang.sdk.ElixirSystemUtil.getProcessOutput(ElixirSystemUtil.java:85)
        at org.elixir_lang.sdk.ElixirSystemUtil.transformStdoutLine(ElixirSystemUtil.java:61)
        at org.elixir_lang.sdk.ElixirSdkType.detectSdkVersion(ElixirSdkType.java:227)
        at org.elixir_lang.sdk.ElixirSdkType.getVersionString(ElixirSdkType.java:102)
        at com.intellij.openapi.projectRoots.SdkType.getVersionString(SdkType.java:83)
```

**Comment by rafaelbarreto87** [comment] 2017-05-21 05:57
I explored this a bit more and I noticed it works fine if I start IntelliJ from the terminal, like `open -a "IntelliJ IDEA Community"`. `/usr/local/bin` is not in the `PATH` for the graphical applications, which appears to be the thing causing the problem.

**Comment by KronicDeth** [comment] 2017-05-21 15:53
So, for https://github.com/KronicDeth/intellij-elixir/issues/190#issuecomment-302916236, we need to add a try catch, so that the error message can say what path is empty since the current error is not terribly clear.

**Comment by raul782** [comment] 2017-05-22 03:03
Alright so, in the end I built the plugin and found the root error:
`/usr/local/bin/elixir:` line 126: exec: erl: not found`

So it looks like that IntelliJ doesn't load your terminal PATH but a really basic one. It's a known issue I wasn't aware.
The fastest way for is that I ended up patching elixir by forcing the setup of this path:
`ERL_PATH="/usr/local/Cellar/erlang/19.3/bin/erl"`
I've seen these workarounds, but I didn't like them
http://depressiverobot.com/2016/02/05/intellij-path.html

@KronicDeth, as you mentioned on slack, It would be great to add a way to select the Erlang version, otherwise the solutions I've seen to mess with IntelliJ feels like a hack.

I'll open an issue to work on that, though I might need some guidance to implement it.

**Comment by KronicDeth** [comment] 2017-05-24 02:10
@raul782 adding the ability to select the Erlang path first can be solved a number of way:

1. Set the Erlang path as a global setting the way the mix path is now
2. Set the Erlang path on a per-project setting
3. Modify the GUI to allow the Erlang path to be selected first, then add it as a custom field to the Elixir SDK object.
4. Allow Erlang SDK to be selected first, then have the Elixir SDK point to it.   There are a couple pre-existing solutions like this:
  1. The IntelliJ Plugin SDK requires that you first select a Java SDK.
  2. I have heard described, but not checked for myself that Clojure is treated as a "framework" on top of the Java SDK in the Cursive IDE

I find (4) the most correct solution because it would allow you to potentially be able to work on both the Elixir and Erlang code for Elixir itself, but there are some caveats with (4).  Since an Erlang plugin already exists for IntelliJ, `intellij-erlang`, it would probably be nice to detect if it is installed and if it is to use their SDK class, but if it's not installed to have some minimum Erlang SDK.  You would have to read up on how to declare optional dependencies for the `intellij-gradle-plugin` Gradle system and how to declare it correctly in the `plugin.xml`s so that it really is optional.  I think it's a bit much to require people to install intellij-erlang to get intellij-elixir to work even if I personally happen to have both installed.

**Comment by raul782** [comment] 2017-05-25 06:11
@KronicDeth Thanks, yeah (4) seems to be the best option so far. I'll give it a try and update my findings on this issue: https://github.com/KronicDeth/intellij-elixir/issues/701

**Comment by KronicDeth** [comment] 2017-06-11 20:18
Closing in favor of #701 as the outlines the work to be done.  Go click subscribe to that issue if this issue is still a problem for your Erlang+Elixir setup.

**Closed by KronicDeth** 2017-06-11 20:18 UTC
Labels: bug, waiting on feedback

**Comment by aamerabbas** [comment] 2018-01-12 18:33
Had the same issue. It was due to $PATH not being included by IntelliJ. This solution worked for me:
http://depressiverobot.com/2016/02/05/intellij-path.html
