### ISSUE TITLE
Very weird syntax highlight

### ISSUE THREAD

**Issue by wbednarski** [KronicDeth/intellij-elixir#654] opened 2017-03-25 00:48 UTC
![messages image 3625375297](https://cloud.githubusercontent.com/assets/282476/24317820/461b5fa8-10fc-11e7-8a9f-dfba1aafa442.png)

```
IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```

**Comment by KronicDeth** [comment] 2017-03-27 18:29
Duplicate of #571.  Fixed by bug fixes in #638.  Root cause was the annotator was trying to highlight  the resolved call definition clauses without checking that it was in the same file, so write file offset, wrong file.

**Closed by KronicDeth** 2017-03-27 18:29 UTC
Labels: bug, duplicate
