### ISSUE TITLE
NPE trying to getPresentation()

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#542] opened 2016-11-29 20:09 UTC
# Version

4.6.0

# Exception

## Message

Sorry if this is a dupe of something I already filed

## Stacktrace

```
java.lang.NullPointerException
	at org.elixir_lang.structure_view.element.CallDefinition.getPresentation(CallDefinition.java:245)
	at org.elixir_lang.structure_view.element.CallDefinitionClause.getPresentation(CallDefinitionClause.java:346)
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:46)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.renderItemApproximately(LookupImpl.java:434)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:234)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:408)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:399)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$0(CompletionThreading.java:139)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:107)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:877)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2016-11-29 21:25
Duplicate of #507.  Fixed by #537.  When searching for closed issues, you need to use the full `nullpointerexception` since Github's search system searches whole words.

**Closed by KronicDeth** 2016-11-29 21:25 UTC
Labels: bug, duplicate
