### ISSUE TITLE
Syntax highlighting is broken frequently after upgrade plugin to 11.9.0

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1874] opened 2021-01-12 19:16 UTC
**Describe the bug**
After upgrade plugin to 11.9.0, syntax highlighting is broken frequently.

**To Reproduce**

1. Create new elixir module
2. Write a function definition
  ```elixir
  def test do
  end
  ```
3. Type `Map.put(%{}, :a, 1)` in function body.
4. Syntax highlighting is broken at `end` after typing `:a`, and some typing completion do not work(when I type `(`, corresponding `)` is not put).

When I reopen the file, syntax highlighting and and typing completion is fixed.

**Expected behavior**
Correct syntax highlighting.

**Screenshots**
<img width="287" alt="スクリーンショット 2021-01-13 3 52 57" src="https://user-images.githubusercontent.com/1321120/104359649-44367c00-5553-11eb-9258-14c89e2029bd.png">

**Desktop:**
 - OS: macOS Catalina
 - Version 10.15.7

**Erlang:**
- Installer asdf
- Version 22.0.7

**Elixir:**
- Installer asdf
- Version 1.10.3-otp-22

**Editor:**
- IntelliJ IDEA 2020.2.4 (Ultimate Edition)

**Plugin:**
- Version 11.9.0

**Comment by KronicDeth** [comment] 2021-01-12 23:16
@odk211 I'm also see this.  The only actual error report I see are due to mirror errors in the decompiler though.  Might be related though because it is issues with the Kernel mirrors.

**Comment by KronicDeth** [comment] 2021-01-15 04:08
Duplicate of #1686

**Comment by KronicDeth** [comment] 2021-01-15 04:08
Fixed in #1877.

**Closed by KronicDeth** 2021-01-15 04:08 UTC
Labels: Kind:Bug:Regression
