### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by williamgueiros** [KronicDeth/intellij-elixir#177] opened 2015-07-25 04:04 UTC
hello...

do you know, where i find documentation, to create integration with debugger in this project??
i lost a lot of time on google but i can't found.

**Comment by zyuyou** [comment] 2015-07-25 08:23
You mean debug this plugin project or elixir-project?

**Comment by williamgueiros** [comment] 2015-07-25 15:53
In elixir do you have a possibility to using debugger.
http://www.jessetrimble.net/iex-pry-elixir/

but putting any information in you code only to debugger is not beautiful, and if i forget this line your project, he will go stopping in production and you will not know why.
in the past people putting debugger in middle of javascript code to debugger.

do you know, how I can create logic to breakpoints works on intellij.

i don't know is possible, people create breakpoint and i add extra information in source but hidden like delphi, but to me that not a good alternative, if you forget brakingpoint do you have bad code?

**Comment by zyuyou** [comment] 2015-07-25 17:17
For now, the elixir debugger had not been implemented in IDEA, so you may just lost a lot of time on creating integration with debugger in elixir-project.

You can keep following the debugger's developments in issue #81 .

**Comment by williamgueiros** [comment] 2015-07-25 18:26
:+1: I will try to help you in debugger implement

**Comment by KronicDeth** [comment] 2015-07-25 20:33
As stated in #81, @williamgueiros, my working plan is to look at what intellij-erlang did and adapt it as needed for Elixir.  Since Elixir passes the original Elixir lines into the compiled beams, it may just work, but I haven't read enough of the intellij-erlang debugger code to see if it's dependent on anything other than line number (such as something derived from the parser).  Closing this as a duplicate of #81.  Please continue discussion there.

**Closed by KronicDeth** 2015-07-25 20:33 UTC
Labels: duplicate, enhancement
