### ISSUE TITLE
DELEGATION Icon uses removed AllIcons.General.Run

### ISSUE THREAD

**Issue by DevWasi** [KronicDeth/intellij-elixir#1750] opened 2020-04-11 09:18 UTC
# Exception

## Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.Icons
	at org.elixir_lang.ElixirFileType.getIcon(ElixirFileType.java:40)
	at com.intellij.psi.impl.ElementBase.getBaseIcon(ElementBase.java:131)
	at com.intellij.psi.impl.ElementBase.computeBaseIcon(ElementBase.java:114)
	at com.intellij.psi.impl.ElementBase.lambda$computeIcon$1(ElementBase.java:87)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:87)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:68)
	at org.elixir_lang.psi.ElixirFile.getIcon(ElixirFile.java:44)
	at com.intellij.ide.navigationToolbar.NavBarPresentation.lambda$getIcon$0(NavBarPresentation.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.ide.navigationToolbar.NavBarPresentation.getIcon(NavBarPresentation.java:63)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:58)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:96)
	at com.intellij.ide.navigationToolbar.NavBarPopup.lambda$createPopupContent$2(NavBarPopup.java:163)
	at com.intellij.ui.components.SelectionAwareListCellRenderer.getListCellRendererComponent(SelectionAwareListCellRenderer.java:24)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:186)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1683)
	at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:182)
	at com.intellij.ide.navigationToolbar.NavBarListWrapper.<init>(NavBarListWrapper.java:64)
	at com.intellij.ide.navigationToolbar.NavBarPopup.createPopupContent(NavBarPopup.java:173)
	at com.intellij.ide.navigationToolbar.NavBarPopup.<init>(NavBarPopup.java:42)
	at com.intellij.ide.navigationToolbar.NavBarPanel.ctrlClick(NavBarPanel.java:582)
	at com.intellij.ide.navigationToolbar.NavBarPanel.access$100(NavBarPanel.java:77)
	at com.intellij.ide.navigationToolbar.NavBarPanel$3.click(NavBarPanel.java:484)
	at com.intellij.ide.navigationToolbar.NavBarPanel$3.mousePressed(NavBarPanel.java:475)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by KronicDeth** [comment] 2020-04-11 16:35
Duplicate of #1654.

**Closed by KronicDeth** 2020-04-11 16:35 UTC
Labels: Closed:Duplicate, Kind:Bug
