### ISSUE TITLE
NullPointerException getting Call.finalArguments() at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:146)

### ISSUE THREAD

**Issue by pdmoore** [KronicDeth/intellij-elixir#3078] opened 2023-02-24 02:37 UTC
# System

Plugin Version: 13.2.1
Application: RubyMine (2022.3.2)
Operating System: Mac OS X (13.2.1)

# Event

### Element

```
-
```

From: `/Users/pdm/Code/exercism/elixir/robot-simulator/lib/robot_simulator.ex:32`

#### Context

```
  """
  @spec simulate(robot, instructions :: String.t()) :: robot() | {:error, String.t()}
  def simulate(robot, instructions) do
    case robot[:direction] do
      :north -> %{:direction => :east, :position => robot[:position]}
      - -> %{:direction => :east, :position => robot[:position]}
    end
  end

  @doc """
  Return the robot's direction.
```

From: `/Users/pdm/Code/exercism/elixir/robot-simulator/lib/robot_simulator.ex:27-37`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedUnaryOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: NullPointerException getting Call.finalArguments()
</summary>

```
java.lang.Throwable: NullPointerException getting Call.finalArguments()
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:146)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArguments(CallImpl.kt:172)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArgument(CallImpl.kt:163)
	at org.elixir_lang.psi.impl.call.CallImpl.hasDoBlockOrKeyword(CallImpl.kt:412)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:1098)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:237)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:410)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:63)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:380)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:46)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:380)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:46)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:317)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:53)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:281)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:663)
	at org.elixir_lang.psi.impl.ElixirStabOperationImpl.processDeclarations(ElixirStabOperationImpl.java:69)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Identifier.resolveElement(Identifier.kt:16)
	at org.elixir_lang.reference.resolver.Identifier.resolve(Identifier.kt:10)
	at org.elixir_lang.reference.resolver.Identifier.resolve(Identifier.kt:8)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Identifier.multiResolve(Identifier.kt:25)
	at org.elixir_lang.annotator.Callable$annotate$1.visitUnqualifiedBracketOperation(Callable.kt:147)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:81)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedExpressionImpl.accept(ElixirUnmatchedExpressionImpl.java:27)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedBracketOperationImpl.accept(ElixirUnmatchedUnqualifiedBracketOperationImpl.java:28)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
```

</details>

**Comment by KronicDeth** [comment] 2023-04-07 19:14
Duplicate of #3059

**Closed by KronicDeth** 2023-04-07 19:14 UTC
