### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by korczis** [KronicDeth/intellij-elixir#2846] opened 2022-09-09 18:33 UTC
# System

Plugin Version: 13.2.0
Application: WebStorm (2022.1.1)
Operating System: Mac OS X (12.4)

# Event

### Element

```
end
```

From: `/Users/korczis/dev/only1/only1-ex/apps/only1/lib/only1/accounts/accounts.ex:289`

#### Context

```
      follower: follower,
      following: following
    }
    |> Repo.delete()
  end
end

```

From: `/Users/korczis/dev/only1/only1-ex/apps/only1/lib/only1/accounts/accounts.ex:284-290`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-10 15:00
Duplicate of #2774

**Closed by KronicDeth** 2022-09-10 15:00 UTC
