### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by olivermt** [KronicDeth/intellij-elixir#2982] opened 2023-01-01 15:58 UTC
# System

Plugin Version: 14.0.0
Application: WebStorm (2022.3.1)
Operating System: Mac OS X (13.0.1)

# Event

No idea what makes it happen, it seems to have no ill side effects and I can't see any pattern to what it does
### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2023-01-27 16:20
Duplicate of #2817

**Closed by KronicDeth** 2023-01-27 16:20 UTC
