### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by IcyEagle** [KronicDeth/intellij-elixir#810] opened 2017-08-27 13:14 UTC
# Version

5.1.0

# Exception

## Message

org/junit/ComparisonFailure

## Stacktrace

```
java.lang.NoClassDefFoundError: org/junit/ComparisonFailure
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quoteLiteral(ElixirPsiImplUtil.java:4714)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quoteLiteral(ElixirStringLineImpl.java:90)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quotedChildNodes(ElixirPsiImplUtil.java:5772)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quotedChildNodes(ElixirPsiImplUtil.java:5730)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quote(ElixirPsiImplUtil.java:3530)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quote(ElixirStringLineImpl.java:70)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quoteAsAtom(ElixirPsiImplUtil.java:3301)
	at org.elixir_lang.psi.impl.ElixirStringLineImpl.quoteAsAtom(ElixirStringLineImpl.java:75)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.quote(ElixirPsiImplUtil.java:3690)
	at org.elixir_lang.psi.impl.ElixirKeywordKeyImpl.quote(ElixirKeywordKeyImpl.java:56)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasKeywordKey(ElixirPsiImplUtil.java:3107)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordValue(ElixirPsiImplUtil.java:778)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.keywordArgument(ElixirPsiImplUtil.java:750)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:3084)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.useScopeSelector(ElixirPsiImplUtil.java:586)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.createsNewScope(ElixirPsiImplUtil.java:599)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1705)
	at org.elixir_lang.psi.ElixirFile.processDeclarations(ElixirFile.java:52)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:42)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve.resolveResultList(MultiResolve.java:32)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:705)
	at org.elixir_lang.reference.Callable.resolve(Callable.java:730)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:389)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:366)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:236)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:208)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.junit.ComparisonFailure PluginClassLoader[org.elixir_lang, 5.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@6bba22d6
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

```

**Comment by KronicDeth** [comment] 2017-08-27 22:39
Duplicate of #714.  Fixed by #773.  Upgrade to v6.0.0 or later to have the fix.

**Closed by KronicDeth** 2017-08-27 22:39 UTC
