### ISSUE TITLE
Read access is allowed from event dispatch thread at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173) 	

### ISSUE THREAD

**Issue by corgifist** [KronicDeth/intellij-elixir#2040] opened 2021-08-02 13:09 UTC
# Version

11.10.0

# What I was doing

I just wanted to run the project, and then I saw this exception

# Exceptions

### Stacktrace

```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.getSortedModules(ModuleManagerImpl.java:603)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.getContentRootsFromAllModules(ProjectRootManagerImpl.java:184)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:173)
	at org.elixir_lang.DepsWatcher$syncLibraries$$inlined$let$lambda$1.run(DepsWatcher.kt:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KronicDeth** [comment] 2022-01-07 17:24
Duplicate of #1900

**Closed by KronicDeth** 2022-01-07 17:24 UTC
Labels: Kind:Bug
