### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:275)

### ISSUE THREAD

**Issue by UsamaHaide0786** [KronicDeth/intellij-elixir#2859] opened 2022-09-17 11:52 UTC
# System

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Mac OS X (11.6.2)

# Event

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:275)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:71)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:70)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:67)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:71)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClauseExpression$1.invoke(Assign.kt:70)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.foldWhile(Modular.kt:28)
	at org.elixir_lang.psi.AccumulatorContinue$Companion.childExpressionsFoldWhile(Modular.kt:19)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressionsFoldWhile(PsiElementImpl.kt:210)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClauseExpression(Assign.kt:67)
	at org.elixir_lang.leex.reference.resolver.Assign.access$resolveInCallDefinitionClauseExpression(Assign.kt:21)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign$resolveInCallDefinitionClause$1.invoke(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:740)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInCallDefinitionClause(Assign.kt:59)
	at org.elixir_lang.leex.reference.resolver.Assign.resolveInViewModule(Assign.kt:55)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:28)
	at org.elixir_lang.leex.reference.resolver.Assign.resolve(Assign.kt:21)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.leex.reference.Assign.multiResolve(Assign.kt:18)
```

**Comment by KronicDeth** [comment] 2023-03-17 20:18
In 12.0.1

https://github.com/KronicDeth/intellij-elixir/blob/4166e08058f7e52b8787e56b5cadadd4b8b3e517/src/org/elixir_lang/leex/reference/resolver/Assign.kt#L64-L277

**Comment by KronicDeth** [comment] 2023-03-17 20:20
In `main`

https://github.com/KronicDeth/intellij-elixir/blob/main/src/org/elixir_lang/leex/reference/resolver/Assign.kt#L76-L318

Line 314 has a proper error reporting logger with the element being reported

https://github.com/KronicDeth/intellij-elixir/blob/3d2fa566fe3cce90d1ab70e06d8234db3551d1f8/src/org/elixir_lang/leex/reference/resolver/Assign.kt#L313-L317

This was added in https://github.com/KronicDeth/intellij-elixir/commit/b8d2bd2a242e66892e53dccba8e0dc9fddc31214, which is part of https://github.com/KronicDeth/intellij-elixir/pull/3040 that fixed https://github.com/KronicDeth/intellij-elixir/issues/3020

**Comment by KronicDeth** [comment] 2023-03-17 20:21
Duplicate of #3020

**Closed by KronicDeth** 2023-03-17 20:21 UTC
Labels: Kind:Bug
