### ISSUE TITLE
[auto-generated] @NotNull method FindUsagesProvider.getType returned null

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#280] opened 2016-03-27 20:06 UTC
# Version

3.0.0

# Exception

## Message

Worker exited due to exception: @NotNull method org/elixir_lang/FindUsagesProvider.getType must not return null

## Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/FindUsagesProvider.getType must not return null
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:139)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:66)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:39)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:68)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$8.getInfo(CtrlMouseHandler.java:607)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:848)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2500(CtrlMouseHandler.java:786)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:831)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:159)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:223)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:45)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2016-03-27 21:08
Thanks for using the new error reporter.  Closing as duplicate of #277.  See https://github.com/KronicDeth/intellij-elixir/issues/277#issuecomment-202136586 for explanation and work-around.  Subscribe to that issue for updates.

**Closed by KronicDeth** 2016-03-27 21:08 UTC
Labels: bug, duplicate
