### ISSUE TITLE
Support colored output in run configurations

### ISSUE THREAD

**Issue by mkaput** [KronicDeth/intellij-elixir#800] opened 2017-08-18 09:05 UTC
For example Dialixir:

```
/home/mk/.asdf/installs/elixir/1.5.1-otp-19/bin/elixir /home/mk/.asdf/installs/elixir/1.5.1-otp-19/bin/mix dialyzer
Checking PLT...
[:asn1, :bimap, :certifi, :combine, :compiler, :crypto, :elixir, :gettext,
 :hackney, :httpoison, :idna, :kernel, :logger, :metrics, :mimerl, :public_key,
 :radiokit_api, :ssl, :ssl_verify_fun, :stdlib, :timex, :tzdata,
 :unicode_util_compat, :uuid, :xattr]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/* ... */',
 files_rec: ['/* ... */'],
 warnings: [:unknown]]
done in 0m2.91s
/* ... */
[33mdone (warnings were emitted)[0m
```

or ESpec:

```
/home/mk/.asdf/installs/elixir/1.5.1-otp-19/bin/elixir /home/mk/.asdf/installs/elixir/1.5.1-otp-19/bin/mix espec
Compiling 1 file (.ex)
/* ... */

[31mF[0m[31mF[0m[31mF[0m[31mF[0m[33m*[0m[33m*[0m[32m.[0m[32m.[0m[32m.[0m[33m*[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m

	1) /* ... */
	[36m/* ... */:37[0m
	[33mTemporarily skipped with: `xcontext`.[0m

/* ... */
```

**Comment by KronicDeth** [comment] 2017-08-19 01:24
Duplicate of #315.  Please go click Subscribe and 👍  on #315.

You might want to open a separate issue to adapt the ExUnit formatter for `espec` too.  The graphical ExUnit support has a lot of advantages and it's the ExUnit runner is the basis for the debugger too.

**Closed by KronicDeth** 2017-08-19 01:24 UTC
