### ISSUE TITLE
@doc autocompletion generates double @@

### ISSUE THREAD

**Issue by jorgheymans** [KronicDeth/intellij-elixir#294] opened 2016-04-11 18:30 UTC
Hi,

Doing @doc and accepting the suggested autocomplete results in a double @ being inserted:
```
@@doc """

"""
```

otherwise great plugin , thanks for not making me move to atom :-p

**Comment by NobbZ** [comment] 2016-04-11 20:50
I think this is related to IntelliJ, since similar thinks happen with
`#inc` -> `##include` in C and `-defi` -> `--define` in Erlang. Can't
access their issue tracker at the moment to look the problem up there
(would even know how to phrase the search)

Jorg Heymans <notifications@github.com> schrieb am Mo., 11. Apr. 2016 um
20:30 Uhr:

**Comment by KronicDeth** [comment] 2016-04-14 02:43
@jorgheymans have you tested if there's a different between selecting the completion with `TAB` or `ENTER`?  I know in Rubymine the completions replace the already typed text if the use `TAB`, but just insert the text if you hit `ENTER`.

**Comment by jorgheymans** [comment] 2016-04-23 13:05
oops missed your comment here sorry, TAB or ENTER makes no difference same behaviour

**Comment by marioosh** [comment] 2016-05-27 11:50
@jorgheymans :
Completion is triggered on `doc` not on `@doc` So, if you use second version `@` symbol is skipped and `doc` will be replaced by macro with additional `@` at the beginning.
Use just `doc<TAB>` and you'll get expected result.

**Comment by aphillipo** [comment] 2016-05-27 14:09
Would it not be better to add @doc as well as doc to the autocompletions with the first taking precedence, then both will work and all users will get expected behaviour. Just a thought.

**Comment by KronicDeth** [comment] 2016-08-13 03:49
@aphillipo it looks like the key parsers doesn't support starting with `@` for the prompt.  I haven't figure out why yet.   I can add `@doc`, but you end up having to type `@doc` and even then you're left with both `@doc` and `doc` with `doc` favored, so you need to hit down before tab to get `@doc`, which won't insert the extra `@`.  There is no precedence system for the templates:  the templates pass through a HashMap and then asks for its keySet, so the order is arbitrary and then the templates are shorted in the UI, which is a Lookup using a `new LookupArranger.DefaultArranger()`, so stuff all fixed by Open API and not extendable by the plugin.

**Comment by KronicDeth** [comment] 2016-08-13 03:50
@jorgheymans, @drathier what are your opinions on having to hit down to select `@doc` over the pre-existing `doc`.  Is it worth it?

**Comment by drathier** [comment] 2016-08-13 09:24
If it's less than 5-10 minutes of work, then yes. Otherwise, no. It's not too hard to relearn, and it really needs a fix higher up before being useful. It still saves a few keystrokes though if you accidentally type `@doc` instead of `doc`, and it doesn't hurt anyone typing `doc`.

**Closed** 2016-08-13 18:34 UTC
Labels: bug
