### ISSUE TITLE
Don't know how to find ancestorTypeSpec at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245) for ElixirMatchedQualifiedMultipleAliasesImpl

### ISSUE THREAD

**Issue by Mirk32** [KronicDeth/intellij-elixir#2504] opened 2022-02-10 14:57 UTC
# System

Plugin Version: 12.0.1
Application: RubyMine (2021.2)
Operating System: Mac OS X (11.6)

# Event

### Excerpt

```
payload. 
         {:ok, exclusion}
```

From: `/Users/michael.matrosov/DevProjects/medwing/placement-service-backend/apps/placement_service/lib/placement_service/matches/process_manager.ex:37`
To: `/Users/michael.matrosov/DevProjects/medwing/placement-service-backend/apps/placement_service/lib/placement_service/matches/process_manager.ex:38`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedQualifiedMultipleAliasesImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find ancestorTypeSpec
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeCallableReference(CallImpl.kt:122)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeReference(CallImpl.kt:77)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference$lambda-4(CallImpl.kt:149)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference(CallImpl.kt:148)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1164)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.getReference(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:95)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:92)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment] 2022-05-06 16:26
Duplicate of #2464

**Closed by KronicDeth** 2022-05-06 16:26 UTC
Labels: Kind:Bug
