### ISSUE TITLE
unable to get stub builder for org.intellij.plugins.markdown.lang.MarkdownFileType

### ISSUE THREAD

**Issue by Potrimpo** [KronicDeth/intellij-elixir#613] opened 2017-02-10 23:50 UTC
# Version

4.7.0

# Exception

## Message

unable to get stub builder for org.intellij.plugins.markdown.lang.MarkdownFileType@7017f8, path = /Users/lewis.knoxstreader/zCode/elixir/plugFun/deps/mime/README.md, stubBindingRoot = MarkdownFile, languages = [Markdown], filesTypes = [Markdown], files = [MarkdownFile], roots = []

## Stacktrace

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:81)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:333)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:684)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:672)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:359)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:325)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at org.elixir_lang.psi.scope.module.Variants.addProjectNameElementsTo(Variants.java:279)
	at org.elixir_lang.psi.scope.module.Variants.lookupElementList(Variants.java:51)
	at org.elixir_lang.reference.Module.getVariants(Module.java:106)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:292)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:164)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:97)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2017-02-12 22:47
Although my error reporter is reporting this bug, I can't do anything to fix that JetBrains forgot to add a stubbuilder for it's `MarkdownFileType`.

# Questions

1) Are you on the latest version of the JetBrains IDE you're using?
2) Have you filed the bug with JetBrains or searched their bug tracker for the bug?

**Comment by KronicDeth** [comment] 2017-02-12 22:50
It looks like the IDEA PHP Symfony 2 plugin had a similar issue (https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/630) and they [fixed it with a change to their stub filter](https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/bf07e880c3646965bbe032b5da6399817fd17733), so I can look into doing something similar.

**Comment by KronicDeth** [comment] 2017-02-23 04:36
Upon further review, the IDEA PHP Symfony 2 plugin uses a File-based index instead of a Stub-based index, so the file filter does not apply here.  I asked the OpenAPI forums (https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000093990-unable-to-get-stub-builder-for-org-intellij-plugins-markdown-lang-MarkdownFileType) if this is a reported bug with JetBrains IDEs themselves as was the case with JSON support.

**Comment by KronicDeth** [comment] 2017-02-24 05:05
@donnerpeter says (https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000093990/comments/115000124664) it is a bug in the indexing, but JetBrains doesn't know how to reproduce it.  @Potrimpo, you should file an official bug report with JetBrains with as much information as you can to help them reproduce the error.  Marking as wontfix on my end since JetBrains has to fix.

**Closed by KronicDeth** 2017-02-24 05:05 UTC
Labels: bug, wontfix
