### ISSUE TITLE
java.lang.NoSuchFieldError: Companion at org.elixir_lang.mix.project._import.Builder$commit$createModules$1.invoke(Builder.kt:110)

### ISSUE THREAD

**Issue by zerosum99** [KronicDeth/intellij-elixir#2983] opened 2023-01-02 13:19 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.2.1)
Operating System: Mac OS X (12.6)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoSuchFieldError: Companion
</summary>

```
java.lang.NoSuchFieldError: Companion
	at org.elixir_lang.mix.project._import.Builder$commit$createModules$1.invoke(Builder.kt:110)
	at org.elixir_lang.mix.project._import.Builder$commit$createModules$1.invoke(Builder.kt:107)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:76)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:107)
```

</details>

**Comment by KronicDeth** [comment] 2023-01-27 17:35
Duplicate of #2975

**Closed by KronicDeth** 2023-01-27 17:35 UTC
