### ISSUE TITLE
Links in stdout point to first file with that name, rather than following path

### ISSUE THREAD

**Issue by drathier** [KronicDeth/intellij-elixir#345] opened 2016-07-12 12:28 UTC
Links in stack traces etc. in stdout point to the first file with that filename, rather than following the whole path. 

e.g. `lib/a/compl.ex` and `lib/b/compl.ex` both open `lib/a/compl.ex` when clicked.

**Comment by KronicDeth** [comment] 2016-07-16 22:12
Duplicate of #229.  Please move any more information about your specific use case to that issue.

**Closed by KronicDeth** 2016-07-16 22:12 UTC
Labels: bug, duplicate
