### ISSUE TITLE
[auto-generated] Exception when opening Elixir's kernel/typespec_test.exs

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#413] opened 2016-09-06 08:01 UTC
# Version

4.3.0

# Exception

## Message

Cannot highlight types

### Excerpt

```
atom | String.t => term
```
 Line(s) 316-316

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:48)
org.elixir_lang.errorreport.Logger.error(Logger.java:31)
org.elixir_lang.annonator.ModuleAttribute.error(ModuleAttribute.java:145)
org.elixir_lang.annonator.ModuleAttribute.cannotHighlightTypes(ModuleAttribute.java:141)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:943)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:954)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:831)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:692)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:851)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:954)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:831)
org.elixir_lang.annonator.ModuleAttribute.highlightType(ModuleAttribute.java:342)
org.elixir_lang.annonator.ModuleAttribute.access$300(ModuleAttribute.java:37)
org.elixir_lang.annonator.ModuleAttribute$1.visitDeclaration(ModuleAttribute.java:101)
org.elixir_lang.annonator.ModuleAttribute$1.visitElement(ModuleAttribute.java:70)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:38)
org.elixir_lang.annonator.ModuleAttribute.annotate(ModuleAttribute.java:53)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:334)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:274)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:293)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:268)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by develop7** [comment] 2016-09-06 08:02
NB: this is a follow-up to #412, so it could be related

**Comment by develop7** [comment] 2016-09-06 08:04
Excerpt mentioned in report, must be https://github.com/elixir-lang/elixir/blob/v1.3.2/lib/elixir/test/elixir/kernel/typespec_test.exs#L317

**Comment by KronicDeth** [comment] 2016-09-07 02:27
I'm not sure this is a regression or not.  I'll have to check if I was testing the parsing of the `*_test.exs`.  Marking as plain bug for now.

**Comment by KronicDeth** [comment] 2016-09-08 02:31
This is actually a pretty interesting collision of map semantics and type semantics: `@type content :: %{atom | String.t => term}` is defining a type with `atom` or `String.t` keys with `term` values, but syntactically its `%{atom | String.t => term}` is trying to update the `String.t` key of a map, `atom`, with the value `term`.

**Comment by KronicDeth** [comment] 2016-09-08 02:42
It turns out it's a test for an invalid typespec, so now I can highlight even though the compiler doesn't like it :-P

```
test "@type with an invalid map notation" do
    assert_raise CompileError, ~r"invalid map specification", fn ->
      test_module do
        @type content :: %{atom | String.t => term}
      end
    end
  end
```
![screen shot 2016-09-07 at 9 41 10 pm](https://cloud.githubusercontent.com/assets/298259/18335269/d3b7b73a-7543-11e6-9d30-7a9ca79737ff.png)

**Closed** 2016-09-08 03:46 UTC
Labels: bug
