### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by jayber** [KronicDeth/intellij-elixir#2777] opened 2022-08-05 02:26 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Windows 10 (10.0)

# Event

### Element

```
end
```

From: `C:/Users/James/Exercism/elixir/secrets/lib/secrets.ex:3`

#### Context

```
defmodule Secrets do
  def secret_add(secret) do
    fn  end
  end

  def secret_subtract(secret) do
    # Please implement the secret_subtract/1 function
  end

```

From: `C:/Users/James/Exercism/elixir/secrets/lib/secrets.ex:0-8`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-12 12:40
Duplicate of #2774

**Closed by KronicDeth** 2022-08-12 12:40 UTC
