### ISSUE TITLE
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren at org.elixir_lang.formatter.Block.<init>(Block.java:272)

### ISSUE THREAD

**Issue by l-ray** [KronicDeth/intellij-elixir#3300] opened 2023-07-04 09:24 UTC
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Community Edition (2023.1.2)
Operating System: Linux (6.3.8-200.fc38.x86_64)

# Event

### Stacktrace

<details>

<summary>
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
</summary>

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:272)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:756)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1482)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1472)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1385)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1045)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1035)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1373)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1405)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1400)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:842)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:929)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:48)
	at com.intellij.formatting.InitialInfoBuilder.buildFrom(InitialInfoBuilder.java:137)
	at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:212)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:109)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:108)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:404)
```

</details>

**Comment by KronicDeth** [comment] 2023-07-08 04:11
Duplicate of #1075

**Closed by KronicDeth** 2023-07-08 04:11 UTC
