### ISSUE TITLE
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren at org.elixir_lang.formatter.Block.<init>(Block.java:272)

### ISSUE THREAD

**Issue by ferLunaDvz** [KronicDeth/intellij-elixir#2519] opened 2022-02-22 00:35 UTC
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.2)
Operating System: Mac OS X (12.2.1)

# Event

### Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:272)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:756)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1482)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1472)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1385)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1045)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1035)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1373)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1405)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:291)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1400)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:842)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:929)
```

**Comment by KronicDeth** [comment] 2023-07-08 04:10
Duplicate of #1075

**Closed by KronicDeth** 2023-07-08 04:10 UTC
Labels: Kind:Bug, Feature:Formatter
