### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.ElixirLanguage at org.elixir_lang.find_usages.handler.Factory.canFindUsages(Factory.kt:19)

### ISSUE THREAD

**Issue by jacobhallenborgprototyp** [KronicDeth/intellij-elixir#2238] opened 2021-11-29 15:40 UTC
# Version

11.13.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.ElixirLanguage
	at org.elixir_lang.find_usages.handler.Factory.canFindUsages(Factory.kt:19)
	at com.intellij.find.findUsages.FindUsagesManager.canFindUsages(FindUsagesManager.java:102)
	at com.intellij.find.impl.FindManagerImpl.canFindUsages(FindManagerImpl.java:902)
	at com.intellij.find.findUsages.DefaultUsageTargetProvider.getTargets(DefaultUsageTargetProvider.java:16)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:51)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:32)
	at com.intellij.ide.impl.dataRules.UsageTargetsRule.getData(UsageTargetsRule.java:13)
	at com.intellij.ide.impl.DataManagerImpl.getRulesData(DataManagerImpl.java:124)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:112)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:72)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:126)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:305)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:301)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:300)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$20(ActionUpdater.java:298)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment] 2021-12-05 18:23
I'm not sure how this is even possible since the FindUsages is from the plugin and it is saying it can't find the language for the plugin.

**Comment by KronicDeth** [comment] 2023-01-25 03:53
Duplicate of #2116

**Closed by KronicDeth** 2023-01-25 03:53 UTC
Labels: Kind:Bug
