### ISSUE TITLE
Do not know whether to inject Markdown in documentation at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:59)

### ISSUE THREAD

**Issue by json2008** [KronicDeth/intellij-elixir#3071] opened 2023-02-16 11:06 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.2)
Operating System: Mac OS X (13.2.1)

# Event

### Element

```
fals
```

From: `/Users/jswk/js/Github_Desktop/postgrex_wal/lib/postgrex_wal.ex:1`

#### Context

```
defmodule PostgrexWal do
  @moduledoc fals

  defmodule StreamBoundaryError do
    defexception [:message]
  end
end
```

From: `/Users/jswk/js/Github_Desktop/postgrex_wal/lib/postgrex_wal.ex:0-6`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirIdentifierImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Do not know whether to inject Markdown in documentation
</summary>

```
java.lang.Throwable: Do not know whether to inject Markdown in documentation
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:59)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2023-02-21 22:31
Duplicate of #2991

**Closed by KronicDeth** 2023-02-21 22:31 UTC
