### ISSUE TITLE
[auto-generated] @NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null

### ISSUE THREAD

**Issue by povilas** [KronicDeth/intellij-elixir#297] opened 2016-04-13 11:48 UTC
# Version

3.0.1

# Exception

## Message

@NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null

## Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/FindUsagesProvider.getDescriptiveName must not return null
	at org.elixir_lang.FindUsagesProvider.getDescriptiveName(FindUsagesProvider.java:177)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:53)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:141)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:113)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:86)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.createRenameDialog(RenamePsiElementProcessor.java:55)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:177)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:169)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:119)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:79)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:134)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by KronicDeth** [comment] 2016-04-14 02:44
Did you try to use Refactor > Rename?

**Comment by povilas** [comment] 2016-04-14 11:26
yes

**Comment by KronicDeth** [comment] 2016-04-14 22:22
Closing as duplicate of #296.  Add any new comments to that.

**Closed by KronicDeth** 2016-04-14 22:22 UTC
Labels: bug, duplicate
