### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.intellij.lang.ASTNode.getStartOffset()" because "whiteSpace" is null at org.elixir_lang.local_quick_fix.RemoveSpaceInFrontOfNoParenthesesStrict.invoke(RemoveSpaceInFrontOfNoParenthesesStrict.java:51)

### ISSUE THREAD

**Issue by william-intelligencebank** [KronicDeth/intellij-elixir#3109] opened 2023-03-10 06:29 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3.3 RC)
Operating System: Mac OS X (13.2.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NullPointerException: Cannot invoke "com.intellij.lang.ASTNode.getStartOffset()" because "whiteSpace" is null
</summary>

```
java.lang.NullPointerException: Cannot invoke "com.intellij.lang.ASTNode.getStartOffset()" because "whiteSpace" is null
	at org.elixir_lang.local_quick_fix.RemoveSpaceInFrontOfNoParenthesesStrict.invoke(RemoveSpaceInFrontOfNoParenthesesStrict.java:51)
```

</details>

**Comment by KronicDeth** [comment] 2023-04-07 20:29
Duplicate of #3107

**Closed by KronicDeth** 2023-04-07 20:29 UTC
