### ISSUE TITLE
NullPointerException getting Call.finalArguments() at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:146)

### ISSUE THREAD

**Issue by donaldww** [KronicDeth/intellij-elixir#3058] opened 2023-02-09 23:37 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.2)
Operating System: Mac OS X (13.0.1)

# Event

### Element

```
not
```

From: `/Users/donaldwilson/Developer/code/elixir/yacht/lib/yacht.ex:65`

#### Context

```

  def score(:full_house, dice) do
    f = Enum.frequencies(dice)
    c = Enum.count(f)

    case Enum.count(f) == 2 and not  do
      true ->
        k = Map.keys(f)
        Map.values(f)
        |> Enum.max()
      _ -> 0
```

From: `/Users/donaldwilson/Developer/code/elixir/yacht/lib/yacht.ex:60-70`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedUnaryOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: NullPointerException getting Call.finalArguments()
</summary>

```
java.lang.Throwable: NullPointerException getting Call.finalArguments()
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.impl.call.CallImplKt.finalArguments(CallImpl.kt:146)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArguments(CallImpl.kt:172)
	at org.elixir_lang.psi.impl.call.CallImplKt.keywordArgument(CallImpl.kt:163)
	at org.elixir_lang.psi.impl.call.CallImpl.hasDoBlockOrKeyword(CallImpl.kt:412)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.hasDoBlockOrKeyword(ElixirPsiImplUtil.java:1098)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:237)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:410)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:63)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:349)
	at org.elixir_lang.psi.scope.Variable.executeNonDeclaringScopeInfix(Variable.kt:424)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:41)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:212)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.kt:65)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:171)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveInScope(MultiResolve.kt:133)
	at org.elixir_lang.psi.scope.variable.MultiResolve$Companion.resolveResultList(MultiResolve.kt:116)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:122)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
```

</details>

**Comment by KronicDeth** [comment] 2023-02-21 23:58
Duplicate of #3059

**Closed by KronicDeth** 2023-02-21 23:58 UTC
Labels: Kind:Bug
