### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by rafaelfrancisco-dev** [KronicDeth/intellij-elixir#2803] opened 2022-08-22 13:45 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (13.0)

# Event

### Element

```
end
```

From: `/Users/rafaelfrancisco/Desktop/qual/lib/qual/business/requester.ex:17`

#### Context

```
      response.body
    else
      raise "Error fetching stations"
    end
  end
end

```

From: `/Users/rafaelfrancisco/Desktop/qual/lib/qual/business/requester.ex:12-18`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-22 16:07
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-08-22 16:07 UTC
