### ISSUE TITLE
java.lang.NullPointerException at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)

### ISSUE THREAD

**Issue by Timtonix** [KronicDeth/intellij-elixir#2608] opened 2022-04-22 13:26 UTC
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Linux (5.15.32-1-MANJARO)

# Event

## Message

Unhandled exception in [StandaloneCoroutine{Cancelling}@2dd9cb3b, EdtCoroutineDispatcher@71c96f96]

### Stacktrace

```
java.lang.NullPointerException
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

**Comment by KronicDeth** [comment] 2022-05-07 20:06
Duplicate of #2564

**Closed by KronicDeth** 2022-05-07 20:06 UTC
