### ISSUE TITLE
Build button does not do anything

### ISSUE THREAD

**Issue by Macfly** [KronicDeth/intellij-elixir#920] opened 2017-11-25 21:47 UTC
## Versions
windows 10

## Elixir
1.5.2

## IntelliJ
IntelliJ IDEA 2017.2.6
Build #IC-172.4574.11, built on November 13, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

## intellij-elixir
6.5.1

# Problem
when I click on build it says "all files are up to date" but it does not compile.
However when I run a test or debug one, it compiles perfectly.
Is there anything special to do to activate this feature?

I did the what it is [written here](https://github.com/KronicDeth/intellij-elixir#buildingcompiling) but I don't have th option to compile individual file.

**Comment by KronicDeth** [comment] 2017-11-29 20:27
The build integration is an older feature.  It probably needs to be updated to work correctly.

**Comment by KronicDeth** [comment] 2017-12-01 03:23
Treating as duplicate of #918

**Closed** 2017-12-01 03:23 UTC
Labels: bug, duplicate
