### ISSUE TITLE
Don't know how to find variable use scope at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:573)

### ISSUE THREAD

**Issue by hcpak** [KronicDeth/intellij-elixir#1924] opened 2021-03-30 05:38 UTC
# Version

11.10.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
java.lang.Throwable: Don't know how to find variable use scope
	at org.elixir_lang.errorreport.Logger.error(Logger.java:42)
	at org.elixir_lang.errorreport.Logger.error(Logger.java:28)
	at org.elixir_lang.reference.Callable$Companion.error(Callable.kt:419)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:573)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:485)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:566)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:523)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:564)
	at org.elixir_lang.reference.Callable$Companion.variableUseScope(Callable.kt:416)
	at org.elixir_lang.psi.impl.declarations.UseScopeImpl.get(UseScopeImpl.kt:119)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getUseScope(ElixirPsiImplUtil.java:957)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.getUseScope(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:110)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:71)
	at com.intellij.psi.search.searches.ReferencesSearch$SearchParameters.getEffectiveSearchScope(ReferencesSearch.java:111)
	at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:54)
	at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:19)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:26)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:35)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:30)
	at com.intellij.find.findUsages.FindUsagesHandlerBase.findReferencesToHighlight(FindUsagesHandlerBase.java:123)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getReferences(IdentifierHighlighterPass.java:302)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:272)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$2(IdentifierHighlighterPass.java:252)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:251)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:227)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by KronicDeth** [comment] 2021-10-21 04:14
Duplicate of #1905

**Closed by KronicDeth** 2021-10-21 04:14 UTC
Labels: Kind:Bug
