### ISSUE TITLE
Erroneous syntax highlighting inside comments

### ISSUE THREAD

**Issue by ArtemGordinsky** [KronicDeth/intellij-elixir#641] opened 2017-03-12 15:24 UTC
<img width="601" alt="screen shot 2017-03-12 at 16 15 27" src="https://cloud.githubusercontent.com/assets/1506254/23832990/9435b1dc-073f-11e7-8c5b-cb73ab6725de.png">
Taken from `deps/ecto/lib/ecto/repo.ex`

Could this be a misconfiguration on my part? Looks kinda weird.

Plugin version: 4.7.0
WebStorm 2016.3.3
Color scheme: Darcula

**Comment by KronicDeth** [comment] 2017-03-12 20:16
This is a duplicate of a lot of other bugs (#619, #625, #626) and was fixed by #627, which will be in the next release.

**Closed** 2017-03-12 20:17 UTC
Labels: bug, duplicate

**Comment by ArtemGordinsky** [comment] 2017-03-12 20:57
Sorry, wasn't able to find those issues before creating mine.
Thanks for the quick response! Can't wait for v5 😃
