### ISSUE TITLE
InvalidMirrorException for rebar3_hex_config.beam

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#672] opened 2017-04-21 09:10 UTC
# Version

5.0.0

# Exception

## Message
```
file:///home/josh/dev/foobar/deps/fs/_build/default/plugins/rebar3_hex/ebin/rebar3_hex_config.beam: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@27b6b6bd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7a84bb29, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f7cbb26, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@753f903f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@672ec37b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@38ac6144, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@42f358fc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4bc486f5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5ae0b1ed, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@19d4db4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5971c1c3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@366d0736, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@69ddb7cf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2c6b7ad, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@55ee11ef]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
```

## Stacktrace

```
org.elixir_lang.beam.psi.impl.ModuleElementImpl$InvalidMirrorException: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@27b6b6bd, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7a84bb29, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1f7cbb26, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@753f903f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@672ec37b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@38ac6144, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@42f358fc, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@4bc486f5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5ae0b1ed, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@19d4db4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5971c1c3, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@366d0736, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@69ddb7cf, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2c6b7ad, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@55ee11ef]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:43)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.java:76)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.java:649)
	at org.elixir_lang.beam.psi.BeamFileImpl$1.run(BeamFileImpl.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:204)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.java:620)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:125)
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.java:110)
	at org.elixir_lang.navigation.GotoSymbolContributor.getItemsByName(GotoSymbolContributor.java:80)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.a(ContributorsBasedGotoByModel.java:209)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by joshuataylor** [comment] 2017-04-21 09:11
Randomly happened, not sure what triggered it.

**Comment by KronicDeth** [comment] 2017-04-22 01:53
The decompiler decompiles on-demand either for the stub index during the indexing OR when a reference is being resolved.  Since some of the annotators determine the text attributes based on resolving references, that could also trigger decompilation.

The important bit is that the problem is with `file:///home/josh/dev/foobar/deps/fs/_build/default/plugins/rebar3_hex/ebin/rebar3_hex_config.beam`, so if you open `rebar3_hex_config.beam`, there is probably invalid code be generated by the decompiler, so that when the parser parses the decompiled code it leads to this error.  If you could paste in decompiled `rebar3_hex_config.beam` that would help.

**Comment by KronicDeth** [comment] 2017-07-26 02:00
I couldn't figure out why I had `fs` in my `mix.lock`, but not installed as a dep anymore, but the dependency chain is `phoenix_live_reload` -> `fs` -> `reba3_hex`, but we use Ember frontends, so I removed `phoenix_live_reload`.  I'll make a new phoenix project, which should be able to trigger the bug.

**Comment by KronicDeth** [comment] 2017-07-26 02:19
`rebar3_hex_config.erl` has a function called `do`

![screen shot 2017-07-25 at 9 17 39 pm](https://user-images.githubusercontent.com/298259/28601603-cba5b7bc-717e-11e7-9d8d-703cd4a5cc7b.png)

which is a perfectly valid identifier in Erlang, but in Elixir of course `do` is one of the few keywords

![screen shot 2017-07-25 at 9 17 30 pm](https://user-images.githubusercontent.com/298259/28601616-dea06c72-717e-11e7-94e7-cf95e2b00e04.png)

**Closed** 2017-07-26 03:00 UTC
Labels: bug
