### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by sandergol** [KronicDeth/intellij-elixir#2830] opened 2022-09-01 09:43 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (11.6.8)

# Event

### Element

```
end
```

From: `/Users/sandergol/Develop/gitlab/private/sandergol/sandergol/my-hints/Erlang/Elixir/test_task/1_task.ex:9`

#### Context

```
      //true
    else
      false
    end
  end
end
```

From: `/Users/sandergol/Develop/gitlab/private/sandergol/sandergol/my-hints/Erlang/Elixir/test_task/1_task.ex:4-9`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

### `/Users/sandergol/Develop/gitlab/private/sandergol/sandergol/my-hints/Erlang/Elixir/test_task/1_task.ex`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment] 2022-09-10 15:00
Duplicate of #2774

**Closed by KronicDeth** 2022-09-10 15:00 UTC
