### ISSUE TITLE
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'jose' (disposed) at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:119)

### ISSUE THREAD

**Issue by kpy3** [KronicDeth/intellij-elixir#2764] opened 2022-07-28 08:10 UTC
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Community Edition (2022.1.4)
Operating System: Mac OS X (12.5)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'jose' (disposed)
</summary>

```
java.lang.RuntimeException: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'jose' (disposed)
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:503)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:523)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:70)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:65)
	at org.elixir_lang.mix.Watcher$contentsChanged$1$1.run(Watcher.kt:52)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'jose' (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:183)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:548)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
	at org.elixir_lang.mix.Watcher.syncLibraries$lambda-9$lambda-8(Watcher.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
	at org.elixir_lang.mix.Watcher.syncLibraries$lambda-9(Watcher.kt:71)
```

</details>

**Comment by KronicDeth** [comment] 2023-03-18 03:44
Duplicate of #3002

**Closed by KronicDeth** 2023-03-18 03:44 UTC
Labels: Kind:Bug
