### ISSUE TITLE
Do not known whether to inject Markdown in documentation key type at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:49)

### ISSUE THREAD

**Issue by bbkgh** [KronicDeth/intellij-elixir#3122] opened 2023-03-16 10:18 UTC
# System

Plugin Version: 14.0.0
Application: PyCharm Professional Edition (2022.3.2)
Operating System: Linux (5.15.0-67-generic)

# Event

### Element

```
type: :component
```

From: `/home/hhh/PycharmProjects/phoenix-test/discuss/deps/phoenix_live_view/lib/phoenix_component.ex:2636`

#### Context

```

  ```heex
  <.live_file_input upload={@uploads.avatar} />
  ```
  """
  @doc type: :component
  def live_file_input(assigns)

  def live_file_input(%Phoenix.LiveView.UploadConfig{} = conf) do
    IO.warn(
      "live_file_input(upload) is deprecated, please use <.live_file_input upload={upload} /> instead"
```

From: `/home/hhh/PycharmProjects/phoenix-test/discuss/deps/phoenix_live_view/lib/phoenix_component.ex:2631-2641`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirNoParenthesesKeywordPairImpl
```


## Exception


### Stacktrace


<details>

<summary>
java.lang.Throwable: Do not known whether to inject Markdown in documentation key type
</summary>

```
java.lang.Throwable: Do not known whether to inject Markdown in documentation key type
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:49)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2023-04-07 20:37
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/3017

**Closed by KronicDeth** 2023-04-07 20:37 UTC
