### ISSUE TITLE
Cannot find enclosing Modular, randomly

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#350] opened 2016-07-17 09:08 UTC
# Version

4.0.0

# Exception

## Message

Cannot find enclosing Modular

### Excerpt

```
def index(conn, _params) do

```
 Line(s) 5-6

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:48)
org.elixir_lang.errorreport.Logger.error(Logger.java:31)
org.elixir_lang.navigation.GotoSymbolContributor.error(GotoSymbolContributor.java:226)
org.elixir_lang.navigation.GotoSymbolContributor.getItemsByName(GotoSymbolContributor.java:96)
com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.a(ContributorsBasedGotoByModel.java:212)
com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:123)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:60)
com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.getElementsByName(ContributorsBasedGotoByModel.java:244)
com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:146)
com.intellij.ide.actions.SearchEverywhereAction$CalcThread.a(SearchEverywhereAction.java:1658)
com.intellij.ide.actions.SearchEverywhereAction$CalcThread.j(SearchEverywhereAction.java:1554)
com.intellij.ide.actions.SearchEverywhereAction$CalcThread.d(SearchEverywhereAction.java:1370)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
com.intellij.ide.actions.SearchEverywhereAction$CalcThread.a(SearchEverywhereAction.java:1400)
com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1370)
com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment] 2016-08-06 16:45
Can you post the controller as a gist or does it contain too much proprietary information?  I have a feeling the failure is random because the indexer is failing in different spots for other files.

**Comment by joshuataylor** [comment] 2016-08-06 16:58
This happens when generating a basic html (or json) controller with gen, with phoenix.

**Comment by KronicDeth** [comment] 2016-08-06 17:12
The next time it happens, in addition to posting the error with the button, check if there are any files in the Attachment tab and post those too or in a gist.  That may help me isolate a reproduction case.

**Comment by KronicDeth** [comment] 2016-08-13 03:02
I can't reproduce with `master` and Phoenix 1.2.  I'm marking as such for now, but comment with more exact steps if you can trigger it again: exact version of the plugin, Phoenix, etc.

**Closed by KronicDeth** 2016-08-13 03:02 UTC
Labels: bug, can't reproduce
