### ISSUE TITLE
Error Setting Elixir SDK

### ISSUE THREAD

**Issue by jjmr** [KronicDeth/intellij-elixir#2494] opened 2022-02-02 15:19 UTC
# System

Plugin Version: 12.2.0
Application: RubyMine (2021.3.1)
Operating System: Mac OS X (12.1)

# What I was doing

Setting Elixir SDK in preferences

# Event

### Stacktrace

```
java.lang.Throwable: Do not use module level message bus
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:196)
	at org.elixir_lang.facet.configurable.Project.setFacetSdk(Project.kt:61)
	at org.elixir_lang.facet.configurable.Project.access$setFacetSdk(Project.kt:16)
	at org.elixir_lang.facet.configurable.Project$createModuleConfigurable$1.applySdk(Project.kt:39)
	at org.elixir_lang.facet.Configurable.apply(Configurable.kt:33)
```

**Comment by KronicDeth** [comment] 2022-02-02 15:27
Duplicate of #2063

**Closed by KronicDeth** 2022-02-02 15:27 UTC
