### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)

### ISSUE THREAD

**Issue by renatoao** [KronicDeth/intellij-elixir#2756] opened 2022-07-22 23:05 UTC
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Community Edition (2022.1.4)
Operating System: Linux (5.15.0-41-generic)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at /usr/lib/elixir` is missing Erlang SDK
	at org.elixir_lang.sdk.erlang_dependent.SdkAdditionalData.ensureErlangSdk(SdkAdditionalData.java:97)
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:34)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.commandLine(MixFormatExternalFormatProcessor.kt:89)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.format(MixFormatExternalFormatProcessor.kt:84)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$format(MixFormatExternalFormatProcessor.kt:69)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda-7$lambda-6(MixFormatExternalFormatProcessor.kt:46)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-01 14:37
This should be written to the log and perhaps a notification at most.   It should not be an error reportable error.

**Comment by KronicDeth** [comment] 2023-03-18 03:56
Duplicate of #3001

**Closed by KronicDeth** 2023-03-18 03:56 UTC
Labels: Kind:Bug
