### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by stocks29** [KronicDeth/intellij-elixir#104] opened 2015-03-03 23:21 UTC
I may be doing something wrong here, but when I create a new elixir file, the editor immediately complains about it.

![screen shot 2015-03-03 at 6 19 23 pm](https://cloud.githubusercontent.com/assets/188319/6474797/01b8bf5c-c1d2-11e4-8a96-322e68287af9.png)

Am I doing something wrong here?

**Comment by KronicDeth** [comment] 2015-03-04 00:51
No, you're not doing anything wrong, the parser just isn't finished,so it's marking anything it can't parse as an error. I'm counting this a duplicate of #6.

**Closed by KronicDeth** 2015-03-04 00:51 UTC
Labels: bug, duplicate
