### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by pfazzi** [KronicDeth/intellij-elixir#2797] opened 2022-08-17 10:22 UTC
# System

Plugin Version: 13.2.0
Application: PhpStorm (2022.2)
Operating System: Mac OS X (12.5)

# Event

### Element

```
,
```

From: `/Users/patrickfazzi/Prima/ermes/lib/ermes_web/controllers/heml_controller.ex:12`

#### Context

```
  alias Ermes.Domain.Mail.Sender
  alias Ermes.Utils.Payload

  @save_events [
    %{
      slug: "attachment_required",
      event: "save_document_queue_attachments_required",
      path: "save"
    },
    %{slug: "autosave_flusso", event: "save_contract_created_autosave", path: "save"},
    %{slug: "docs_integration", event: "save_documents_integration", path: "save"},
```

From: `/Users/patrickfazzi/Prima/ermes/lib/ermes_web/controllers/heml_controller.ex:7-17`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-17 12:02
Duplicate of #2774

**Closed by KronicDeth** 2022-08-17 12:02 UTC
