### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by julianmoors** [KronicDeth/intellij-elixir#2889] opened 2022-10-07 14:14 UTC
# System

Plugin Version: 13.2.0
Application: RubyMine (2022.2.2)
Operating System: Mac OS X (12.6)

# Event

### Element

```

```

From: `/Users/julian/Documents/Projects/Websites/Elixir/Mastery/lib/mastery/core/template.ex:0`

#### Context

```
defmodule Mastery.
```

From: `/Users/julian/Documents/Projects/Websites/Elixir/Mastery/lib/mastery/core/template.ex:0`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-07 17:10
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-10-07 17:10 UTC
