### ISSUE TITLE
Tried to "reformat code" (auto indent). Error happens reproducible. IntelliJ/Idea is installed fresh (absolutely no changes in fonfig) and elixir plugin also.

### ISSUE THREAD

**Issue by UweKrause** [KronicDeth/intellij-elixir#3310] opened 2023-07-08 15:58 UTC
# System

Plugin Version: 15.0.1
Application: IntelliJ IDEA Ultimate Edition (2023.1.1)
Operating System: Linux (6.1.38-1-lts)

# What I was doing

Tried to "reformat code" (auto indent). Error happens reproducible. IntelliJ/Idea is installed fresh (absolutely no changes in fonfig) and elixir plugin also.

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
</summary>

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 125,4,main] 819992878 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1629170035
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:219)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:213)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.workingDirectory(MixFormatExternalFormatProcessor.kt:77)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor$Companion.access$workingDirectory(MixFormatExternalFormatProcessor.kt:70)
	at org.elixir_lang.formatter.MixFormatExternalFormatProcessor.format$lambda$7$lambda$6(MixFormatExternalFormatProcessor.kt:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
```

</details>

**Comment by KronicDeth** [comment] 2023-07-09 00:30
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/3189

**Comment by KronicDeth** [comment] 2023-07-09 00:31
This is fixed in 15.1.0.  Upgrade to get the fix.

**Closed by KronicDeth** 2023-07-09 00:30 UTC

**Comment by UweKrause** [comment] 2023-07-09 11:40
Great to hear, thanks a lot!
Overall, thanks a lot for developing the plugin. Beside the plugin itself, I am impressed by that HUGE readme, all with pictures and everything!

15.1.0. is not jet available at the jetbrains marketplace. Since you released it just yesterday, I guess all I have to do is just a bit of waiting?

**Comment by KronicDeth** [comment] 2023-07-09 12:00
Yeah, there's a bit of waiting while JetBrains reviews the upload.  If you want to install it now you can use the tarball from the GitHub release, which is the same as uploaded to JetBrains Marketplace.

**Comment by UweKrause** [comment] 2023-07-09 12:48
Ahh, I don't think that is necessary. Thanks again and feel free to close :)
