### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by jveiga** [KronicDeth/intellij-elixir#996] opened 2018-01-15 10:30 UTC
# Version

7.2.1

# Exception

## Message

one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;

## Stacktrace

```
java.lang.NoSuchMethodError: one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;
	at org.elixir_lang.file.LevelPropertyPusher.initExtra(LevelPropertyPusher.java:164)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.initializeProperties(PushedFilePropertiesUpdaterImpl.java:132)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.lambda$new$1(FileBasedIndexProjectHandler.java:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:352)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runStartupActivities$0(StartupManagerImpl.java:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivities(StartupManagerImpl.java:119)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$openProject$7(ProjectManagerImpl.java:360)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:383)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:446)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:437)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Exception happened on opening a Python project, so feel free to close this if it doesn't make sense :)

**Comment by jveiga** [comment] 2018-01-15 10:32
seems similar to https://github.com/KronicDeth/intellij-elixir/issues/994

**Comment by KronicDeth** [comment] 2018-02-05 02:24
Duplicate of #992.  Subscribe to that issue.

**Closed by KronicDeth** 2018-02-05 02:24 UTC
Labels: Closed:Duplicate, Kind:Bug
