### ISSUE TITLE
Access is allowed from event dispatch thread only for elixir_documentation.Panel editor

### ISSUE THREAD

**Issue by aby2503** [KronicDeth/intellij-elixir#1057] opened 2018-03-19 09:56 UTC
# Version

7.4.0

# Exception

## Message

Access is allowed from event dispatch thread only.

## Stacktrace

```
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@32c153a3 Current thread: Thread[ApplicationImpl pooled thread 4,4,Idea Thread Group] 1180667927 SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.2.7#IU-172.4574.19 IDEA, eap:false, os:Linux 4.13.0-36-generic, java-version:JetBrains s.r.o 1.8.0_152-release-915-b12,6,main] 813161585

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:520)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1104)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1093)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3029)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:334)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:220)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:195)
	at org.elixir_lang.beam.chunk.elixir_documentation.Panel.<init>(Panel.kt:23)
	at org.elixir_lang.beam.chunk.elixir_documentation.Splitter.<init>(Splitter.kt:13)
	at org.elixir_lang.beam.chunk.elixir_documentation.NamespaceKt.component(namespace.kt:11)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:83)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:38)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:88)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2018-03-21 22:05
Duplicate of #1039

**Closed by KronicDeth** 2018-03-21 22:05 UTC
Labels: Kind:Bug
