### ISSUE TITLE
Support colors in run configurations

### ISSUE THREAD

**Issue by kwando** [KronicDeth/intellij-elixir#875] opened 2017-10-25 12:46 UTC
It would be nice if mix tasks runned through a "mix run configuration" showed colors in the "console window".
The elixir Logger emits colorized messages when run in the "terminal" panel but not when running through a run configuration.

**Comment by KronicDeth** [comment] 2017-10-25 13:10
Duplicate of #315.  Resolved in #863.  Wait for next release.

**Closed by KronicDeth** 2017-10-25 13:10 UTC

**Comment by kwando** [comment] 2017-10-25 13:22
Whoops, sorry for the noise. I missed that issue while glancing through the list.

**Comment by KronicDeth** [comment] 2017-10-25 13:26
Not surprising, the issue title and comments don't contain "color" in them since it's talking directly about how colors are implemented: ANSI escape codes.  You weren't likely to know that unless you do a lot of terminal programming.
