### ISSUE TITLE
java.util.NoSuchElementException at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:142)

### ISSUE THREAD

**Issue by Maartyl** [KronicDeth/intellij-elixir#2956] opened 2022-12-18 19:44 UTC
#### System
Plugin Version: 14.0.0
Application: IntelliJ IDEA Community Edition (2022.3)
Operating System: Windows 10 (10.0)

#### Event
The error pops up on opening any Elixir file.

<details>

<summary>
java.util.NoSuchElementException
</summary>

```
java.util.NoSuchElementException
	at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:142)
	at org.elixir_lang.reference.Resolver.filterUnderSameModule(Resolver.kt:61)
	at org.elixir_lang.reference.Resolver.preferUnderSameModule(Resolver.kt:40)
	at org.elixir_lang.reference.Resolver.preferElementUnderSameModule(Resolver.kt:32)
	at org.elixir_lang.reference.Resolver.preferred(Resolver.kt:16)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:74)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:95)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:83)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:187)
	at org.elixir_lang.psi.Use.modulars(Use.kt:84)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:35)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:182)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:44)
	at org.elixir_lang.psi.scope.CallDefinitionClause$execute$4.invoke(CallDefinitionClause.kt:182)
	at org.elixir_lang.psi.scope.CallDefinitionClause$execute$4.invoke(CallDefinitionClause.kt:182)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:34)
	at org.elixir_lang.psi.QuoteMacro.treeWalkUp(QuoteMacro.kt:18)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:59)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:182)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:167)
	at org.elixir_lang.psi.scope.CallDefinitionClause.execute(CallDefinitionClause.kt:44)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults(MultiResolve.kt:255)
	at org.elixir_lang.psi.scope.call_definition_clause.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:242)
	at org.elixir_lang.reference.resolver.Callable.resolveUnqualified(Callable.kt:132)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:103)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)
```

</details>

**Comment by KronicDeth** [comment] 2023-01-27 16:05
Duplicate of #2960 since it has more context

**Comment by KronicDeth** [comment] 2023-02-28 20:13
Line 142 does not exist in https://github.com/KronicDeth/intellij-elixir/blob/v14.0.0/src/org/elixir_lang/reference/Resolver.kt, but `moduleForSourceOrLibrary` is 

https://github.com/KronicDeth/intellij-elixir/blob/965b94b3df226f4323d6bde46bf03838b9b6c919/src/org/elixir_lang/reference/Resolver.kt#L69-L88

**Closed** 2023-02-28 20:30 UTC
Labels: Kind:Bug
