### ISSUE TITLE
Edge could not be stripped from explanation line

### ISSUE THREAD

**Issue by mario-mazo** [KronicDeth/intellij-elixir#1656] opened 2020-02-07 21:29 UTC
# Exception
Hello

after updating the plugin to 11.5.0 and elixir to 1.10, the whole thing keeps crashing

## Message

*** exception class was changed or removed

## Stacktrace

```
Edge could not be stripped from explanation line

`[0m[34m┃ [34m[2m   →[0m  Priority: normal [0m`


org.elixir_lang.credo.Annotator.stripEdge(Annotator.java:258)
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
org.elixir_lang.credo.Annotator.explanationToToolTip(Annotator.java:406)
org.elixir_lang.credo.Annotator.lambda$apply$2(Annotator.java:382)
java.base/java.util.Optional.ifPresent(Optional.java:183)
org.elixir_lang.credo.Annotator.apply(Annotator.java:381)
org.elixir_lang.credo.Annotator.apply(Annotator.java:49)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.lambda$checkFileWithExternalAnnotator$1(ExternalAnnotatorInspectionVisitor.java:71)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.checkFileWithExternalAnnotator(ExternalAnnotatorInspectionVisitor.java:69)
org.elixir_lang.credo.inspection_tool.Local.checkFile(Local.kt:28)
com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)
com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:77)
com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:64)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:306)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$3(LocalInspectionsPass.java:274)
com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:154)
com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:146)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$4(LocalInspectionsPass.java:271)
com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:271)
com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by KronicDeth** [comment] 2020-02-07 22:05
This is an error from the credo checker.  I'm not sure why updating would make the output of credo include the ANSI escape codes when earlier versions didn't.

For now, as a work-around, you should turn off credo integration:

1. Preference
2. Click Editor > Inspections (NOT the nested Editor > Inspections > Credo menu
3. Make sure Elixir > Credo inspection is UNchecked

   ![Screen Shot 2020-02-07 at 4 04 26 PM](https://user-images.githubusercontent.com/298259/74069392-b3126900-49c3-11ea-9b27-c544ad14926f.png)

**Comment by KronicDeth** [comment] 2022-05-20 15:25
Duplicate of #954

**Closed by KronicDeth** 2022-05-20 15:25 UTC
Labels: Kind:Bug, Feature:Credo
