### ISSUE TITLE
Allow credo annotator to be disabled when it causes CPU spikes

### ISSUE THREAD

**Issue by dKrishtal** [KronicDeth/intellij-elixir#949] opened 2017-12-13 12:34 UTC
Constantly loads the processor beam.smp -> erl_child_setup. Even when reading the code, in phpstorm all ok.

MacBook Pro 2017
MacOs Sierra 10.12.6
Intellij IDEA 2017.3 Ultimate

**Comment by KronicDeth** [comment] 2017-12-13 13:22
@dKrishtal there aren't a lot of reasons for the IDE to start `beam.smp`.  The plugin doesn't use alchemist-server or the Elixir Language Server, so there's no need to run `beam.smp` in the background continuously, there are 3 

1. Run Configurations
  1. Mix Task
  2. Mix ExUnit Task
2. `mix credo` external annotator

Since you say you're just reading code, I'm going to assume it's (2) because the external annotator are only run on open editor tabs.

## Questions

1. Do you have `credo` installed in the `mix.exs` project?
  * If yes, then it's probably `mix credo` spiking the CPU.
  * If no, :man_shrugging:
2. Can you get the full arguments to `beam.smp`?  In a separate terminal, run `ps -eaf | grep beam.smp` and report the full command line.   If it contains `mix credo`, then we know it is that.
3. If it is `mix credo`, when you run `mix credo` in your project directory in the terminal, does the CPU also spike?
  * If yes, then there's not much I can do besides adding an option to turn off the `mix credo` external annotator running automatically.
  * If no, :man_shrugging:

**Comment by KronicDeth** [comment] 2017-12-13 13:23
This may be a dupe of #909

**Comment by dKrishtal** [comment] 2017-12-13 13:39
@KronicDeth Yes, this is really a credo!

beam.smp ..... -noshell -s elixir start_cli -extra /usr/local/Cellar/elixir/1.5.2/bin/mix credo lib/....ex:1:11

**Comment by KronicDeth** [comment] 2017-12-13 13:41
@dKrishtal are you on the latest version of `credo`?  Run `mix hex.outdated`.  There was a change awhile ago in `credo` that made `credo` much faster and you may be before that.  If you're not then, we'll have to look elsewhere.

**Comment by dKrishtal** [comment] 2017-12-13 13:45
@KronicDeth credo 0.8.10 this latest version..

**Comment by KronicDeth** [comment] 2017-12-13 13:51
Ok, yeah, so the only option, barring some advice from @rrrene about a less CPU intensive way to run `credo`, is for me to add an option to allow users to disable the `credo` annotator as a bug fix for this.  Separately, as a new feature, I can figure out how to run it as a batch annotator instead.

**Comment by dKrishtal** [comment] 2017-12-13 13:59
@KronicDeth Thank! when about the expected bugfix?

**Comment by KronicDeth** [comment] 2017-12-13 14:06
I've been doing about one release a week recently, so 1-2 weeks at most probably.  Assuming some other thing doesn't take priority.

**Comment by KronicDeth** [comment] 2017-12-13 14:15
Looks like there's an existing system to pair it with a batch inspection and through that pairing to disable the annotator:

```java
 /**
   * Return inspection which should run in batch mode.
   * When inspection with short name is disabled, then annotator won't run in the editor via {@link com.intellij.codeInsight.daemon.impl.ExternalToolPass}.
   * Implementing {@link com.intellij.codeInspection.ex.ExternalAnnotatorBatchInspection}
   * and extending {@link com.intellij.codeInspection.LocalInspectionTool} or {@link GlobalSimpleInspectionTool} would
   * provide implementation for a batch tool which would run without read action, according to the {@link #doAnnotate(Object)} documentation.
   */
  public String getPairedBatchInspectionShortName() {
    return null;
  }
  ```
[ExternalAnnotator](https://github.com/JetBrains/intellij-community/blob/7f262584083cc1bdc0934981b803db2b264b5353/platform/analysis-api/src/com/intellij/lang/annotation/ExternalAnnotator.java#L81-L90)

**Closed** 2017-12-15 04:14 UTC
Labels: Kind:Bug
