### ISSUE TITLE
Edge could not be stripped from explanation line at org.elixir_lang.credo.Annotator.stripEdge(Annotator.java:249)

### ISSUE THREAD

**Issue by antwaanh** [KronicDeth/intellij-elixir#2600] opened 2022-04-19 18:33 UTC
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Mac OS X (12.3.1)

# Event

## Message

`[0m[34m┃ [34m[2m   →[0m  Priority: normal [0m`

### Stacktrace

```
java.lang.Throwable: Edge could not be stripped from explanation line
	at org.elixir_lang.credo.Annotator.stripEdge(Annotator.java:249)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
	at org.elixir_lang.credo.Annotator.explanationToToolTip(Annotator.java:402)
	at org.elixir_lang.credo.Annotator.lambda$apply$2(Annotator.java:376)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.elixir_lang.credo.Annotator.apply(Annotator.java:375)
	at org.elixir_lang.credo.Annotator.apply(Annotator.java:44)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.applyExternalAnnotatorWithContext(AnnotationHolderImpl.java:256)
	at com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.lambda$checkFileWithExternalAnnotator$1(ExternalAnnotatorInspectionVisitor.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.checkFileWithExternalAnnotator(ExternalAnnotatorInspectionVisitor.java:54)
	at org.elixir_lang.credo.inspection_tool.Local.checkFile(Local.kt:28)
```

### `induced.txt`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment] 2022-05-20 15:24
Duplicate of #954

**Closed by KronicDeth** 2022-05-20 15:24 UTC
