### ISSUE TITLE
Don't know how to check if ElixirVariable variable

### ISSUE THREAD

**Issue by mjakubowski84** [KronicDeth/intellij-elixir#646] opened 2017-03-20 07:07 UTC
# Version

4.7.0

# Exception

## Message

Don't know how to check if variable

### Excerpt

```
name
```
 Line(s) 23-23

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirVariableImpl
```

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:51)
org.elixir_lang.errorreport.Logger.error(Logger.java:34)
org.elixir_lang.reference.Callable.error(Callable.java:336)
org.elixir_lang.reference.Callable.isVariable(Callable.java:285)
org.elixir_lang.code_insight.lookup.element_renderer.Variable.color(Variable.java:103)
org.elixir_lang.code_insight.lookup.element_renderer.Variable.renderElement(Variable.java:54)
com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
com.intellij.codeInsight.lookup.impl.LookupImpl.c(LookupImpl.java:434)
com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:234)
com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:408)
com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:399)
com.intellij.codeInsight.completion.AsyncCompletion$1.a(CompletionThreading.java:139)
com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:107)
com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:87)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:84)
com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment] 2017-04-11 02:19
Duplicate of #555.  Fixes by #612.  Wait for next release.

**Closed by KronicDeth** 2017-04-11 02:19 UTC
