### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:99)

### ISSUE THREAD

**Issue by mackenziequinnjetton** [KronicDeth/intellij-elixir#3037] opened 2023-01-31 10:00 UTC
# System

Plugin Version: 14.0.0
Application: RubyMine (2022.3.2)
Operating System: Mac OS X (12.6.1)

# Event

### Element

```
Makeup.Lexer.Postprocess
```

From: `/Users/mackenziequinnjetton/Documents/GitHub/greet_everyone/lib/greet_everyone.ex:19`

#### Context

```
  def hello do
    :world
  end
end

Makeup.Lexer.Postprocess

```

From: `/Users/mackenziequinnjetton/Documents/GitHub/greet_everyone/lib/greet_everyone.ex:14-20`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedQualifiedAliasImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:99)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:83)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:79)
```

</details>

**Comment by KronicDeth** [comment] 2023-02-21 21:19
Duplicate of #2926

**Closed by KronicDeth** 2023-02-21 21:19 UTC
