### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by AHBruns** [KronicDeth/intellij-elixir#2820] opened 2022-08-28 05:14 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-10 15:18
Duplicate of #2740

**Closed by KronicDeth** 2022-09-10 15:18 UTC
