### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by ramka001** [KronicDeth/intellij-elixir#872] opened 2017-10-24 03:43 UTC
# Version

6.3.0

# Exception

## Message

Write access is allowed from event dispatch thread only

## Stacktrace

```
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@7cba956b Current thread: Thread[ApplicationImpl pooled thread 9,4,Idea Thread Group] 1012670307 SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.2.5#IU-172.4343.14 IDEA, eap:false, os:Linux 4.4.0-97-generic, java-version:JetBrains s.r.o 1.8.0_152-release-915-b12,6,main] 924543297

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:520)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1104)
	at com.intellij.openapi.application.impl.ApplicationImpl.e(ApplicationImpl.java:1192)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1016)
	at org.elixir_lang.sdk.elixir.Type.putDefaultErlangSdk(Type.java:339)
	at org.elixir_lang.mix.runner.MixRunningStateUtil.setElixir(MixRunningStateUtil.java:276)
	at org.elixir_lang.mix.runner.MixRunningStateUtil.commandLine(MixRunningStateUtil.java:174)
	at org.elixir_lang.annotator.Credo.generalCommandLine(Credo.java:100)
	at org.elixir_lang.annotator.Credo.generalCommandLine(Credo.java:142)
	at org.elixir_lang.annotator.Credo.generalCommandLine(Credo.java:244)
	at org.elixir_lang.annotator.Credo.doAnnotate(Credo.java:222)
	at org.elixir_lang.annotator.Credo.doAnnotate(Credo.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.a(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2017-10-24 12:02
Duplicate of #864.  Use [work-around](https://github.com/KronicDeth/intellij-elixir/issues/864#issuecomment-338442310).

**Closed by KronicDeth** 2017-10-24 12:02 UTC
