### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)

### ISSUE THREAD

**Issue by vitaly107** [KronicDeth/intellij-elixir#3202] opened 2023-04-29 15:51 UTC
# System

Plugin Version: 15.0.1
Application: RubyMine (2023.1)
Operating System: Mac OS X (13.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
</summary>

```
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
	at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:63)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
```

</details>

**Comment by KronicDeth** [comment] 2023-05-06 05:08
Duplicate of #3158

**Closed by KronicDeth** 2023-05-06 05:08 UTC
