### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by aleksbgs** [KronicDeth/intellij-elixir#2843] opened 2022-09-08 17:41 UTC
# System

Plugin Version: 13.2.0
Application: RubyMine (2022.2.1)
Operating System: Mac OS X (12.5.1)

# Event

### Element

```
,
```

From: `/Users/aleks/Desktop/elixirchat/fawkes/lib/fawkes_web/controllers/room_controller.ex:2`

#### Context

```
defmodule FawkesWeb.RoomController do
  use FawkesWeb,:controller
  def ping(conn,_params) do
    conn:
    |> render("ack.json",%{success:true,message:"pong"})
  end
end

```

From: `/Users/aleks/Desktop/elixirchat/fawkes/lib/fawkes_web/controllers/room_controller.ex:0-7`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

### `/Users/aleks/Desktop/elixirchat/fawkes/lib/fawkes_web/controllers/room_controller.ex`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment] 2022-09-10 15:00
Duplicate of #2774

**Closed by KronicDeth** 2022-09-10 15:00 UTC
