### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by Jianyuanlu** [KronicDeth/intellij-elixir#1025] opened 2018-02-07 08:09 UTC
# Version

7.2.1

# Exception

## Message

one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;

## Stacktrace

```
java.lang.NoSuchMethodError: one.util.streamex.StreamEx.nonNull()Lone/util/streamex/StreamEx;
	at org.elixir_lang.file.LevelPropertyPusher.initExtra(LevelPropertyPusher.java:164)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.initializeProperties(PushedFilePropertiesUpdaterImpl.java:132)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.a(FileBasedIndexProjectHandler.java:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:346)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:338)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:116)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivities(StartupManagerImpl.java:113)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:360)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:267)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progr

**Comment by KronicDeth** [comment] 2018-02-18 17:12
Duplicate of #992.  Upgrade to 7.3.0.

**Closed by KronicDeth** 2018-02-18 17:12 UTC
