### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by zapient** [KronicDeth/intellij-elixir#430] opened 2016-09-12 23:05 UTC
# Version

4.3.0

# Exception

## Message

Error while indexing /usr/local/src/elixir/lib/elixir/test/elixir/kernel/typespec_test.exs
To reindex this file IDEA has to be restarted: @NotNull method org/elixir_lang/psi/impl/ElixirPsiImplUtil.canonicalNameSet must not return null

## Stacktrace

```
java.lang.IllegalStateException: @NotNull method org/elixir_lang/psi/impl/ElixirPsiImplUtil.canonicalNameSet must not return null
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.canonicalNameSet(ElixirPsiImplUtil.java:417)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.canonicalNameSet(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:66)
	at org.elixir_lang.psi.stub.type.call.Stub.hasCanonicalNames(Stub.java:100)
	at org.elixir_lang.psi.stub.type.call.Stub.hasNameOrCanonicalNames(Stub.java:111)
	at org.elixir_lang.psi.stub.type.call.Stub.shouldCreateStub(Stub.java:87)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:69)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:208)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:191)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1559)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1516)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2016-09-15 01:52
Duplicate of #412.  Fixed in #419.  3 options:
1) Don't load the elixir std library in 4.3.0
2) Wait for 4.4.0
3) Run the canary build (https://github.com/KronicDeth/intellij-elixir/releases/tag/v4.4.0-dev%2B20160908134805) that contains the fix now.

**Closed** 2016-09-15 01:52 UTC
Labels: bug, duplicate
