### ISSUE TITLE
intellij freezes with elixir plugin

### ISSUE THREAD

**Issue by suryatejamuthyala** [KronicDeth/intellij-elixir#2484] opened 2022-01-22 15:04 UTC
whole IDE freezes when trying to edit an .ex file , find attached logs
[logs.zip](https://github.com/KronicDeth/intellij-elixir/files/7918605/logs.zip)

**Comment by steveops** [comment] 2022-01-24 03:53
I have been experiencing the same

**Comment by steveops** [comment] 2022-01-24 21:04
[freeze logs.zip](https://github.com/KronicDeth/intellij-elixir/files/7928829/freeze.logs.zip)

**Comment by steveops** [comment] 2022-01-24 21:05
> > I have been experiencing the same
> 
> can you follow the instructions [here](https://plugins.jetbrains.com/plugin/7522-elixir/reviews#review=62758-62759) https://plugins.jetbrains.com/plugin/7522-elixir/reviews#review=62758-62759 , that may help the developer

Thanks

**Comment by KronicDeth** [comment] 2022-01-29 17:03
This has the same root cause as #2457.  Please move all conversation to that issue.

**Comment by KronicDeth** [comment] 2022-01-29 17:03
Duplicate of #2457

**Closed by KronicDeth** 2022-01-29 17:03 UTC
Labels: Kind:Bug
