### ISSUE TITLE
IDE fatal error (2016.1)

### ISSUE THREAD

**Issue by imetallica** [KronicDeth/intellij-elixir#274] opened 2016-03-25 00:17 UTC
Hello, sometimes this happens on my IDE (Linux).

```
null
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.operator(ElixirPsiImplUtil.java:929)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.operator(ElixirMatchedMatchOperationImpl.java:78)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:1660)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.functionNameElement(ElixirMatchedMatchOperationImpl.java:46)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:1625)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.functionName(ElixirMatchedMatchOperationImpl.java:41)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.resolvedFunctionName(ElixirPsiImplUtil.java:3930)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.resolvedFunctionName(ElixirMatchedMatchOperationImpl.java:108)
	at org.elixir_lang.annonator.Kernel$1.visitCall(Kernel.java:185)
	at org.elixir_lang.annonator.Kernel$1.visitElement(Kernel.java:207)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirMatchedExpressionImpl.accept(ElixirMatchedExpressionImpl.java:19)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.accept(ElixirMatchedMatchOperationImpl.java:24)
	at org.elixir_lang.annonator.Kernel.annotate(Kernel.java:179)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.operator(ElixirPsiImplUtil.java:929)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.operator(ElixirMatchedMatchOperationImpl.java:78)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionNameElement(ElixirPsiImplUtil.java:1660)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.functionNameElement(ElixirMatchedMatchOperationImpl.java:46)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.functionName(ElixirPsiImplUtil.java:1625)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.functionName(ElixirMatchedMatchOperationImpl.java:41)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.resolvedFunctionName(ElixirPsiImplUtil.java:3930)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.resolvedFunctionName(ElixirMatchedMatchOperationImpl.java:108)
	at org.elixir_lang.annonator.Kernel$1.visitCall(Kernel.java:185)
	at org.elixir_lang.annonator.Kernel$1.visitElement(Kernel.java:207)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirMatchedExpressionImpl.accept(ElixirMatchedExpressionImpl.java:19)
	at org.elixir_lang.psi.impl.ElixirMatchedMatchOperationImpl.accept(ElixirMatchedMatchOperationImpl.java:24)
	at org.elixir_lang.annonator.Kernel.annotate(Kernel.java:179)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by KronicDeth** [comment] 2016-03-25 04:22
Duplicate of #251.  Fixed by #259.  Wait for release of `v2.3.0`.  Ignore the error for now: it should be a transient error due to you typing and the IDE doing error recovery on a malformed infix operation.  Once the code is valid the errors will stop being generated.

**Closed by KronicDeth** 2016-03-25 04:22 UTC
Labels: bug, duplicate
