### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by donaldww** [KronicDeth/intellij-elixir#3157] opened 2023-04-02 02:11 UTC
I run IntelliJ with Elixir plugin on two more or less identical machines. My work machine sits behind a proxy and my home machine does not.

The following error, caused by the elixir plugin, occurs constantly (as in ~ every 3 – 5 seconds) on the proxy machine. Often this error is a prelude to keyboard freeze, rotating rainbow, forced quit and restart. The constant flashing red robot for months has been unpleasant but workable, in hopes that some fixes would soon appear. But the freeze/restarts are intolerable.

The error appears when I open a project, before editing has started. This does not happen when I'm working on other languages under the same IntelliJ.

As far as using the new version of IntelliJ, Elixir is not in the plugin list.

In the meantime, I've been forced to start using VS Code, but hope this situation is temporary.

What is the story vis-a-vis future releases of the Elixir plugin in JetBrains editors?

IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Build #IU-223.8836.41, built on March 9, 2023

Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1504M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    commit-message-helper-idea-plugin (1.1.0)
    org.rust.lang (0.4.191.5293-223)
    com.thvardhan.gradianto (5.1)
    com.jetbrains.darkPurpleTheme (1.3)
    IdeaVIM (2.1.0)
    com.intellij.ideolog (203.0.30.0)
    name.kropp.intellij.makefile (223.8214.6)
    de.docs_as_co.intellij.plugin.diagramsnet (0.2.2)
    org.jetbrains.erlang (0.11.1162)
    org.elixir_lang (14.0.0)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.virtuslab.git-machete (3.8.0)
    Pythonid (223.8836.41)
    net.ashald.envfile (3.4.1)
    pro.bashsupport (3.2.1.223)
    com.fapiko.jetbrains.plugins.better_direnv (1.1.0)
    com.mallowigi (85.1.0)
    zielu.gittoolbox (500.0.5+213)

Kotlin: 223-1.8.0-release-345-IJ8836.41

                        #

java.util.NoSuchElementException
	at org.elixir_lang.reference.Resolver.moduleForSourceOrLibrary(Resolver.kt:142)
	at org.elixir_lang.reference.Resolver.filterUnderSameModule(Resolver.kt:61)
	at org.elixir_lang.reference.Resolver.preferUnderSameModule(Resolver.kt:40)
	at org.elixir_lang.reference.Resolver.preferElementUnderSameModule(Resolver.kt:32)
	at org.elixir_lang.reference.Resolver.preferred(Resolver.kt:16)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:77)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:95)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:120)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:99)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:120)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.toModulars(QualifiableAliasImpl.kt:99)
	at org.elixir_lang.psi.impl.QualifiableAliasImplKt.maybeModularNameToModulars(QualifiableAliasImpl.kt:83)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:187)
	at org.elixir_lang.psi.impl.call.qualification.QualifiedImplKt.qualifiedToModulars(QualifiedImpl.kt:19)
	at org.elixir_lang.reference.resolver.Callable.resolveQualified(Callable.kt:150)
	at org.elixir_lang.reference.resolver.Callable.resolveInScope(Callable.kt:101)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:89)
	at org.elixir_lang.reference.resolver.Callable.resolveAll(Callable.kt:85)
	at org.elixir_lang.reference.resolver.Callable.resolvePreferred(Callable.kt:75)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:38)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:34)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:29)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:147)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
	at org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
	at org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.kt:105)
	at org.elixir_lang.reference.Callable.resolve(Callable.kt:112)

**Comment by KronicDeth** [comment] 2023-04-07 20:19
Duplicate of #2956

**Closed by KronicDeth** 2023-04-07 20:19 UTC
