### ISSUE TITLE
Don't know how to get name of parameter at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:153)

### ISSUE THREAD

**Issue by manuelkiessling** [KronicDeth/intellij-elixir#2732] opened 2022-06-26 18:43 UTC
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Ultimate Edition (2022.1.2)
Operating System: Mac OS X (12.4)

# Event

### Element

```
-1
```

From: `/Users/manuel/hello/deps/decimal/lib/decimal.ex:1104`

#### Context

```
  the number will be: `sign * coefficient * 10 ^ exponent`.

  A decimal number will always be created exactly as specified with all digits
  kept - it will not be rounded with the context.
  """
  @spec new(1 | -1, non_neg_integer | :NaN | :inf, integer) :: t
  def new(sign, coef, exp)
      when sign in [1, -1] and ((is_integer(coef) and coef >= 0) or coef in [:NaN, :inf]) and
             is_integer(exp),
      do: %Decimal{sign: sign, coef: coef, exp: exp}

```

From: `/Users/manuel/hello/deps/decimal/lib/decimal.ex:1099-1109`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnaryOperationImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to get name of parameter
</summary>

```
java.lang.Throwable: Don't know how to get name of parameter
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:153)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnParameter(MultiResolve.kt:102)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:40)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHeadArguments(MultiResolve.kt:35)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnTypeHead(MultiResolve.kt:31)
	at org.elixir_lang.psi.scope.type.MultiResolve.executeOnType(MultiResolve.kt:27)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:111)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:69)
	at org.elixir_lang.psi.scope.Type.execute(Type.kt:37)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:68)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:593)
	at org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:152)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults(MultiResolve.kt:184)
	at org.elixir_lang.psi.scope.type.MultiResolve$Companion.resolveResults$default(MultiResolve.kt:176)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:42)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:23)
	at org.elixir_lang.reference.resolver.Type.resolve(Type.kt:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Type.multiResolve(Type.kt:19)
	at org.elixir_lang.ReferenceKt.safeMultiResolve(reference.kt:16)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:99)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:89)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:49)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:80)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:41)
```

</details>

**Comment by felipeloha** [comment] 2023-03-10 14:06
with the latest master of the pluging

I wrote the following code on a file and ran a test with it:
```
  @doc """
    the number will be: sign * coefficient * 10 ^ exponent
    A decimal number will always be created exactly as specified with all digits
    kept - it will not be rounded with the context.
  """
  @spec new(1 | -1, non_neg_integer | :NaN | :inf, integer) :: term()
  def new(sign, coef, exp)
      when sign in [1, -1] and ((is_integer(coef) and coef >= 0) or coef in [:NaN, :inf]) and
             is_integer(exp),
      do: %Decimal{sign: sign, coef: coef, exp: exp}
```

the tests ran successfully and the plugin did not break

**Comment by KronicDeth** [comment] 2023-03-26 05:54
Duplicate of #2795

**Closed by KronicDeth** 2023-03-26 05:54 UTC
Labels: Kind:Bug
