### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by adeftu** [KronicDeth/intellij-elixir#2789] opened 2022-08-10 19:32 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.5)

[threadDumps-freeze-20220810-153024-IU-222.3345.118.zip](https://github.com/KronicDeth/intellij-elixir/files/9303502/threadDumps-freeze-20220810-153024-IU-222.3345.118.zip)

**Comment by KronicDeth** [comment] 2022-08-22 19:07
All yours appear to be from

```
	at org.elixir_lang.reference.module.UnaliasedName.up(UnaliasedName.kt:82)
	at org.elixir_lang.reference.module.UnaliasedName.unaliasedName(UnaliasedName.kt:60)
	at org.elixir_lang.reference.module.UnaliasedName.unaliasedName(UnaliasedName.kt:18)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.getPresentableText(ItemPresentation.kt:38)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.access$getPresentableText(ItemPresentation.kt:16)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation$_presentableText$2.invoke(ItemPresentation.kt:28)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation$_presentableText$2.invoke(ItemPresentation.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.get_presentableText(ItemPresentation.kt:25)
	at org.elixir_lang.psi.impl.qualifiable_alias.ItemPresentation.getPresentableText(ItemPresentation.kt:19)
```

Unfortunately without the actual `.ex` or `.beam` file name we can't narrow down what is causing the issue.


We can hope for the best that this is the same root cause as #2800 and it is fixed by the PR.  I'll reopen if 13.2.1 does not fix you problem.

**Closed by KronicDeth** 2022-08-22 19:07 UTC
Labels: Kind:Bug, Bug:Needs More Context

**Comment by adeftu** [comment] 2022-11-09 13:51
@KronicDeth Could you please reopen? I'm on 13.2.1 and IntelliJ 2022.2.3 and the IDE still hangs many times. 
I'm attaching a new thread dump.

[threadDumps-freeze-20221109-084524-IU-222.4345.14.zip](https://github.com/KronicDeth/intellij-elixir/files/9971635/threadDumps-freeze-20221109-084524-IU-222.4345.14.zip)

**Comment by adeftu** [comment] 2022-11-09 15:05
Btw, note that 12.2.1 works fine, but that requires me to downgrade IntelliJ to 2021. So some regression must have been added somewhere in 13.x.y.

**Comment by adeftu** [comment] 2022-11-09 16:27
I found a way to consistently replicate the issue. However the file that I'm using depends on a lot of internal code of my employer that I can't share. 

Is there a way to share with me a test build of the plugin with debugging logs enabled? I could install it and share back the logs after a freeze.

**Comment by adeftu** [comment] 2022-11-09 17:15
> Btw, note that 12.2.1 works fine, but that requires me to downgrade IntelliJ to 2021. So some regression must have been added somewhere in 13.x.y.

Never mind. I just checked this file on following configurations, all freezing the IDE.

IntelliJ IDEA 2021.3.3 + Elixir 12.2.1
IntelliJ IDEA 2021.2.4 + Elixir 12.2.1
IntelliJ IDEA 2021.1.3 + Elixir 12.2.1
