### ISSUE TITLE
Don't know how to find ancestorTypeSpec at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245) for ElixirMultipleAliasesImpl

### ISSUE THREAD

**Issue by m0rt3nlund** [KronicDeth/intellij-elixir#2495] opened 2022-02-03 06:06 UTC
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.1)
Operating System: Windows 10 (10.0)

# Event

### Excerpt

```
{:ok, units} <.

    {units(units_and_processes), driver_processes(units_and_processes)}
```

From: `C:/dev/tmpRep/config-admin/lib/config_admin/config/import/plant/context.ex:117`
To: `C:/dev/tmpRep/config-admin/lib/config_admin/config/import/plant/context.ex:119`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedQualifiedMultipleAliasesImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know how to find ancestorTypeSpec
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:245)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.scope.TypeKt.ancestorTypeSpec(Type.kt:222)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeCallableReference(CallImpl.kt:122)
	at org.elixir_lang.psi.impl.call.CallImplKt.computeReference(CallImpl.kt:77)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference$lambda-4(CallImpl.kt:149)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.elixir_lang.psi.impl.call.CallImplKt.getReference(CallImpl.kt:148)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getReference(ElixirPsiImplUtil.java:1048)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.getReference(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:96)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:92)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:39)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
```

**Comment by KronicDeth** [comment] 2022-05-06 16:24
Duplicate of #2464

**Closed by KronicDeth** 2022-05-06 16:24 UTC
Labels: Kind:Bug
