### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at C:\Program Files (x86)\Elixir` is missing Erlang SDK at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)

### ISSUE THREAD

**Issue by danelmerdoc** [KronicDeth/intellij-elixir#2868] opened 2022-09-24 01:33 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at C:\Program Files (x86)\Elixir` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir at C:\Program Files (x86)\Elixir` is missing Erlang SDK
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:85)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-01 19:56
Duplicate of #2747

**Closed by KronicDeth** 2022-10-01 19:56 UTC
