### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:118)

### ISSUE THREAD

**Issue by h3d-thanhlx** [KronicDeth/intellij-elixir#3006] opened 2023-01-13 05:20 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Linux (5.15.0-57-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion
</summary>

```
java.lang.RuntimeException: java.lang.NoSuchFieldError: Companion
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:505)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:33)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at com.intellij.projectImport.ProjectOpenProcessorBase.importToProject(ProjectOpenProcessorBase.kt:185)
	at com.intellij.projectImport.ProjectOpenProcessorBase.access$importToProject(ProjectOpenProcessorBase.kt:33)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:165)
	at com.intellij.projectImport.ProjectOpenProcessorBase$doOpenProject$1.invoke(ProjectOpenProcessorBase.kt:33)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:358)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:131)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:95)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoSuchFieldError: Companion
	at org.elixir_lang.mix.project._import.Builder$commit$createModules$1.invoke(Builder.kt:110)
	at org.elixir_lang.mix.project._import.Builder$commit$createModules$1.invoke(Builder.kt:107)
	at org.elixir_lang.mix.Project.createModulesForOtpApps(Project.kt:76)
	at org.elixir_lang.mix.project._import.Builder.commit(Builder.kt:107)
```

</details>

**Comment by KronicDeth** [comment] 2023-01-27 16:42
Duplicate of #2975

**Closed by KronicDeth** 2023-01-27 16:42 UTC
