### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by zookzook** [KronicDeth/intellij-elixir#2929] opened 2022-11-15 11:56 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-16 20:29
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2817

**Closed by KronicDeth** 2022-12-16 20:29 UTC
