### ISSUE TITLE
Keyword pair does not have exactly 2 children when code is invalid

### ISSUE THREAD

**Issue by RamanBut-Husaim** [KronicDeth/intellij-elixir#1007] opened 2018-01-27 12:04 UTC
Here is the piece of code that generates the error:

```elixir
  @spec tail(t) :: {:ok, t} | {:error, :empty_list}
  def tail(%LinkedList{head: %LinkedListEntry{next: next} = head, length: length}) do
    case next do
      nil -> LinkedList.new()
      _ -> %LinkedList{head: next, length: length - 1}
    end
  end
```

When I'm removing the param name *head* with a space right after the *=* sign the exception occurs. The removal is performed by a single symbol starting with *d*, so *d* -> *a* -> *e* -> ...

Full file content could be found here - https://github.com/RamanBut-Husaim/exercism.elixir/blob/62a1e3df6cc5f5d965391f3d58827a26c7a3363a/simple-linked-list/linked_list.exs

# Version

7.2.1

# Exception

## Message

null

## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getKeywordValue(ElixirPsiImplUtil.java:3050)
	at org.elixir_lang.psi.impl.ElixirKeywordPairImpl.getKeywordValue(ElixirKeywordPairImpl.java:47)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:520)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:509)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:113)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:375)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:420)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:82)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:66)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:484)
	at org.elixir_lang.psi.scope.Variable.executeStrippedCallDefinitionHead(Variable.java:582)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:227)
	at org.elixir_lang.psi.scope.Variable.execute(Variable.java:102)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1753)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:147)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1097)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
	at org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:58)
	at org.elixir_lang.reference.resolver.Callable.resolve(Callable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:145)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:175)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at org.elixir_lang.reference.Callable.multiResolve(Callable.java:668)
	at org.elixir_lang.annotator.Callable$1.visitPlainCall(Callable.java:172)
	at org.elixir_lang.annotator.Callable$1.visitNonModuleAttributeCall(Callable.java:156)
	at org.elixir_lang.annotator.Callable$1.visitCall(Callable.java:114)
	at org.elixir_lang.annotator.Callable$1.visitElement(Callable.java:148)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:42)
	at org.elixir_lang.annotator.Callable.annotate(Callable.java:105)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by RamanBut-Husaim** [comment] 2018-01-27 12:07
**IDE**
IntelliJ IDEA 2017.3.3 (Community Edition)
Build #IC-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

**Elixir**
1.6.0

**Comment by KronicDeth** [comment] 2018-05-20 19:48
The keyword pair while the code is invalid does not have exactly 2 children.

https://github.com/KronicDeth/intellij-elixir/blob/815c0553d26f58af2cea0a7d77dcb0742d2c52c8/src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java#L3047-L3050

**Comment by KronicDeth** [comment] 2021-06-30 15:56
Duplicate of #1611

**Closed by KronicDeth** 2021-06-30 15:56 UTC
Labels: Kind:Bug
