### ISSUE TITLE
Compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by Deni7777** [KronicDeth/intellij-elixir#1875] opened 2021-01-12 19:29 UTC
# Version

11.9.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.diagnostic.PluginException: While loading class org.elixir_lang.folding.OptionsProvider: org/elixir_lang/folding/OptionsProvider has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: org.elixir_lang] [Plugin: org.elixir_lang]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:299)
	at com.intellij.openapi.util.AtomicNotNullLazyValue$1.compute(AtomicNotNullLazyValue.java:59)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:37)
	at com.intellij.openapi.options.ConfigurableEP.canCreateConfigurable(ConfigurableEP.java:342)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:34)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:29)
	at com.intellij.application.options.editor.CodeFoldingOptionsTopHitProvider.lambda$getOptions$1(CodeFoldingOptionsTopHitProvider.java:31)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:21)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.application.options.editor.CodeFoldingOptionsTopHitProvider.getOptions(CodeFoldingOptionsTopHitProvider.java:30)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.java:66)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:54)
	at

**Comment by KronicDeth** [comment] 2021-01-12 23:15
@Deni7777 what IDE and version of that IDE are you using?  Are you using the bundled JBR or your system JRE? Class file version 53.0 is from Java 9 while the version it wants, 52.0 is from Java 8, but modern releases of IntelliJ's JBR are Java 11.

You can get this from the splash image on the About menu item in the IDE like below

![Screen Shot 2021-01-12 at 5 14 18 PM](https://user-images.githubusercontent.com/298259/104385934-bda18080-54f9-11eb-97e6-f39f0d100a04.png)

**Comment by KronicDeth** [comment] 2021-01-15 04:09
Duplicate of #1870

**Closed by KronicDeth** 2021-01-15 04:09 UTC
Labels: Kind:Bug:Regression
