### ISSUE TITLE
java.lang.IllegalStateException: seed must not be null at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)

### ISSUE THREAD

**Issue by mail2bapi** [KronicDeth/intellij-elixir#2784] opened 2022-08-09 13:18 UTC
# System

Plugin Version: 13.2.0
Application: PhpStorm (2022.2)
Operating System: Linux (5.15.0-43-generic)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: seed must not be null
</summary>

```
java.lang.IllegalStateException: seed must not be null
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions$default(PsiElementImpl.kt:213)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-09 13:24
Duplicate of #2773

**Closed by KronicDeth** 2022-08-09 13:24 UTC
