### ISSUE TITLE
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:,   2 != 3,   which is length of CachedValue dependencies: [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL],   where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null), , Recomputation gives com.intellij.util.CachedValueBase$Data@7a759e13 which is equivalent to 'fresh' [Plugin: org.elixir_lang] at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)

### ISSUE THREAD

**Issue by Ridtt** [KronicDeth/intellij-elixir#2939] opened 2022-11-25 10:46 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.4)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
</summary>

```
com.intellij.diagnostic.PluginException: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  2 != 3
  which is length of CachedValue dependencies: [UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL] and [PSI_MOD_COUNT_OPTIMIZATION, UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
  where values are  org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null) and org.elixir_lang.psi.__module__.Reference(UNMATCHED_UNQUALIFIED_NO_ARGUMENTS_CALL:null)

Recomputation gives com.intellij.util.CachedValueBase$Data@7a759e13 which is equivalent to 'fresh' [Plugin: org.elixir_lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at org.elixir_lang.psi.__MODULE__.reference(__MODULE__.kt:18)
	at org.elixir_lang.psi.impl.call.CallImplKt.maybeModularNameToModulars(CallImpl.kt:330)
	at org.elixir_lang.psi.impl.PsiElementImplKt.maybeModularNameToModulars(PsiElementImpl.kt:188)
	at org.elixir_lang.psi.Using.treeWalkUpFromLastChildCall(Using.kt:67)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:44)
	at org.elixir_lang.psi.Using.treeWalkUp(Using.kt:27)
	at org.elixir_lang.psi.Use.treeWalkUp(Use.kt:39)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:65)
	at org.elixir_lang.psi.scope.Module.execute(Module.kt:39)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:165)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:615)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.processDeclarations(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:156)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:440)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl$processDeclarations$5.invoke(ProcessDeclarationsImpl.kt:439)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:442)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:468)
	at kotlin.sequences.SequencesKt___SequencesKt.lastOrNull(_Sequences.kt:300)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:443)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:417)
	at org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:265)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:655)
	at org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:65)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:137)
	at org.elixir_lang.psi.scope.module.MultiResolve$Companion.resolveResults(MultiResolve.kt:128)
	at org.elixir_lang.reference.resolver.Module.resolveInScope(Module.kt:83)
	at org.elixir_lang.reference.resolver.Module.resolveAll(Module.kt:78)
	at org.elixir_lang.reference.resolver.Module.resolvePreferred(Module.kt:72)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:35)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:31)
	at org.elixir_lang.reference.resolver.Module.resolve(Module.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at org.elixir_lang.reference.Module.multiResolve(Module.kt:31)
	at org.elixir_lang.reference.Module.resolve(Module.kt:38)
```

</details>

**Comment by KronicDeth** [comment] 2023-01-06 19:15
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2205

**Closed by KronicDeth** 2023-01-06 19:15 UTC
