### ISSUE TITLE
Keywords (defmodule, defp, etc) have no own color class in editor 

### ISSUE THREAD

**Issue by fuson** [KronicDeth/intellij-elixir#110] opened 2015-04-08 08:06 UTC
In all other languages it classified as "Keyword" and have proper color style.

**Comment by KronicDeth** [comment] 2015-04-09 03:59
The issue is that node coloring is part of the syntax highlighter and only the lexer's leaf nodes have syntax highlighting applied to them, so in order to have `defmodule` for modules and `def` and `defp` for functions colored a Keywords, I have to make them be special rules in the lexer, but from Elixir's perspective, `defmodule`, `def`, and `defp` aren't special, they are just identifiers, so they get that color.  

I'd rather not start adding specialization hacks for this as it goes counter to supporting the fully allowed macro syntax of Elixir and means I need to update the lexer not when the language changes, but when a given macro becomes popular, such as coloring `test` in ExUnit a different color.

If it turns out there's a way to color nodes without changing the lexer I'll consider this, but for now I'm closing this issue.  (**Note: If there is a way to color nodes outside of having different lexer element types it would simplify the handling of sigils as currently implemented because I need to keep track you're in a regex sigil to color it's fragments a different color**)

**Closed by KronicDeth** 2015-04-09 03:59 UTC
