### ISSUE TITLE
Provide means to download Elixir source code for reference

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#597] opened 2017-01-23 18:08 UTC
Thing is Elixir does not ship source files along with release so in order to be able to navigate somewhere to stdlib I have to download it myself, unpack it and configure Sourcepath in projects' SDK settings.

**Comment by KronicDeth** [comment] 2017-01-23 18:15
I'm counting this as a duplicate of #113.

**Closed by KronicDeth** 2017-01-23 18:15 UTC
Labels: duplicate, enhancement
