### ISSUE TITLE
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.sdks.erlang.Configurable;, specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: org.elixir_lang] at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)

### ISSUE THREAD

**Issue by josuehenrique** [KronicDeth/intellij-elixir#3348] opened 2023-09-16 04:16 UTC
# System

Plugin Version: 16.0.0
Application: RubyMine (2023.2.1)
Operating System: Linux (6.2.0-32-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.sdks.erlang.Configurable;
</summary>

```
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.sdks.erlang.Configurable;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: org.elixir_lang]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.<init>(SettingsTreeView.java:534)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.buildChildren(SettingsTreeView.java:571)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:26)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:12)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:67)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:82)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:82)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:62)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:54)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:45)
	at com.intellij.ui.tree.FilteringTreeModel.createModel(FilteringTreeModel.java:26)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:199)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:89)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:195)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:65)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.kt:39)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.showSettingsDialog(ShowSettingsUtilImpl.kt:88)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.showSmallIDEFacetSettings(Provider.kt:78)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.createSmallIDEFacetPanel$lambda$1$lambda$0(Provider.kt:86)
	at com.intellij.ui.EditorNotificationPanel$6.handlePanelActionClick(EditorNotificationPanel.java:442)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel$1.hyperlinkActivated(EditorNotificationPanel.java:487)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:14)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:242)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:164)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
```

</details>

**Comment by KronicDeth** [comment] 2023-11-03 17:27
Duplicate of #3345

**Closed by KronicDeth** 2023-11-03 17:27 UTC
