### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by josuehenrique** [KronicDeth/intellij-elixir#645] opened 2017-03-17 18:42 UTC
# Version

4.7.0

# Exception

## Message
```
  def get_group_atom(group_name) when is_bitstring(group_name) do
    case group_name do
      "Bloqueado" -> :block
      "Bloqueado LC" -> :block_cl
      "Inativo" -> :inactive
      _ -> nil
    end
  end

  defp get_default_profile_name #THIS ERROR RAISED WHEN I WROTE THIS LINE

  defp default_group_names, do: [:block, :block_cl, :inactive]

  defp in_default_groups?(group_name) do
    get_group_atom(group_name)
      |> !is_nil
  end
```
## Stacktrace

```
java.lang.AssertionError
	at org.elixir_lang.code_insight.lookup.element_renderer.CallDefinitionClause.renderElement(CallDefinitionClause.java:38)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:147)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.a(LookupImpl.java:419)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.c(LookupImpl.java:396)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.refreshUi(LookupImpl.java:1086)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.d(CompletionProgressIndicator.java:350)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$000(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1.run(CompletionProgressIndicator.java:103)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2493)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by josuehenrique** [comment] 2017-03-17 18:42
@KronicDeth

**Comment by KronicDeth** [comment] 2017-04-11 02:08
Duplicate of #563.  Trying typing the example in a scratch tab in master does not trigger the error, so #609 seems to have fixed it (or a scratch file isn't enough to trigger the bug and it requires project index to trigger :man_shrugging:)

**Closed by KronicDeth** 2017-04-11 02:08 UTC
