### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;

### ISSUE THREAD

**Issue by payomdousti** [KronicDeth/intellij-elixir#1409] opened 2019-03-07 21:48 UTC
# Version

10.2.0

# Exception

## Message

com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;

## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VfsUtil.findFile(Ljava/nio/file/Path;Z)Lcom/intellij/openapi/vfs/VirtualFile;
	at org.elixir_lang.mix.Dep.virtualFile(Dep.kt:19)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:49)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:43)
	at org.elixir_lang.DepsWatcher.syncLibraries(DepsWatcher.kt:184)
	at org.elixir_lang.DepsWatcher.syncLibrary(DepsWatcher.kt:165)
	at org.elixir_lang.DepsWatcher.access$syncLibrary(DepsWatcher.kt:31)
	at org.elixir_lang.DepsWatcher$fileCreated$2.run(DepsWatcher.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2019-03-14 18:53
What IDE and version are you using?

**Comment by YannCebron** [comment] 2019-03-15 09:29
method was added in  

65b6d4cb7c64499ec245473828c890700431a7cc | Wed Jul 04 11:11:10 CEST 2018 | Alexandr Evstigneev | Fixed local default gems discovery in some cases

**Comment by KronicDeth** [comment] 2023-06-16 17:28
Duplicate of #1391

**Closed by KronicDeth** 2023-06-16 17:28 UTC
Labels: Kind:Bug
