### ISSUE TITLE
Can't open all project when update to Intellij IDEA 2019.2

### ISSUE THREAD

**Issue by vwlio** [KronicDeth/intellij-elixir#1527] opened 2019-07-26 11:47 UTC
**Describe the bug**
When I upgrade my Intellij IDEA to 2019.2. All my project can't be opened.
I get some error from intellij-elixir plugin. And when I disabled it, I can open my project again.
**Logs**
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: org.elixir_lang.mix.project.OpenProcessor.<init>()
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:408)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:136)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:42)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:54)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:439)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:226)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:277)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodException: org.elixir_lang.mix.project.OpenProcessor.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:382)
	... 25 more
2019-07-26 20:35:22,765 [  11464]   WARN - util.DeprecatedMethodException - This method in class com.intellij.util.containers.WeakHashMap is deprecated and going to be removed soon. Use ContainerUtil.createWeakMap() instead 
com.intellij.util.DeprecatedMethodException: This method in class com.intellij.util.containers.WeakHashMap is deprecated and going to be removed soon. Use ContainerUtil.createWeakMap() instead
	at com.intellij.util.DeprecatedMethodException.report(DeprecatedMethodException.java:15)
	at com.intellij.util.containers.WeakHashMap.<init>(WeakHashMap.java:46)
	at org.elixir_lang.sdk.erlang.Type.<init>(Type.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:389)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:136)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:42)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:54)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:439)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:226)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.intellij.openapi.projectRoots.SdkType.getAllTypes(SdkType.java:210)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.findSdkTypeByName(ProjectJdkTableImpl.java:222)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.getSdkTypeByName(ProjectJdkTableImpl.java:217)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.readExternal(ProjectJdkImpl.java:157)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.loadState(ProjectJdkTableImpl.java:243)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:57)
	at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:17)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:405)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:355)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:122)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:97)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:44)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:248)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
	at com.intellij.openapi.projectRoots.ProjectJdkTable.getInstance(ProjectJdkTable.java:20)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.reset(ProjectSdksModel.java:80)
	at org.elixir_lang.facet.SdksService.initModel(SdksService.kt:29)
	at org.elixir_lang.facet.SdksService.getModel(SdksService.kt:18)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.sdkNameSet(Converter.kt:41)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.missingLibraryNameSet(Converter.kt:38)
	at org.elixir_lang.facet.external_library.conversion.ConverterKt.access$missingLibraryNameSet(Converter.kt:1)
	at org.elixir_lang.facet.external_library.conversion.Converter.isConversionNeeded(Converter.kt:13)
	at com.intellij.conversion.impl.ConversionRunner.isConversionNeeded(ConversionRunner.java:89)
	at com.intellij.impl.ConversionServiceImpl.isConversionNeeded(ConversionServiceImpl.java:173)
	at com.intellij.impl.ConversionServiceImpl.convert(ConversionServiceImpl.java:114)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:589)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-07-26 20:35:22,840 [  11539]  ERROR - m.PlatformProjectOpenProcessor - The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 3,4,Idea Thread Group] 
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 3,4,Idea Thread Group]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2104)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1247)
	at com.intellij.conversion.impl.ui.ConvertProjectDialog.<init>(ConvertProjectDialog.java:95)
	at com.intellij.impl.ConversionServiceImpl.convert(ConversionServiceImpl.java:119)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:589)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
**Desktop:**
 - OS: macOS
 - Version 10.14.5

**Erlang:**
- Installer homebrew
- Version 22.0.4

**Elixir:**
- Installer homebrew
- Version 1.9.1

**Plugin:**
- Version 10.6.0

**Additional context**
When I tried to open my elixir project on windows I get the unknow version sdk error and can't set elixir sdk. I'm so sorry that I didn't save the error log.

**Comment by olivierpichon** [comment] 2019-08-15 10:40
Hey guys, we are facing the exact same issue. The plugin is basically incompatible with any new version of Intellij IDEA. And so atm we have to disable the plugin to open our Elixir projects. @KronicDeth I am sure you must be busy with a million things, but do you think we could expect someone to take a look at this or should we explore moving to another editor for Elixir projects? Thx a lot for everything!

**Comment by KronicDeth** [comment] 2019-08-15 12:53
@olivierpichon as a work-around, the JetBrains Toolbox allows you install old versions of the IDEs and pin a version.

I will try to get a quick fix out today, but I am otherwise very busy preparing for ElixirConf at the end of the month.

**Comment by KronicDeth** [comment] 2019-08-15 12:54
Forgot, but Toolbox also lets you install 2 versions side-by-side too.

**Comment by olivierpichon** [comment] 2019-08-15 13:07
Thanks a lot @KronicDeth!

**Comment by KronicDeth** [comment] 2019-08-15 15:11
I think the bug is due to this change:

> Constructor injection referring to extension points not supported
> Obtain reference to extension points via (Project)ExtensionPointName.findExtension() in your constructor instead
-- https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html#section-1

**Comment by KronicDeth** [comment] 2019-08-15 17:36
It is also affected by https://youtrack.jetbrains.com/issue/IDEA-218071, which does not have a fix.  I'm going to have to take out the project converters for now, so people on really old versions of the IDE might need to manually re-import projects after that instead of the file layout of the project files being auto-updated.

**Comment by olivierpichon** [comment] 2019-08-15 18:48
Thank you so much for the update

**Closed** 2019-08-15 19:49 UTC

**Comment by KronicDeth** [comment] 2019-08-15 21:16
Fixed in #1545 and #1546.

**Comment by KronicDeth** [comment] 2019-08-15 21:24
@vwlio, @olivierpichon I just released v11.0.0.  It should be 2019.2 compatible.

**Comment by olivierpichon** [comment] 2019-08-16 06:19
Amazing @KronicDeth : I re-installed from the release (from disk). RubyMine does not crash anymore, but I have no syntax highlighting.
The plugin seems to be installed correctly though. Most likely a user error. Appreciate all the hard work you put into this in any cases
<img width="530" alt="Screen Shot 2019-08-16 at 8 17 25 am" src="https://user-images.githubusercontent.com/3260198/63147450-837b3900-bffe-11e9-86c0-f20d42ee3f54.png">
<img width="1014" alt="Screen Shot 2019-08-16 at 8 17 46 am" src="https://user-images.githubusercontent.com/3260198/63147459-883fed00-bffe-11e9-991b-bbc3d8b92624.png">

**Comment by KronicDeth** [comment] 2019-08-16 11:07
2019.2 has a bug that prevents the project converters, which setup some of the project layout like the facets automatically, from running.  It may be that the facets are affected by this.  You could try removing the Rubymine project files (`*.iml` and the `.idea` directory) to see if the problem is fixed on reimport.

**Comment by olivierpichon** [comment] 2019-08-16 11:23
Thanks! I should have mentioned I tried to do that (removing the .idea directory) without success. While the plugin is installed, Elixir is not listed in the Languages / Framework.
<img width="1015" alt="Screen Shot 2019-08-16 at 1 20 25 pm" src="https://user-images.githubusercontent.com/3260198/63164520-fbf6ef80-c028-11e9-9dbd-1d8f382d2b40.png">

**Comment by KronicDeth** [comment] 2019-08-16 11:56
Go to the Help menu and select View Log or View Log in Finder.  Check if there are any errors in the log.  The Facet API could have changed too, but unlike the OpenProcessor it does crash immediately, so is just hidden in the menu.

**Comment by olivierpichon** [comment] 2019-08-16 12:12
The log shows no Exception but shows that the plugin is disabled. It does not give much more details as to why. What's even weirder is (as you can see on the above print screen) the UI shows the extension as enabled:
```
2019-08-16 14:10:38,613 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2019-08-16 14:10:38,622 [      9]   INFO -        #com.intellij.idea.Main - initializing environment 
2019-08-16 14:10:38,623 [     10]   INFO - .intellij.util.EnvironmentUtil - loading shell env: /bin/bash -l -i -c '/Applications/RubyMine.app/Contents/bin/printenv.py' '/private/var/folders/t_/qnltz_vx5_dclfg_8s010wnm0000gr/T/intellij-shell-env.tmp' 
2019-08-16 14:10:38,626 [     13]   INFO -        #com.intellij.idea.Main - IDE: RubyMine (build #RM-192.5728.104, 23 Jul 2019 16:23) 
2019-08-16 14:10:38,626 [     13]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (10.14.6, x86_64) 
2019-08-16 14:10:38,626 [     13]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_212-release-1586-b4 (JetBrains s.r.o) 
2019-08-16 14:10:38,626 [     13]   INFO -        #com.intellij.idea.Main - JVM: 25.212-b4 (OpenJDK 64-Bit Server VM) 
2019-08-16 14:10:38,639 [     26]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx2048m -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/Users/olivier/java_error_in_rubymine_%p.log -XX:HeapDumpPath=/Users/olivier/java_error_in_rubymine.hprof -Djb.vmOptionsFile=/Users/olivier/Library/Preferences/RubyMine2019.2/rubymine.vmoptions -Didea.home.path=/Applications/RubyMine.app/Contents -Didea.executable=rubymine -Didea.platform.prefix=Ruby -Didea.paths.selector=RubyMine2019.2 
2019-08-16 14:10:38,639 [     26]   INFO -        #com.intellij.idea.Main - ext: /Applications/RubyMine.app/Contents/jdk/Contents/Home/jre/lib/ext: [sunec.jar, nashorn.jar, cldrdata.jar, jfxrt.jar, dnsns.jar, localedata.jar, sunjce_provider.jar, meta-index, sunpkcs11.jar, jaccess.jar, zipfs.jar] 
2019-08-16 14:10:38,639 [     26]   INFO -        #com.intellij.idea.Main - ext: /System/Library/Java/Extensions: [MRJToolkit.jar] 
2019-08-16 14:10:38,639 [     26]   INFO -        #com.intellij.idea.Main - charsets: JNU=UTF-8 file=UTF-8 
2019-08-16 14:10:38,721 [    108]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 53 ms 
2019-08-16 14:10:40,421 [   1808]   INFO - tellij.diagnostic.LoadingPhase - Reached SPLASH loading phase 
2019-08-16 14:10:40,435 [   1822]   INFO - plication.impl.ApplicationImpl - CPU cores: 4; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@4a785df6[Running, parallelism = 3, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@4cca1615 
2019-08-16 14:10:40,721 [   2108]   INFO - llij.ide.plugins.PluginManager - Plugin 'Configuration Script' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA 
2019-08-16 14:10:40,727 [   2114]   INFO - llij.ide.plugins.PluginManager - Plugin 'Native Debug for IntelliJ' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA 
2019-08-16 14:10:40,782 [   2169]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: CSS (192.5728.104), CoffeeScript (192.5728.104), Database Tools and SQL (192.5728.104), Docker (192.5728.104), EditorConfig (192.5728.104), Gherkin (192.5728.104), Git (192.5728.104), GitHub (192.5728.104), HTML Tools (192.5728.104), HTTP Client (192.5728.104), Haml (192.5728.104), IDE Settings Sync (192.5728.104), IDEA CORE (192.5728.104), IntelliLang (192.5728.104), JavaScript Debugger (192.5728.104), JavaScript Intention Power Pack (192.5728.104), JavaScript and TypeScript (192.5728.104), Less (192.5728.104), Markdown (192.5728.104), Mercurial (192.5728.104), Perforce (192.5728.104), Performance Testing (192.5728.104), Puppet (192.5728.104), Remote Hosts Access (192.5728.104), Ruby CSS Support Integration (192.5728.104), Ruby Code Coverage (192.5728.104), Ruby Cucumber support (192.5728.104), Ruby Database Support Integration (192.5728.104), Ruby Docker (192.5728.104), Ruby Haml Support Integration (192.5728.104), Ruby I18n Support Integration (192.5728.104), Ruby JavaScript Debugger Integration (192.5728.104), Ruby Performance Testing (192.5728.104), Ruby Puppet Support Integration (192.5728.104), Ruby Remote SDK Support (192.5728.104), Ruby Slim Support Integration (192.5728.104), Ruby UML Support Integration (192.5728.104), SSH Remote Run (192.5728.104), Sass (192.5728.104), Settings Repository (192.5728.104), Shell Script (192.5728.104), Slim (192.5728.104), Stylus (192.5728.104), Subversion (192.5728.104), Task Management (192.5728.104), Terminal (192.5728.104), TextMate bundles (192.5728.104), Time Tracking (192.5728.104), UML (192.5728.104), Vagrant (192.5728.104), YAML (192.5728.104), tslint (192.5728.104) 
2019-08-16 14:10:40,782 [   2169]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Configuration Script (192.5728.104), Elixir (11.0.0), Native Debug for IntelliJ (192.5728.104) 
2019-08-16 14:10:42,231 [   3618]   INFO - .intellij.util.EnvironmentUtil - shell environment loaded (21 vars) 
2019-08-16 14:10:42,258 [   3645]   INFO - .intellij.util.EnvironmentUtil - LC_CTYPE=en_AU.UTF-8 
2019-08-16 14:10:42,343 [   3730]   INFO - m.intellij.ui.mac.touchbar.NST - touchbar-server isn't running, skip nst loading 
2019-08-16 14:10:42,503 [   3890]   INFO - cloudConfig.CloudConfigManager - === Start: JBA_NOT_CONNECTED === 
2019-08-16 14:10:42,535 [   3922]   INFO - tellij.diagnostic.LoadingPhase - Reached CONFIGURATION_STORE_INITIALIZED loading phase 
2019-08-16 14:10:42,583 [   3970]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2019-08-16 14:10:42,583 [   3970]   INFO - pi.util.registry.RegistryState -   dumb.aware.run.configurations = true 
2019-08-16 14:10:42,616 [   4003]   INFO - pi.util.registry.RegistryState - Experimental features enabled for user: inline.browse.button, linux.native.menu, recent.and.edited.files.together, show.create.new.element.in.popup, new.large.text.file.viewer, ruby.force.explicit.bundle.exec, ruby.run.anything.remote.sdk.enabled, ruby.use.experimental.debugger, ruby.docker.get.sdk.via.docker.cp 
2019-08-16 14:10:42,640 [   4027]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=1994 
2019-08-16 14:10:42,731 [   4118]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/RubyMine.app/Contents/bin/fsnotifier 
2019-08-16 14:10:42,739 [   4126]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2019-08-16 14:10:43,362 [   4749]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2019-08-16 14:10:43,383 [   4770]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2019-08-16 14:10:43,518 [   4905]   INFO - il.indexing.FileBasedIndexImpl - File index extensions iterated:46 
2019-08-16 14:10:43,792 [   5179]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.plugins.ruby.version.management.system.RubySystemData 
2019-08-16 14:10:43,987 [   5374]   INFO - pl$FileIndexDataInitialization - Initialization done:515 
2019-08-16 14:10:44,157 [   5544]   INFO - exImpl$StubIndexInitialization - Initialization done:168 
2019-08-16 14:10:44,501 [   5888]   INFO - j.ide.ui.OptionsTopHitProvider - 10 ms spent to cache options in application 
2019-08-16 14:10:44,654 [   6041]   INFO - tellij.diagnostic.LoadingPhase - Reached FRAME_SHOWN loading phase 
2019-08-16 14:10:45,457 [   6844]   INFO - cloudConfig.CloudConfigManager - === Start.updateInitStatus === 
2019-08-16 14:10:45,459 [   6846]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus === 
2019-08-16 14:10:45,517 [   6904]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2019-08-16 14:10:45,577 [   6964]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: VibrantInk from plugin: com.intellij.database 
2019-08-16 14:10:45,577 [   6964]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: WarmNeon from plugin: com.intellij.database 
2019-08-16 14:10:45,577 [   6964]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: High сontrast from plugin: com.intellij.database 
2019-08-16 14:10:45,852 [   7239]   INFO - .cloudConfig.CloudConfigClient - === Get cloud config URL: https://cloudconfig.jetbrains.com/cloudconfig/files === 
2019-08-16 14:10:46,121 [   7508]   INFO - ment.rvm.LocalRvmPathsSettings - RVM installation wasn't detected. 
2019-08-16 14:10:46,137 [   7524]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus.value: JBA_NOT_CONNECTED === 
2019-08-16 14:10:46,527 [   7914]   INFO - cloudConfig.CloudConfigManager - === End.updateInitStatus === 
2019-08-16 14:10:49,195 [  10582]   INFO - pl.projectlevelman.NewMappings - VCS Root: [Git] - [/Users/olivier/Documents/sources/panoramix] 
2019-08-16 14:10:49,790 [  11177]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2019-08-16 14:10:49,975 [  11362]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2019-08-16 14:10:50,798 [  12185]   INFO -              PerformancePlugin - Performance Plugin is in silent mode 
2019-08-16 14:10:51,446 [  12833]   INFO - llij.database.util.SqlDialects - SQL dialects initialized in 8 ms 
2019-08-16 14:10:51,547 [  12934]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 1 millis (read time: 1) 
2019-08-16 14:10:51,602 [  12989]   INFO - j.ide.ui.OptionsTopHitProvider - 728 ms spent to cache options in project 
2019-08-16 14:10:51,645 [  13032]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 794ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2019-08-16 14:10:51,892 [  13279]   INFO - tartup.impl.StartupManagerImpl - /Users/olivier/Documents/sources/panoramix/.idea case-sensitivity: expected=false actual=false 
2019-08-16 14:10:51,904 [  13291]   INFO - tellij.diagnostic.LoadingPhase - Reached PROJECT_OPENED loading phase 
2019-08-16 14:10:51,928 [  13315]   INFO -  #git4idea.commands.GitHandler - [.] git version 
2019-08-16 14:10:52,022 [  13409]   INFO -  #git4idea.commands.GitHandler - git version 2.20.1 (Apple Git-117) 
2019-08-16 14:10:52,032 [  13419]   INFO - ea.config.GitExecutableManager - Git version for /usr/bin/git : 2.20.1 
2019-08-16 14:10:52,155 [  13542]   INFO - Json.PackageJsonUpdateNotifier - processPackageJsonFiles [] 
2019-08-16 14:10:52,181 [  13568]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 3148 ms 
2019-08-16 14:10:54,631 [  16018]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 3213ms; general responsiveness: ok; EDT responsiveness: 1/4 sluggish 
2019-08-16 14:10:55,448 [  16835]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 815ms; general responsiveness: ok; EDT responsiveness: ok 
2019-08-16 14:10:55,469 [  16856]   INFO - tellij.diagnostic.LoadingPhase - Reached INDEXING_FINISHED loading phase 
2019-08-16 14:10:55,514 [  16901]   INFO - cloudConfig.CloudConfigManager - === StatusBar.start create === 
2019-08-16 14:10:56,382 [  17769]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2019-08-16 14:10:56,854 [  18241]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 389ms; general responsiveness: ok; EDT responsiveness: ok 
2019-08-16 14:10:56,918 [  18305]   INFO - ings.impl.UpdateCheckerService - channel: release 
2019-08-16 14:10:56,965 [  18352]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 111ms; general responsiveness: ok; EDT responsiveness: ok 
2019-08-16 14:10:57,036 [  18423]   INFO - e.GemRequirementsChangeWatcher - Initial scan started 
2019-08-16 14:10:58,014 [  19401]   INFO - e.GemRequirementsChangeWatcher - Initial scan took: 978 ms 
```

**Comment by KronicDeth** [comment] 2019-08-16 13:08
I can reproduce in Rubymine 2019.2.

@olivierpichon use IntelliJ Community Edition (free) or IntelliJ Ultimate (more web features, but not free) as the 11.0.0 works in that until I figure out what is different specifically in Rubymine 2019.2, but not in IntelliJ 2019.2.  Moving to a new issue.

**Comment by olivierpichon** [comment] 2019-08-16 13:14
Sounds good, thank you!

**Comment by vwlio** [comment] 2019-08-17 01:04
Thanks for fixing this bug, now I can move my project from 2019.1.4 to 2019.2.
