### ISSUE TITLE
accessExpressions should be flattened with buildAccessExpressionChildren

### ISSUE THREAD

**Issue by Soimil** [KronicDeth/intellij-elixir#1490] opened 2019-05-24 21:23 UTC
# Exception

## Stacktrace

```
java.lang.AssertionError: accessExpressions should be flattened with buildAccessExpressionChildren
	at org.elixir_lang.formatter.Block.<init>(Block.java:311)
	at org.elixir_lang.formatter.Block.buildChild(Block.java:795)
	at org.elixir_lang.formatter.Block.lambda$buildMapUpdateArgumentsChildren$27(Block.java:1521)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildMapUpdateArgumentsChildren(Block.java:1511)
	at org.elixir_lang.formatter.Block.lambda$buildMapArgumentsChildren$24(Block.java:1424)
	at org.elixir_lang.formatter.Block.lambda$buildContainerChildren$14(Block.java:1084)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildContainerChildren(Block.java:1074)
	at org.elixir_lang.formatter.Block.buildMapArgumentsChildren(Block.java:1412)
	at org.elixir_lang.formatter.Block.lambda$buildMapChildren$25(Block.java:1444)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:330)
	at org.elixir_lang.formatter.Block.buildMapChildren(Block.java:1439)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:881)
	at org.elixir_lang.formatter.Block.buildChildren(Block.java:968)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:61)
	at com.intellij.formatting.InitialInfoBuilder.buildFrom(InitialInfoBuilder.java:164)
	at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:264)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:136)
	at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:41)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:437)
	at com.intellij.formatting.FormatterImpl.buildProcessorAndWrapBlocks(FormatterImpl.java:422)
	at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:310)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.doPerform(CodeStyleManagerImpl.java:395)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:106)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:398)
	at com.intellij.codeInsight.editorActions.PasteHandler.indentEachLine(PasteHandler.java:288)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$doPaste$3(PasteHandler.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.editorActions.PasteHandler.doPaste(PasteHandler.java:207)
	at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:98)
	at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:55)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:216)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:215)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:102)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:111)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:671)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment] 2023-07-08 04:08
Duplicate of #1075

**Closed by KronicDeth** 2023-07-08 04:08 UTC
Labels: Kind:Bug, Feature:Formatter
