### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented. at org.elixir_lang.documentation.ElixirDocumentationProvider.formatDocs(ElixirDocumentationProvider.kt:123)

### ISSUE THREAD

**Issue by DesmondLouis** [KronicDeth/intellij-elixir#2569] opened 2022-04-01 07:42 UTC
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Linux (5.13.0-37-generic)

# Event

## Message

Unhandled exception in [StandaloneCoroutine{Cancelling}@4a539751, EdtCoroutineDispatcher@ac7a409]

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented.
	at org.elixir_lang.documentation.ElixirDocumentationProvider.formatDocs(ElixirDocumentationProvider.kt:123)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

**Comment by KronicDeth** [comment] 2022-05-07 01:49
Duplicate of #2412

**Closed by KronicDeth** 2022-05-07 01:49 UTC
