### ISSUE TITLE
java.lang.NullPointerException at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)

### ISSUE THREAD

**Issue by renews** [KronicDeth/intellij-elixir#2581] opened 2022-04-09 10:52 UTC
# System

Plugin Version: 12.2.0
Application: RubyMine (2021.3.3)
Operating System: Windows 11 (10.0)

# Event

## Message

Unhandled exception in [StandaloneCoroutine{Cancelling}@5eb6a4f3, EdtCoroutineDispatcher@6c9675d9]

### Stacktrace

```
java.lang.NullPointerException
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

**Comment by KronicDeth** [comment] 2022-05-07 20:06
Duplicate of #2564

**Closed by KronicDeth** 2022-05-07 20:06 UTC
