### ISSUE TITLE
NotImplementedError at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.time(CallDefinitionClause.kt:197) 	

### ISSUE THREAD

**Issue by aaylward** [KronicDeth/intellij-elixir#2059] opened 2021-08-14 06:01 UTC
# Version

11.13.0

# What I was doing

opening an sbt project

# Exceptions

### Stacktrace

```
kotlin.NotImplementedError: An operation is not implemented: Should not happen
	at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.time(CallDefinitionClause.kt:197)
	at org.elixir_lang.structure_view.element.CallDefinition$Companion.fromCall(CallDefinition.kt:243)
	at org.elixir_lang.structure_view.element.CallDefinitionClause$Companion.fromCall(CallDefinitionClause.kt:220)
	at org.elixir_lang.psi.impl.PresentationImpl.getPresentation(PresentationImpl.kt:31)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getPresentation(ElixirPsiImplUtil.java:1114)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.getPresentation(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:112)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.update(PsiElement2UsageTargetAdapter.java:277)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:63)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:68)
	at com.intellij.find.findUsages.PsiElement2UsageTargetAdapter.<init>(PsiElement2UsageTargetAdapter.java:90)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:29)
	at org.elixir_lang.UsageTargetProvider.getTargets(UsageTargetProvider.kt:22)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:42)
	at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:27)
	at com.intellij.ide.impl.dataRules.UsageTargetsRule.getData(UsageTargetsRule.java:13)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:116)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:126)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:344)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:273)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:298)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:295)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:294)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:292)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment] 2021-11-30 19:43
Duplicate of #2014

**Closed by KronicDeth** 2021-11-30 19:43 UTC
Labels: Kind:Bug
