### ISSUE TITLE
Do not know whether to inject Markdown in documentation at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:47)

### ISSUE THREAD

**Issue by jiaojing** [KronicDeth/intellij-elixir#2821] opened 2022-08-29 12:50 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Community Edition (2022.2.1)
Operating System: Mac OS X (12.5.1)

# Event

### Element

```
File
```

From: `/Users/jing/Documents/projects/tai/deps/timex/lib/timex.ex:1`

#### Context

```
defmodule Timex do
  @moduledoc File.read!("README.md")

  use Application

  @doc false
  def start(_type, _args) do
```

From: `/Users/jing/Documents/projects/tai/deps/timex/lib/timex.ex:0-6`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirAccessExpressionImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Do not know whether to inject Markdown in documentation
</summary>

```
java.lang.Throwable: Do not know whether to inject Markdown in documentation
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:47)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:22)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-10 15:25
Duplicate of #2771

**Closed by KronicDeth** 2022-09-10 15:25 UTC
