### ISSUE TITLE
ConcurrentModificationException at org.elixir_lang.structure_view.element.modular.Module.getChildren(Module.kt:46)

### ISSUE THREAD

**Issue by ihumanable** [KronicDeth/intellij-elixir#1494] opened 2019-05-29 18:31 UTC
# Version

3.10.0

# Description

Attempting to open up the File Structure menu in an elixir or elixir-script file (*.ex, *.exs) results in this error consistently.

# Exception

## Stacktrace

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at org.elixir_lang.structure_view.element.call_definition_by_name_arity.TreeElementList.putNew(TreeElementList.kt:49)
	at org.elixir_lang.structure_view.element.call_definition_by_name_arity.TreeElementList.addClausesToCallDefinition(TreeElementList.kt:31)
	at org.elixir_lang.structure_view.element.call_definition_by_name_arity.TreeElementList.addClausesToCallDefinition(TreeElementList.kt:25)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.childCallTreeElements(Module.kt:153)
	at org.elixir_lang.structure_view.element.modular.Module$Companion.callChildren(Module.kt:88)
	at org.elixir_lang.structure_view.element.modular.Module.getChildren(Module.kt:46)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:50)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:219)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:55)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:47)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.getChildren(StructureViewComponent.java:767)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:63)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:66)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:81)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:61)
	at com.intellij.ide.util.FileStructurePopup$1.rebuildTree(FileStructurePopup.java:153)
	at com.intellij.ide.util.FileStructurePopup.lambda$rebuildAndSelect$27(FileStructurePopup.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:68)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:153)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:91)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:320)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by KronicDeth** [comment] 2019-05-29 18:38
The version number doesn’t really make sense.  The current version of the plugin is 10.5.2.  What version of the plugin and IDE do you have installed?

**Comment by ihumanable** [comment] 2019-05-29 20:31
Oh yea, that's weird, it's just what pycharm autopopulated

![image](https://user-images.githubusercontent.com/122636/58588938-ab37dd80-8215-11e9-9995-65422d7ace34.png)

![image](https://user-images.githubusercontent.com/122636/58588976-bab72680-8215-11e9-87f6-047567227457.png)

This also appears to be a duplicate of https://github.com/KronicDeth/intellij-elixir/issues/1488 my apologies for not realizing.  

I was able to replicate this bug by creating a new project via

```console
mix new intellij_elixir_sample
```

I then opened it in PyCharm with the Elixir plugin versions above and went to the scaffold module `IntellijElixirSample` and attempted to view the File Structure, both from my keyboard shortcut and from using the Actions Popup and selecting the File Structure item, same stacktrace both times.

**Comment by ihumanable** [comment] 2019-05-31 13:58
@KronicDeth Please let me know if I can provide any additional information that may be of assistance.

**Comment by KronicDeth** [comment] 2019-06-02 14:53
I can reproducing using https://github.com/KronicDeth/intellij-elixir/issues/1494#issuecomment-497097777

**Comment by KronicDeth** [comment] 2019-06-02 14:56
I cannot reproduce in IntelliJ.  Weird that is something specific to PyCharm or the small IDEs, but maybe related to the difference in SDK or module representation.

**Comment by rossvz** [comment] 2019-08-19 14:04
Im getting this same error in Webstorm 2019.2 and IntelliJ IDEA Community 2019.2 (worked fine in webstorm in 2019.1)

**Comment by KronicDeth** [comment] 2019-09-20 14:54
Duplicate of #1488.

**Closed by KronicDeth** 2019-09-20 14:54 UTC
Labels: Kind:Bug
