### ISSUE TITLE
[auto-generated] Unhandled exception when typing code 

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#448] opened 2016-10-03 11:40 UTC
# Version

4.4.0

# Exception

## Message

Don't know how to resolve variable in match

### Excerpt

```
do
    matches? = ~s{This works!} == ~s[This works!]
    assert matches? == true
  end
```
 Line(s) 13-16

## Stacktrace

<details>
```
org.elixir_lang.errorreport.Logger.error(Logger.java:48)
org.elixir_lang.errorreport.Logger.error(Logger.java:31)
org.elixir_lang.psi.scope.Variable.execute(Variable.java:141)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarationsInPreviousSibling(ElixirPsiImplUtil.java:1644)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:1543)
org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:57)
com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1046)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:84)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
org.elixir_lang.reference.Callable.multiResolve(Callable.java:800)
org.elixir_lang.reference.Callable.resolve(Callable.java:824)
org.elixir_lang.annonator.Callable$1.visitCall(Callable.java:60)
org.elixir_lang.annonator.Callable$1.visitElement(Callable.java:48)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedNoArgumentsCallImpl.accept(ElixirMatchedUnqualifiedNoArgumentsCallImpl.java:41)
org.elixir_lang.annonator.Callable.annotate(Callable.java:39)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:334)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:269)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:293)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:268)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:434)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:427)
com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
</details>

**Comment by KronicDeth** [comment] 2016-10-10 03:42
I tried this:

```elixir
defmodule ModuleTest do
  test do
    matches? = ~s{This works!} == ~s[This works!]
    assert matches? == true
  end
end
```

and couldn't reproduce an error.  There are two reasons why the excerpt could not reproduce the error:

1) The error happens because of some interaction with code outside the `do` block that happens while typing.
2) The captured excerpt is a little past the point when the error occurs, so some earlier form actually caused the error.

If you can try cutting down the file and typing slowly to get a more precise reproduction case I can maybe fix this.

**Comment by KronicDeth** [comment] 2016-10-15 02:21
I changed the error reporter to always include the element class in #464, so hopefully that can pin this down if it happens again.  Closing for now until someone can reproduce.

**Closed by KronicDeth** 2016-10-15 02:21 UTC
Labels: bug, can't reproduce
