### ISSUE TITLE
Plugin keeps crashing Intellij, working on Pheonix Application

### ISSUE THREAD

**Issue by JamesReeseS2** [KronicDeth/intellij-elixir#2822] opened 2022-08-29 14:49 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Windows 10 (10.0)

# What I was doing

Just writing code

# Event

### Element

```
)
```

#### Context

```
    # ExAws.Config.new(:s3)
    # Duration.diff(Duration.now(), Duration)
    today = Timex.today()
    |> IO.inspect(label: "TODAY: ")

    Timex.shift*()


#    ExAws.S3.list_objects_v2(@map_bucket)
#    |> ExAws.request!
#    |> IO.inspect
```
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-08-29 14:52
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-08-29 14:52 UTC
