### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by jcfvalente** [KronicDeth/intellij-elixir#2832] opened 2022-09-03 07:46 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Community Edition (2022.2.1)
Operating System: Mac OS X (12.2.1)

# Event

### Element

```
end
```

From: `/Users/josevalente/git/elixir-course/servy/lib/servy/handler.ex:87`

#### Context

```
      403 => "Forbidden",
      404 => "Not Found",
      500 => "Internal Server Error",
    }[code]
  end
end

request = """
GET /wildthings HTTP/1.1
Host: example.com
User-Agent: ExampleBrowser/1.0
```

From: `/Users/josevalente/git/elixir-course/servy/lib/servy/handler.ex:82-92`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-10 15:00
Duplicate of #2774

**Closed by KronicDeth** 2022-09-10 15:00 UTC
