### ISSUE TITLE
credo | Edge could not be stripped from explanation line

### ISSUE THREAD

**Issue by eagle-te** [KronicDeth/intellij-elixir#1394] opened 2019-02-13 10:48 UTC
Exceptions occurs multiple times, after setting up credo in IntelliJ.

Plugin: v10.2.0
IntelliJ: 2018.3.4

# Exception

## Message

*** exception class was changed or removed

## Stacktrace

```
Edge could not be stripped from explanation line

`[0m[33m┃ [33m[2m  [F][0m Category: refactor [0m`


org.elixir_lang.credo.Annotator.stripEdge(Annotator.java:258)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
org.elixir_lang.credo.Annotator.explanationToToolTip(Annotator.java:406)
org.elixir_lang.credo.Annotator.lambda$apply$2(Annotator.java:382)
java.util.Optional.ifPresent(Optional.java:159)
org.elixir_lang.credo.Annotator.apply(Annotator.java:381)
org.elixir_lang.credo.Annotator.apply(Annotator.java:49)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.lambda$checkFileWithExternalAnnotator$1(ExternalAnnotatorInspectionVisitor.java:78)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:973)
com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.checkFileWithExternalAnnotator(ExternalAnnotatorInspectionVisitor.java:76)
org.elixir_lang.credo.inspection_tool.Local.checkFile(Local.kt:28)
com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:141)
com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$7(LocalInspectionsPass.java:316)
com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:315)
com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2022-05-20 15:29
Duplicate of #954

**Closed by KronicDeth** 2022-05-20 15:29 UTC
Labels: Kind:Bug
