### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2928] opened 2022-11-15 06:30 UTC
Duplicated with https://github.com/KronicDeth/intellij-elixir/issues/2817 . But with reproduction steps.

# How to reproduce

1. Write like bellow
2. Move caret to just after `@moduledoc """`.
3.  Press `enter`.

```elixir
defmodule Foo do
  @moduledoc """
  """
end
```

# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Mac OS X (12.6.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-16 20:28
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2817

**Closed by KronicDeth** 2022-12-16 20:28 UTC
