### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by swieckib** [KronicDeth/intellij-elixir#340] opened 2016-07-07 13:15 UTC
Given how advanced this plugin is, it would be great to add support for code formatting and make developers life easier.

I know there is a guide how to do it in house, but it would be nice to have it build-in same as in other IntelliJ plugins.

**Comment by KronicDeth** [comment] 2016-07-07 15:25
Duplicate of #98.  Please go 👍  the issue there, so the user vote count is correct.

**Closed by KronicDeth** 2016-07-07 15:25 UTC
Labels: duplicate, enhancement
