### ISSUE TITLE
InvalidMirrorException for jsx_decoder.beam

### ISSUE THREAD

**Issue by astavonintsc** [KronicDeth/intellij-elixir#1651] opened 2020-02-03 01:57 UTC
There are no reproduction steps. The issue is happening even I'm not touching IDE at all. 

# Exception

## Message

file:///Users/alex/projects/tsc_2_backend/.elixir_ls/build/test/lib/jsx/ebin/jsx_decoder.beam

## Stacktrace

```
org.elixir_lang.beam.psi.impl.ModuleElementImpl$InvalidMirrorException: stub:[org.elixir_lang.beam.psi.impl.CallDefinitionImpl@67c07a1b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7173327b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@69b82379, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@574b6989, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@33bfd1d9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5bb7cd3f, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@733c8edb, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7f37a614, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@324b8132, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@57706c71, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@40ad6a12, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2686315, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6c44207b, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@3803ca66, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@13d5da8e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5264732a, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1feec6e5, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@39187f84, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@424d383, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@75a80d0e, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@1c9834b0, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@66869cf8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@441ce360, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@71e95690, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2c89d1a9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7ebae99c, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5d1e02c8, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@6678922d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@41e13d2, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@2d41fcc4, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@64b3e6, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@22afa03d, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@565ba739, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@74ded6ea, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@5100a014, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@ef14c41, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@51840c9, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@7f3bf06, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@53a7bfec, org.elixir_lang.beam.psi.impl.CallDefinitionImpl@57b0629d]; mirror:[UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL, UNMATCHED_UNQUALIFIED_NO_PARENTHESES_CALL]
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:43)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.impl.ModuleImpl.setMirror(ModuleImpl.java:105)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirror(ModuleElementImpl.java:55)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:46)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.setMirrors(ModuleElementImpl.java:37)
	at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.java:633)
	at org.elixir_lang.beam.psi.BeamFileImpl$1.run(BeamFileImpl.java:606)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at org.elixir_lang.beam.psi.BeamFileImpl.getMirror(BeamFileImpl.java:604)
	at org.elixir_lang.beam.psi.impl.ModuleElementImpl.getMirror(ModuleElementImpl.java:125)
	at org.elixir_lang.beam.psi.impl.CallDefinitionImpl.getNavigationElement(CallDefinitionImpl.java:110)
	at org.elixir_lang.navigation.ChooseByNameContributor.getItemsByName(ChooseByNameContributor.kt:60)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$3(ContributorsBasedGotoByModel.java:196)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by KronicDeth** [comment] 2020-04-10 18:22
Duplicate of #1633.

**Closed by KronicDeth** 2020-04-10 18:22 UTC
Labels: Closed:Duplicate, Feature:Decompiler, Kind:Bug
