### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by newtechwave** [KronicDeth/intellij-elixir#2900] opened 2022-10-18 02:55 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by skanjo** [comment] 2022-10-18 20:27
I am having the same problem on Mac. It is rather random. Seems to be related to syntax highlighting.

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.6)

**Comment by mikeevstropov** [comment] 2022-10-24 04:54
Same here

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Kubuntu 22.04.1 LTS

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-01 19:31
Duplicate of #2817

**Comment by KronicDeth** [comment] 2022-12-01 19:32
@mikeevstropov thanks for such a concise reproduction case!

**Closed by KronicDeth** 2022-12-01 19:31 UTC
