### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by vicsstar** [KronicDeth/intellij-elixir#2910] opened 2022-10-28 01:59 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.2.3)
Operating System: Mac OS X (12.6)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-01 19:12
Duplicate of #2740

**Closed by KronicDeth** 2022-12-01 19:12 UTC
