### ISSUE TITLE
Syntax highlighting bug in module attributes

### ISSUE THREAD

**Issue by sbrother** [KronicDeth/intellij-elixir#625] opened 2017-02-23 04:54 UTC
![elixir bug](https://cloud.githubusercontent.com/assets/1652291/23245401/62fa8c04-f949-11e6-8d5a-122b8b5f5359.png)

The screenshot should explain the bug fairly well. Could this be something I'm doing wrong?

**Comment by KronicDeth** [comment] 2017-02-23 21:35
It looks like the String annotator is fighting with the Atom annotator, so the String color is being mis-applied to the wrong offsets.

**Comment by KronicDeth** [comment] 2017-02-24 04:58
@sbrother do you have a full length file that reproduces the error?  This may be related to #626, in which case it is fixed by #627.

**Comment by sbrother** [comment] 2017-02-24 05:14
@KronicDeth I just tried to reproduce it, and failed to, but found instead some other oddities which look like the symptoms you describe in #626. I guess you can go ahead and close this issue, and I'll test again once #627 is merged.

Thanks for your work on this; it's shaping up to be an awesome Elixir IDE.

**Closed** 2017-02-24 05:19 UTC
Labels: bug, duplicate
