### ISSUE TITLE
Credo annotator need to turn off ANSI color to override config

### ISSUE THREAD

**Issue by niku** [KronicDeth/intellij-elixir#1231] opened 2018-08-23 12:35 UTC
# Description

It seems that when credo annotater was enabled, it causes error.
I suspect color codes which is emitted by credo cause this error.
When I changed `color: true` to `color: false` in `config/.credo.exs`, it doesn't bring the error and it works well.

----

If you desire to reproduce this error, do following instructions:

1. Import the code https://github.com/niku/joque/commit/15a7f099eca16c34250dc617d814a371be89bfaf
2. Remove moduledoc in lib/joque/jobs.ex
3. Make credo annotater enable https://github.com/KronicDeth/intellij-elixir#enable
4. Run credo batch https://github.com/KronicDeth/intellij-elixir#batch-mode

Thank you.

# Exception

## Message

*** exception class was changed or removed

## Stacktrace

```
Edge could not be stripped from explanation line

`[0m[34m┃ [34m[2m  [R][0m Category: readability [0m`


org.elixir_lang.credo.Annotator.stripEdge(Annotator.java:258)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
org.elixir_lang.credo.Annotator.explanationToToolTip(Annotator.java:406)
org.elixir_lang.credo.Annotator.lambda$apply$2(Annotator.java:382)
java.util.Optional.ifPresent(Optional.java:159)
org.elixir_lang.credo.Annotator.apply(Annotator.java:381)
org.elixir_lang.credo.Annotator.apply(Annotator.java:49)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.lambda$checkFileWithExternalAnnotator$1(ExternalAnnotatorInspectionVisitor.java:76)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
com.intellij.codeInspection.ExternalAnnotatorInspectionVisitor.checkFileWithExternalAnnotator(ExternalAnnotatorInspectionVisitor.java:74)
org.elixir_lang.credo.inspection_tool.Local.checkFile(Local.kt:28)
com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)
com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:276)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:244)
com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1156)
com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:247)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:218)
com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:121)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2018-08-25 20:16
Yeah, I'll need to make the annotator turn off the colorization no matter what the config setting says.

**Comment by KronicDeth** [comment] 2022-05-20 15:30
Duplicate of #954

**Closed by KronicDeth** 2022-05-20 15:30 UTC
Labels: Kind:Bug
