### ISSUE TITLE
org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:80) ElixirParenthesesArgumentsImpl cannot be cast to ElixirList

### ISSUE THREAD

**Issue by GaryLCoxJr** [KronicDeth/intellij-elixir#1153] opened 2018-07-03 12:51 UTC
I was adding a table to a migration when this happened.  I wasn't doing anything special, just typing.

# Exception

## Message

Worker exited due to exception

## Stacktrace

```
java.lang.ClassCastException: org.elixir_lang.psi.impl.ElixirParenthesesArgumentsImpl cannot be cast to org.elixir_lang.psi.ElixirList
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:80)
	at org.elixir_lang.psi.ElementDescriptionProvider.getElementDescription(ElementDescriptionProvider.kt:38)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:30)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:71)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$8.getInfo(CtrlMouseHandler.java:565)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.c(CtrlMouseHandler.java:741)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3300(CtrlMouseHandler.java:670)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:716)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:949)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KronicDeth** [comment] 2018-07-29 15:14
Duplicate of #1136.

**Closed by KronicDeth** 2018-07-29 15:14 UTC
Labels: Kind:Bug
