### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by william-intelligencebank** [KronicDeth/intellij-elixir#2880] opened 2022-10-03 04:44 UTC
# System

Plugin Version: 13.2.0
Application: PhpStorm (2022.1.3)
Operating System: Mac OS X (12.6)

# Event

### Element

```
}
```

From: `/Users/william/Workspace/ib/web/apis/v3/profiler/profiler.ex:804`

#### Context

```
              "customItemNameSingle": "item",
              "alertType": "success"
          }
      }
  """
  def call(%Plug.Conn{query_params: query_params} = conn, "PUT", nil, id, params, %{"language" => language, :dbname => dbname} = opts) do
    with {:ok, verified_params} <- is_query_params_valid(
           query_params,
           valid_query_params_standard()
           |> valid_draft_query_param()
         ),
```

From: `/Users/william/Workspace/ib/web/apis/v3/profiler/profiler.ex:799-809`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-07 17:09
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-10-07 17:09 UTC
