### ISSUE TITLE
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found at org.elixir_lang.documentation.MarkdownFlavourDescriptor.<init>(MarkdownFlavourDescriptor.kt:21)

### ISSUE THREAD

**Issue by vincentopensourcetaiwan** [KronicDeth/intellij-elixir#3159] opened 2023-04-02 09:55 UTC
# System

Plugin Version: 14.0.0
Application: RubyMine (2023.1)
Operating System: Mac OS X (12.3.1)

# Event

## Message

Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@672d96dd, Dispatchers.Default]

### Stacktrace

<details>

<summary>
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found
</summary>

```
java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found
	at org.elixir_lang.documentation.MarkdownFlavourDescriptor.<init>(MarkdownFlavourDescriptor.kt:21)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.html(ElixirDocumentationProvider.kt:482)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.formatDocs(ElixirDocumentationProvider.kt:392)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:41)
```

</details>

**Comment by KronicDeth** [comment] 2023-04-07 21:11
Duplicate of #3150

**Closed by KronicDeth** 2023-04-07 21:11 UTC
