### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)

### ISSUE THREAD

**Issue by drl123** [KronicDeth/intellij-elixir#3195] opened 2023-04-26 11:16 UTC
Just started happening today (or at least just noticed...had been running 15.0.0 until yesterday).  I noticed that some of the syntax highlighting was not working in my test files.  I rolled back to 15.0.0 and restarted, same but complained about index not loaded.  Updated to 15.0.1 and index ran, but still got this error, but most of the syntax highlighting is working again, but not all.  The keywords like defmodule, describe, test, alias are not being highlighted.

![image](https://user-images.githubusercontent.com/568926/234559985-ba82b6f4-2678-41f5-83bf-68d631d2fbbb.png)

# System

Plugin Version: 15.0.1
Application: RubyMine (2023.1.1 Preview)
Operating System: Mac OS X (13.2.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
</summary>

```
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
	at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:63)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
```

</details>

**Comment by drl123** [comment] 2023-05-05 16:17
Somehow it stopped highlighting again, so I did `File > Invalidate Caches` and restarted and I seem to have most of the syntax highlighting back in tests now. Hope that helps track down what's going on.

**Comment by KronicDeth** [comment] 2023-05-06 05:08
Duplicate of #3158

**Closed by KronicDeth** 2023-05-06 05:08 UTC
