### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by JHoffmanME** [KronicDeth/intellij-elixir#2857] opened 2022-09-16 00:27 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Mac OS X (12.5.1)

# Event

### Element

```
}
```

From: `/Users/jhoffman/Projects/starlit/bedrock/lib/components/scripts/slate/add_ipropane_slate_app.ex:46`

#### Context

```
            with_url(
              nil,
              "?v={{api_version}}&user_key={{admin_user_key}}"
            ) do
              # extend environment
              with_env(%{admin_user_key: user_key}) do
                updating = get_from_env("updating", false)

                if not updating do
                  ##########
                  # Add an app instantiating the product for the tenant "wmop"
```

From: `/Users/jhoffman/Projects/starlit/bedrock/lib/components/scripts/slate/add_ipropane_slate_app.ex:41-51`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```
Details: /Users/jhoffman/Projects/starlit/bedrock/lib/components/scripts/slate/add_ipropane_slate_app.ex
defmodule Bedrock.Script.AddIPropaneSlateApp do
  use Bedrock.RESTMacros
  alias Bedrock.App

  require Logger

  defp environment() do
    %{
      ##### Tenant
      user_tenant_uri: "ipropane",
      tenant_label: "Independence Propane",
      #
      ##### Server location and admin login
      host: rest_host(),
      bedrock_host: bedrock_host(),
      api_version: "1.0",
      bedrock_tenant_uri: "bedrock",
      admin_id: bedrock_admin_id(),
      admin_password: bedrock_admin_password(),
      ############ PRODUCT
      #
      slate_product_id: "slate",
      slate_product_code_prefix: "Bedrock.Product.Slate",
      #
      ############ APP
      #
      slate_app_id: App.make_id("slate"),
      slate_app_code_prefix: ""
    }
    |> to_document()
  end

  # Expects 	%{updating: <boolean>} defaults to false
  def run(env_params) do
    rest_script do
      with_env(environment()) do
        with_env(env_params) do
          with_url("{{host}}/api/", "?v={{api_version}}") do
            # Login as root admin
            user_key = find_user_key(env_params)
            # keep set prefix
            with_url(
              nil,
              "?v={{api_version}}&user_key={{admin_user_key}}"
            ) do
              # extend environment
              with_env(%{admin_user_key: user_key}) do
                updating = get_from_env("updating", false)

                if not updating do
                  ##########
                  # Add an app instantiating the product for the tenant "wmop"
                  post(
                    "tenants/{{user_tenant_uri}}/apps",
                    %{
                      app: %{
                        id: "{{slate_app_id}}",
                        about: "Slate app for {{tenant_label}}",
                        product_id: "{{slate_product_id}}",
                        code_prefix: "{{slate_app_code_prefix}}"
                      }
                    }
                  )
                else
                  # Deactivate app
                  post("tenants/{{user_tenant_uri}}/apps/{{slate_app_id}}/deactivate", %{})
                end

                ### CHANGE ANYTHING UNDER HERE THAT NEEDS UPDATING
                post(
                  "tenants/{{user_tenant_uri}}/apps/{{slate_app_id}}/settings",
                  %{
                    settings: %{
                      logo: "https://app.myaccountplus.com/MyAccountPlusLogo.png",
                      site_name: "{{tenant_label}}",
                      show_fuel_ordering : true
                    }
                  }
                )

                # Update the apps config
                post(
                  "tenants/{{user_tenant_uri}}/apps/{{slate_app_id}}/config",
                  %{config: %{}}
                )

                # Activate app
                post("tenants/{{user_tenant_uri}}/apps/{{slate_app_id}}/activate", %{})
              end
            end
          end
        end
      end
    end
  end
end

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-16 16:29
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-09-16 16:29 UTC
