### ISSUE TITLE
java.lang.IllegalStateException: Seems you haven't called addPlace() at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)

### ISSUE THREAD

**Issue by argaghulamahmad** [KronicDeth/intellij-elixir#2906] opened 2022-10-27 04:39 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.1.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: Seems you haven't called addPlace()
</summary>

```
java.lang.IllegalStateException: Seems you haven't called addPlace()
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:217)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:149)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-16 20:27
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2817

**Closed by KronicDeth** 2022-12-16 20:27 UTC
