### ISSUE TITLE
Slight syntax breakage

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#513] opened 2016-11-14 14:59 UTC
using 4.6

note that `defp`, `if`, and `token` are all white

![image](https://cloud.githubusercontent.com/assets/89260/20269362/c6b68808-aa50-11e6-84fc-7a4983226b18.png)

```elixir
  defp _login(%User{} = u, password) do
    if checkpw(password, u.hashed_password) do
      user = u
      |> User.changeset(%{last_signed_in_at: Timex.now, token: user_token})
      |> Repo.update!

      {:ok, user}
    else
      {:error, :bad_pass}
    end
  end
```

This caused methods further down to file to break highlighting too, but as i tried to isolate the cause (through cut / paste) the highlighting came back

**Comment by KronicDeth** [comment] 2016-12-01 00:37
I'm can't reproduce this now on master, so I'm going to count this as related to the Timex issues fixed in #539.  Leave a comment and I'll reopen if it error recurs in `4.7.0` after it is released.

**Closed by KronicDeth** 2016-12-01 00:37 UTC
Labels: bug
