### ISSUE TITLE
3.0.1 has broken Elixir SDK support on Rubymine 8.0.1 (Build #RM 143.382)

### ISSUE THREAD

**Issue by aCandidMind** [KronicDeth/intellij-elixir#302] opened 2016-05-05 10:49 UTC
Elixir Plugin 3.0.1 is not finding any SDK automatically. Furthermore it can't pick up my manually set SDK and after indexing for a while it claims that no Project SDK is defined (Notification bar above every Elixir file: "Project SDK is not defined"). I can't define a SDK under the project settings. There's only `Other Settings -> Elixir External Tools` where I manually setup the SDK as mentioned above.

Also when clicking `New Project` there's no Elixir project type.

I have Syntax Highlighting but can't edit any code. It appears as if the keyboard wasn't working but is for Ruby files.

This is my very first step with Elixir and your Elixir plugin in general so bare with my if I missed some information.

My OS is Ubuntu 15.10.

Here's the Event Log:
```
12:31:32 IBus prior to 1.5.11 may cause input problems. See IDEA-78860 for details.
         Do not show again.
12:31:32 Platform and Plugin Updates: RubyMine is ready to update.
12:31:50 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/lib/test/repo.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:31:53 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/ecto/lib/ecto/repo/schema.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:31:55 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/ecto/lib/ecto/adapters/mysql.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:31:57 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/ecto/integration_test/support/migration.exs
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:03 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:09 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/poison/lib/poison/parser.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:10 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/gettext/lib/gettext/extractor_agent.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:13 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/phoenix/lib/phoenix/router/scope.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:16 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/phoenix/lib/phoenix/endpoint/cowboy_handler.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:17 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/phoenix/lib/phoenix/transports/serializer.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:21 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/phoenix/priv/templates/phoenix.gen.html/view.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:23 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/postgrex/lib/postgrex/extensions/int4.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:23 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/deps/phoenix_html/lib/phoenix_html/safe.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:24 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/test/support/conn_case.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:27 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:29 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/_build/dev/lib/test/priv/repo/seeds.exs
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:33 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/_build/dev/lib/phoenix/priv/templates/phoenix.gen.html/view.ex
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:35 NoSuchMethodError
         Error while indexing /home/bogn/dev/elixir/test/config/dev.exs
         To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:40 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:48 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:32:59 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:33:01 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:33:03 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:33:41 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:33:44 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:33:47 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:34:24 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:34:26 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:34:52 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:35:11 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:35:13 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:11 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:18 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:24 NoSuchMethodError: update failed for AnAction with ID=LocalHistory.ShowSelectionHistory: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:26 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:28 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:29 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:31 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:42 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:44 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:46 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:37:58 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:07 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:09 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:11 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:13 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:16 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:38:21 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:39:51 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:39:58 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:40:31 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:40:33 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:42:13 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:44:20 NoSuchMethodError: update failed for AnAction with ID=ExportToHTML: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:45:53 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:45:56 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
12:45:59 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
```

**Comment by KronicDeth** [comment] 2016-05-08 13:20
`NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z` is a duplicate of #293 and for some reason it is having the knock-on effect of breaking other parts of the plugin.

Try downgrading to 3.0.0 using the [download link on the JetBrains plugin repo}(https://plugins.jetbrains.com/plugin/download?pr=&updateId=24927) by first uninstalling the plugin:
1) Preferences > Plugins
2) Select Elixir
3) Click the Uninstall button
4) Click the Restart IntelliJ Elixir button that replaces the Uninstall button
5) Install the `intellij-elixir.zip` for 3.0.0 using [the instructions in the README](https://github.com/KronicDeth/intellij-elixir#in-ide).

**Closed** 2016-06-12 00:56 UTC
Labels: bug, duplicate

**Comment by kostin-a** [comment] 2016-07-28 14:27
Downgrade to 3.0.0 gives the same issue unfortunately: 
During open any *.ex file I have the following error:
```
16:34:12 NoSuchMethodError: update failed for AnAction with ID=Groovy.NewScript: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
16:34:43 NoSuchMethodError: update failed for AnAction with ID=Groovy.NewScript: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
16:35:07 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
16:35:10 NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z 
```

I have the following environment: 
IDEA version: 15.0.1
JRE: 1.8.45, 64-bit, 
Ubuntu 14.04

Could you please suggest solution?

**Comment by KronicDeth** [comment] 2016-07-28 14:48
@kostin-a this issue was closed by a PR (#323) was released (https://github.com/KronicDeth/intellij-elixir/commit/bd3c6541c0ef8bee46c5bc059f28a25aa3ceab50) in v4.0.0.  You should upgrade to V4.0.0 now.

**Comment by kostin-a** [comment] 2016-07-28 15:09
thank you, @KronicDeth !

Actually I started from v4.0.0 with the same error (then I followed instructions from this ticket):

# Version

4.0.0


# Exception


## Message

Error while indexing /home/andrey/Projects/elixir-test/r/erf.ex
To reindex this file IDEA has to be restarted: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z


## Stacktrace

```
java.lang.NoSuchMethodError: com.intellij.lang.parser.GeneratedParserUtilBase.nextTokenIsSmart(Lcom/intellij/lang/PsiBuilder;Lcom/intellij/psi/tree/IElementType;)Z
	at org.elixir_lang.parser.ElixirParser.unmatchedCaptureNonNumericOperation(ElixirParser.java:6219)
	at org.elixir_lang.parser.ElixirParser.unmatchedExpression(ElixirParser.java:6100)
	at org.elixir_lang.parser.ElixirParser.expression(ElixirParser.java:2162)
	at org.elixir_lang.parser.ElixirParser.expressionList(ElixirParser.java:2174)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1_0(ElixirParser.java:2047)
	at org.elixir_lang.parser.ElixirParser.elixirFile_1(ElixirParser.java:2038)
	at org.elixir_lang.parser.ElixirParser.elixirFile(ElixirParser.java:2023)
	at org.elixir_lang.parser.ElixirParser.parse_root_(ElixirParser.java:649)
	at org.elixir_lang.parser.ElixirParser.parseLight(ElixirParser.java:643)
	at org.elixir_lang.parser.ElixirParser.parse(ElixirParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:218)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getLastChild(SharedImplUtil.java:57)
	at com.intellij.psi.impl.source.PsiFileImpl.getLastChild(PsiFileImpl.java:789)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:938)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

**Comment by KronicDeth** [comment] 2016-07-28 15:21
@kostin-a 4.0.0 has the improved build process, but I guess it's not enough in your specific case.  I'm not sure what is going on.  I build way back in 14.1 and then use it in 2016.1.  Maybe something is only weird in 15.0?  I do have 15.0 installed locally, so I guess I'll need to test more in 15.0.  Do you have a sample elixir project on github that I can use to trigger your exact bug?

**Comment by kostin-a** [comment] 2016-07-28 15:51
@KronicDeth , sure. Pushed the test one:

[https://github.com/kostin-a/elxr](https://github.com/kostin-a/elxr)

**Comment by KronicDeth** [comment] 2016-09-02 03:40
kostin-a's issue is related to #391
