### ISSUE TITLE
Run, Debug and Make

### ISSUE THREAD

**Issue by mvbaffa** [KronicDeth/intellij-elixir#124] opened 2015-05-14 15:02 UTC
Hi,

I have just downloaded Elixir Plugin. Can you please give me the path to create a new Run configuration and make/compile the project.

I have Erlang and Erlang Plugin installed how can I Debug Elixir or attach the Erlang debugger and use it in my Elixir Project.

Thanks

**Comment by KronicDeth** [comment] 2015-05-15 15:28
I'm not sure how to add Run Configuration support off the top of my head.  I haven't looked into it yet, but #80 is already open to work on it as other users have requested it.  I would have to look at intellij-erlang to see which extension points are used for Run Configurations.

You should able to just open the intellij-elixir in IntelliJ and it will pick up the project configuration as it's committed to the repo.  You'll need to install some plugins and setup the SDK for your system as documented here: https://confluence.jetbrains.com/display/IDEADEV/Getting+Started+with+Plugin+Development. To check the SDKs and libraries are correct open File > Project Structure.  Click Project Settings > Project and ensure an IntelliJ SDK is the Project SDK.  Click Project Settings > Module.  Select intellij-elixir.  Go to the Dependencies tab.  Ensure that JInterface was found.  If it can't find JInterface go to Project Settings > Libraries > JInterface and add the path to OtpErlang.jar from your install of Erlang.  OtpErlang.jar is used by the tests to ensure that the parser in intellij-elixir generates the same quoted form as Elixir Code.string_to_quoted.

You'll also need intellij_elixir to run the tests.  You can get it from https://github.com/KronicDeth/intellij_elixir.  You'll need to do `mix release` to generate intellij_elixir/rel/intellij_elixir/bin/intellij_elixir.  Then Edit the Run configuration for JUnit > org.elixir_lang.  In "Before launch" select External tool 'External Tools/intellij_elixir release'.  Click the Pencil icon to edit.  The External Tools dialog will pop-up with intellij_elixir release selected.  Click Pencil again to edit.  In the Edit Tool dialog, Ensure the Program path is pointing to the `intellij_elixir/rel/intellij_elixir/bin/intellij_elixir` bin that exrm generated.

To make the project from IntellIJ you go to Build > Prepare Plugin Module 'intellij-elixir' For Deployment.  This will compile the plugin into a zip that you can install.  It's the same zip as on the Releases page here on github.  To run tests, there should be a Run Configuration called `org.elixir_lang` that runs all the junit tests. 
![screen shot 2015-05-15 at 10 18 45 am](https://cloud.githubusercontent.com/assets/298259/7655807/cbda9fc4-faeb-11e4-8fa3-36142ca3e77a.png)
 To debug the plugin, you run the `Elixir` Run Configuration in debug mode.  It has an electrical plug icon next to it. ![screen shot 2015-05-15 at 10 19 06 am](https://cloud.githubusercontent.com/assets/298259/7655822/dd637f04-faeb-11e4-9c42-9fe5335023db.png)


This is the [guide](https://confluence.jetbrains.com/display/IntelliJIDEA/Custom+Language+Support) I'm using for plugin development.  It doesn't cover run configurations.  Most of the work I do on this plugin is by reading the source for [IntelliJ Community](https://github.com/JetBrains/intellij-community) and other plugins like [intellij-erlang](https://github.com/ignatov/intellij-erlang) and [intellij-plugins](https://github.com/JetBrains/intellij-plugins).  I also launch intellij-erlang and intellij-community in the debugger inside Intellij itself so I can look up the stack to see how stuff is done.  In general, the documentation for writing plugins isn't that great, but a lot of the source is open and the source that isn't open is disassembled by IntelliJ's own disassembler, so given enough time you can figure out how you're supposed to add an extension.

After I finish the current issue I'm working on, I'll try to clean this up and add it to CONTRIBUTING.  Thanks for helping on this.

**Comment by mvbaffa** [comment] 2015-05-15 20:02
There is not mix.exs in the project directory

**Comment by mvbaffa** [comment] 2015-05-15 20:07
You'll need to do mix release. There is no mix.exs in the project directory

**Comment by KronicDeth** [comment] 2015-05-17 22:52
Hyphen (`-`) vs underscore (`_`) matters.  This project uses a hyphen in its name.  The Elixir project used for testing this project uses an underscore in its name.  When I said run `mix release`, that was in the Elixir project, https://github.com/KronicDeth/intellij_elixir, which has a [mix.exs](https://github.com/KronicDeth/intellij_elixir/blob/master/mix.exs).  I'm sorry if my phrasing was unclear in my last comment.

**Comment by williamgueiros** [comment] 2015-06-27 03:15
Do you have more information about debugging, and how I can help you to add debugger?

**Comment by mvbaffa** [comment] 2015-06-28 12:16
Sorry but I am very busy this days. I will not be able, for some time, to
continue this work.
Em 27/06/2015 00:15, "william de melo gueiros" <notifications@github.com>
escreveu:

Do you have more information about debugging, and how I can help you to add
debugger?

—
Reply to this email directly or view it on GitHub
<https://github.com/KronicDeth/intellij-elixir/issues/124#issuecomment-115948833>
.

**Comment by KronicDeth** [comment] 2017-07-08 02:00
* Run
  * #167 added `mix` task Run Configurations
  * #482 improved Run Configurations, adding more configuration options and enable Mix ExUnit configurations for running `mix test` with a formatter that shows results graphically.
* Debug
  * #643 added a graphical debugging option when using `Mix ExUnit` run configurations

#643 was merged as 0136fd4c03369d60dc786651faf2722ffb4e1ac1 and released in [v5.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v5.1.0), so that completes the originally requested feature.

If you like additional features for Run or Debug or there are bugs with the features as implemented, please open new issue(s)

**Closed by KronicDeth** 2017-07-08 02:00 UTC
Labels: enhancement

**Comment by albertortizl** [comment] 2017-09-16 21:44
Hi, do you have any plans on add capabilities to debug exs? I can't do that, so I can't debug Exunit files

**Comment by KronicDeth** [comment] 2017-09-17 00:24
I think the problem is that @JakeBecker explained that the current system depends on having a `.beam` file on file system to debug it, but the actually debugging is just using the module name, so there's nothing stopping it from working on `.exs` files, we'd just have to extend the interface to the script to allow passing module names that can't be scanned in from the file system.

**Comment by JakeBecker** [comment] 2017-09-18 20:20
I wrote about some of the issues with debugging exs files in this blog post: https://medium.com/@JakeBeckerCode/debugging-elixir-in-vs-code-400e21814614

To summarize, the things that need to happen are:

1. Require the .exs files prior to interpreting modules
2. For each module that was loaded when requiring the .exs files, actually write the beam file to somewhere in the code path, since `:int.ni/1` will refuse to interpret them if it can't find their beam file
3. Interpret the modules

In my VS Code plugin, the default test configuration does this for "test/**/test_helper.exs" and "test/**/*_test.exs" prior to running the test task. Code for that is here: https://github.com/JakeBecker/elixir-ls/blob/master/apps/debugger/lib/debugger/server.ex#L508 .  You're welcome to reuse it in IntelliJ Elixir.

**Comment by av-miller** [comment] 2022-12-14 16:29
> I think the problem is that @JakeBecker explained that the current system depends on having a `.beam` file on file system to debug it, but the actually debugging is just using the module name, so there's nothing stopping it from working on `.exs` files, we'd just have to extend the interface to the script to allow passing module names that can't be scanned in from the file system.

I'd love to add support for debugging `.exs` file. Please points me where to start and I can create a PR for that.
