### ISSUE TITLE
Syntax coloring and IntelliJ Sense not working with Phoenix templates

### ISSUE THREAD

**Issue by musialny** [KronicDeth/intellij-elixir#2927] opened 2022-11-14 17:17 UTC
**Describe the bug**
Syntax coloring and IntelliJ Sense not working with Phoenix templates (and those from Surface Components) 

**To Reproduce**
Opening project?

**Screenshots**
![image](https://user-images.githubusercontent.com/38112820/201723637-5f2cede1-fdee-4f6c-a744-9792b0b8b488.png)

**Desktop:**
 - OS: Fedora Linux
 - Version: 36

**Erlang:**
- Installer: dnf
- Version 12.3.2.6

**Elixir:**
- Installer: dnf
- Version: Elixir 1.14.1

**Plugin:**
- Version: 13.2.1

**Comment by KronicDeth** [comment] 2023-01-06 18:24
Duplicate of #2102

**Closed by KronicDeth** 2023-01-06 18:24 UTC
