### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by pfazzi** [KronicDeth/intellij-elixir#2866] opened 2022-09-23 15:00 UTC
# System

Plugin Version: 13.2.0
Application: PhpStorm (2022.2.1)
Operating System: Mac OS X (12.6)

# Event

### Element

```
end
```

From: `/Users/patrickfazzi/Prima/roger/deps/prima_auth0_ex/lib/prima_auth0_ex/plug/verify_and_validate_token.ex:111`

#### Context

```
      do:
        :prima_auth0_ex
        |> Application.get_env(:server, [])
        |> Keyword.get(:missing_auth_header_log_level, :warn)
  end
end

```

From: `/Users/patrickfazzi/Prima/roger/deps/prima_auth0_ex/lib/prima_auth0_ex/plug/verify_and_validate_token.ex:106-112`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-01 19:16
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-10-01 19:16 UTC
