### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os in WebStorm 2020.2

### ISSUE THREAD

**Issue by iamsteeve** [KronicDeth/intellij-elixir#1813] opened 2020-08-24 21:40 UTC
# Exception
in the .exs files that I use for tests the elixir syntax is not complete and throws this exception in

-  **webstorm 2020.2** 
- **elixir 1.9.4**
- **mac os catalina 10.15.5**
- **plugin version 11.8.0**

## Stacktrace

```
java.lang.NoClassDefFoundError: org/codehaus/plexus/interpolation/os/Os
	at org.elixir_lang.exunit.ExUnitLineMarkerProvider.getInfo(TestLineMarkerProvider.kt:60)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:53)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

<img width="866" alt="Captura de Pantalla 2020-08-24 a la(s) 16 38 41" src="https://user-images.githubusercontent.com/33048029/91099086-50638080-e628-11ea-9e39-d5c30cb73a73.png">

**Comment by KronicDeth** [comment] 2020-09-26 02:01
`org/codehaus/plexus/interpolation/os/Os` is a class path supplied by JetBrains, so they must have changed the dependency out in newer versions of the IDEs.

**Comment by iamsteeve** [comment] 2020-09-30 13:17
@KronicDeth What version of webstorm do you recommend so that this does not happen? :D

**Comment by KronicDeth** [comment] 2020-09-30 13:26
I have not looked at when the change occurred.  If you install JetBrains Toolbox, it will let you easily install old versions of the IDEs and you can try earlier versions.

**Comment by KronicDeth** [comment] 2023-05-06 05:07
Duplicate of #3158

**Closed by KronicDeth** 2023-05-06 05:07 UTC
Labels: Kind:Bug
