### ISSUE TITLE
Could not initialize class org.elixir_lang.ElixirLanguage at org.elixir_lang.templates.ElixirContextType.isInContext(ElixirContextType.java:20)

### ISSUE THREAD

**Issue by joshzinny** [KronicDeth/intellij-elixir#2121] opened 2021-10-04 15:45 UTC
# Exception

## Message

update failed for AnAction(com.intellij.codeInsight.generation.actions.SurroundWithAction, id=SurroundWith) with text=Surround With...

## Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.ElixirLanguage
	at org.elixir_lang.templates.ElixirContextType.isInContext(ElixirContextType.java:20)
	at com.intellij.codeInsight.template.TemplateContextType.isInContext(TemplateContextType.java:69)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.getDirectlyApplicableContextTypes(TemplateManagerImpl.java:482)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.getApplicableContextTypes(TemplateManagerImpl.java:574)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableTemplates(TemplateManagerImpl.java:544)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableTemplateWithInsertingDummyIdentifier(TemplateManagerImpl.java:559)
	at com.intellij.codeInsight.generation.actions.SurroundWithAction.isValidForFile(SurroundWithAction.java:40)
	at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:103)
	at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:108)
	at com.intellij.codeInsight.actions.CodeInsightAction.update(CodeInsightAction.java:99)
	at com.intellij.codeInsight.actions.BaseCodeInsightAction.update(BaseCodeInsightAction.java:89)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:113)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:414)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:394)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$25(ActionUpdater.java:393)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1483)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:393)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:230)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:305)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:301)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$19(ActionUpdater.java:300)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$20(ActionUpdater.java:298)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KronicDeth** [comment] 2023-01-25 03:53
Duplicate of #2116

**Closed by KronicDeth** 2023-01-25 03:53 UTC
Labels: Kind:Bug
