### ISSUE TITLE
Should look for Elixir SDK in /usr and /usr/local on Unix

### ISSUE THREAD

**Issue by derekmorr** [KronicDeth/intellij-elixir#141] opened 2015-06-25 00:33 UTC
On Unix (but maybe not OS X), the plugin should look for Elixir SDK(s) in /usr and /usr/local

**Comment by KronicDeth** [comment] 2015-06-26 22:42
Unless I setup a VM, I don't have access to an Elixir install on any Linux since I develop on OSX.  I need to full path, or pattern (like where is the wild-card for the Elixir and/or Erlang version)?

For example, on OSX, I search in `/usr/local/Cellar/elixir/<version>` for Homebrew installs and confirm the install by looking for `/usr/local/Cellar/elixir/<version>/bin/elixir`, `/usr/local/Cellar/elixir/<version>/bin/elixirc`, `/usr/local/Cellar/elixir/<version>/bin/iex`, `/usr/local/Cellar/elixir/<version>/bin/mix`.  I assume that the libraries for Elixir are under `/usr/local/Cellar/elixir/<version>/lib/<name>/ebin`, so for your install on Linux

1. What would be the bin dir for `elixir`, `elixirc`, `iex`, and `mix`?
2. What lib directory contains the <name>/ebin directories for `eex`, `elixir`, `ex_unit`, `iex`, `logger`, and `mix`?

**Comment by derekmorr** [comment] 2015-06-27 01:05
I installed Elixir via the packages on Erlang Solutions using the instructions at 
https://www.erlang-solutions.com/downloads/download-elixir

That installs elixir, elixirc, iex, and mix in /usr/local/bin.

The ebin directories are in /usr/local/lib/elixir/lib/<name>/ebin.

**Comment by KronicDeth** [comment] 2015-11-05 00:28
This looks implemented by #188, which has been released in [v1.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v1.2.0) today.  Let me know if it doesn't fix this issue for you and I'll reopen.

**Closed by KronicDeth** 2015-11-05 00:28 UTC
Labels: enhancement

**Comment by bangbambang** [comment] 2016-11-27 18:16
@KronicDeth could you please reopen the issue? #188 check SDK path at `/usr/local/lib/elixir`, but on some distro, the binary isn't exist/symlinked to that path. I can confirm that on my system ([Archlinux](https://www.archlinux.org/packages/community/any/elixir/files/)) and 2 others ([Ubuntu](http://packages.ubuntu.com/xenial/amd64/elixir/filelist), [Debian](https://packages.debian.org/sid/all/elixir/filelist)) the binary is located either at `/usr/bin` or `usr/lib/elixir/bin/`. [Fedora](https://apps.fedoraproject.org/packages/elixir/contents/#) only use `/usr/bin`.

**Comment by cocodrino** [comment] 2018-10-13 02:53
guys when I search for a folder named elixir on arch I get

```
/usr/share/licenses/elixir
/usr/lib/elixir
/usr/lib/elixir/lib/elixir
/run/media/me/95936a51-3671-4a9d-9567-5059c3a086db/home/yo/.vim/bundle/syntastic/syntax_checkers/elixir

and for elixir and elixirrc

[me@me-pc sqliteauth]$ whereis elixir
elixir: /usr/bin/elixir /usr/lib/elixir /usr/share/man/man1/elixir.1.gz
[me@me-pc sqliteauth]$ whereis elixirc
elixirc: /usr/bin/elixirc /usr/share/man/man1/elixirc.1.gz


```


but I've tried all these folders and intellij always tell me that it's not a valid path, just a question, what files must have the elixir sdk path and the erlang sdk path???...thank you
