### ISSUE TITLE
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.configurable.Project;, specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: org.elixir_lang] at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)

### ISSUE THREAD

**Issue by ShawnMcCool** [KronicDeth/intellij-elixir#3364] opened 2023-09-23 10:24 UTC
# System

Plugin Version: 16.0.0
Application: PhpStorm (2023.2.1)
Operating System: Linux (6.1.51)

# Event

### Stacktrace

<details>

<summary>
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.configurable.Project;
</summary>

```
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.elixir_lang.facet.configurable.Project;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: org.elixir_lang]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.openapi.options.ex.Weighted.lambda$static$0(Weighted.java:26)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:221)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:41)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:148)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:110)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:119)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.showSettingsDialog(ShowSettingsUtilImpl.kt:77)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.showSmallIDEFacetSettings(Provider.kt:78)
	at org.elixir_lang.notification.setup_sdk.Provider$Companion.createSmallIDEFacetPanel$lambda$1$lambda$0(Provider.kt:86)
	at com.intellij.ui.EditorNotificationPanel$6.handlePanelActionClick(EditorNotificationPanel.java:442)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel$1.hyperlinkActivated(EditorNotificationPanel.java:487)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:14)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:242)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:164)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
```

</details>

**Comment by KronicDeth** [comment] 2023-10-06 00:04
Duplicate of #3349

**Closed by KronicDeth** 2023-10-06 00:04 UTC
