### ISSUE TITLE
Don't know how to find variable use scope for `else` block

### ISSUE THREAD

**Issue by pcmarks** [KronicDeth/intellij-elixir#492] opened 2016-11-06 14:27 UTC
# Version

4.2.0

windows 7

IntelliJ IDEA 2016.2.4

# Description

I had just did a backspace to delete a character in a typo. 

I don't know if it makes any difference but I had left IntelliJ ope overnight and this was the first edit that I performed the following morning.

Peter

# Exception

## Message

Don't know how to find variable use scope for 

### Excerpt

```
else
        fn(f1) -> R.chunk(n, step, limit, f1) end,
        &do_chunk(&1, n, leftwover, &2)

```
 Line(s) 518-521

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:48)
org.elixir_lang.errorreport.Logger.error(Logger.java:31)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:680)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:667)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:667)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:576)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:674)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:576)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:674)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:667)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:667)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:667)
org.elixir_lang.reference.Callable.variableUseScope(Callable.java:382)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.getUseScope(ElixirPsiImplUtil.java:2303)
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.getUseScope(ElixirUnmatchedUnqualifiedNoArgumentsCallImpl.java:89)
com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:79)
com.intellij.psi.searc

**Comment by KronicDeth** [comment] 2016-11-29 03:18
I think this is a duplicate of #429  and so was fixed by #434

**Closed by KronicDeth** 2016-11-29 03:18 UTC
Labels: bug
