### ISSUE TITLE
Don't know how to check if ElixirVariable is variable

### ISSUE THREAD

**Issue by ciroque** [KronicDeth/intellij-elixir#657] opened 2017-03-30 15:51 UTC
# Version

4.7.0

# Exception

## Message

Don't know how to check if variable

### Excerpt

```
attrs
```
 Line(s) 68-68

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirVariableImpl
```

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:51)
org.elixir_lang.errorreport.Logger.error(Logger.java:34)
org.elixir_lang.reference.Callable.error(Callable.java:336)
org.elixir_lang.reference.Callable.isVariable(Callable.java:285)
org.elixir_lang.code_insight.lookup.element_renderer.Variable.color(Variable.java:103)
org.elixir_lang.code_insight.lookup.element_renderer.Variable.renderElement(Variable.java:54)
com.intellij.codeInsight.lookup.LookupElementBuilder.renderElement(LookupElementBuilder.java:396)
com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:149)
com.intellij.codeInsight.lookup.impl.LookupImpl.a(LookupImpl.java:433)
com.intellij.codeInsight.lookup.impl.LookupImpl.c(LookupImpl.java:410)
com.intellij.codeInsight.lookup.impl.LookupImpl.refreshUi(LookupImpl.java:1105)
com.intellij.codeInsight.lookup.impl.LookupImpl.appendPrefix(LookupImpl.java:324)
com.intellij.codeInsight.lookup.impl.LookupTypedHandler.a(LookupTypedHandler.java:120)
com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:84)
com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1167)
com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1.run(TypedAction.java:171)
com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler.lambda$execute$0(TypedAction.java:165)
com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler.execute(TypedAction.java:159)
com.intellij.openapi.editor.impl.EditorFactoryImpl$MyTypedHandler.execute(EditorFactoryImpl.java:287)
com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:142)
com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:42)
com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:142)
com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1114)
com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:1102)
com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3115)
com.intellij.openapi.editor.impl.EditorImpl$6.keyTyped(EditorImpl.java:937)
java.awt.Component.processKeyEvent(Component.java:6496)
javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
java.awt.Component.processEvent(Component.java:6318)
java.awt.Container.processEvent(Container.java:2236)
java.awt.Component.dispatchEventImpl(Component.java:4897)
java.awt.Container.dispatchEventImpl(Container.java:2294)
java.awt.Component.dispatchEvent(Component.java:4719)
java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
java.awt.Component.dispatchEventImpl(Component.java:4768)
java.awt.Container.dispatchEventImpl(Container.java:2294)
java.awt.Window.dispatchEventImpl(Window.java:2746)
java.awt.Component.dispatchEvent(Component.java:4719)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
java.awt.EventQueue.access$500(EventQueue.java:98)
java.awt.EventQueue$3.run(EventQueue.java:715)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
java.awt.EventQueue$4.run(EventQueue.java:737)
java.awt.EventQueue$4.run(EventQueue.java:735)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:634)
com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KronicDeth** [comment] 2017-04-11 02:15
Duplicate of #555.  Fixes by #612.  Wait for next release.

**Closed by KronicDeth** 2017-04-11 02:15 UTC
Labels: bug, duplicate
