### ISSUE TITLE
Compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by Deni7777** [KronicDeth/intellij-elixir#1870] opened 2021-01-11 18:38 UTC
# Version

11.9.0

# What I was doing

I don't know what I was doing

# Exceptions

### Stacktrace

```
com.intellij.diagnostic.PluginException: While loading class org.elixir_lang.sdk.elixir.Type: org/elixir_lang/sdk/elixir/Type has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: org.elixir_lang]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:80)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:401)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:232)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at com.intellij.openapi.projectRoots.SdkType.getAllTypes(SdkType.java:234)
	at com.

**Comment by KronicDeth** [comment] 2021-01-15 04:10
Duplicate of #1872

**Comment by KronicDeth** [comment] 2021-01-15 04:10
This is older, but #1872 had more details.

**Closed by KronicDeth** 2021-01-15 04:10 UTC
Labels: Kind:Bug:Regression
