### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by SeriousSamV** [KronicDeth/intellij-elixir#2925] opened 2022-11-11 21:28 UTC
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Linux (5.19.0-23-generic)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by KronicDeth** [comment] 2022-12-01 19:13
Duplicate of #2740

**Closed by KronicDeth** 2022-12-01 19:13 UTC
