### ISSUE TITLE
StackOverflowError when annotating Call at org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)

### ISSUE THREAD

**Issue by andreact** [KronicDeth/intellij-elixir#1609] opened 2019-10-22 01:37 UTC
# Version

3.5.0.1

# Exception

## Message

*** exception class was changed or removed

## Stacktrace

```
StackOverflowError when annotating Call

### Excerpt

```
use ExMachina.Ecto, repo: Database.Repo
```
 Line(s) 1-1 in /home/andrea/Projects/kommit/GiveProgram/Bankommit/bankommit/apps/database/test/support/factory.ex


### Element Class Name

```
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl
```


org.elixir_lang.errorreport.Logger.error(Logger.java:51)
org.elixir_lang.errorreport.Logger.error(Logger.java:34)
org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:25)
org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:14)
com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:593)
org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:585)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:583)
org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
org.elixir_lang.reference.Callable.multiResolve(Callable.kt:106)
org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:98)
org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:87)
org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:47)
org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:78)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
org.elixir_lang.annotator.Callable.annotate(Callable.kt:39)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:353)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:286)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:313)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:316)
com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:316)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:316)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:316)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:283)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2019-11-08 15:13
@andreact is this using `ExMachina`?

**Comment by KronicDeth** [comment] 2021-06-29 15:58
Duplicate of #1513

**Closed by KronicDeth** 2021-06-29 15:58 UTC
Labels: Kind:Bug, Note:Waiting on Feedback
