### ISSUE TITLE
java.lang.IllegalStateException: seed must not be null at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)

### ISSUE THREAD

**Issue by rubin55** [KronicDeth/intellij-elixir#2801] opened 2022-08-20 09:08 UTC
# System

Plugin Version: 13.2.0
Application: CLion (2022.2.1)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
java.lang.IllegalStateException: seed must not be null
</summary>

```
java.lang.IllegalStateException: seed must not be null
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions(PsiElementImpl.kt:220)
	at org.elixir_lang.psi.impl.PsiElementImplKt.childExpressions$default(PsiElementImpl.kt:213)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

This happened after I created a new file, named it `runtime.exs` and pasted the following into it:

```elixir
import Config
# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
```

**Comment by KronicDeth** [comment] 2022-08-20 11:51
Duplicate of #2773

**Closed by KronicDeth** 2022-08-20 11:51 UTC
