### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here. at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)

### ISSUE THREAD

**Issue by bhjakobsen** [KronicDeth/intellij-elixir#3065] opened 2023-02-11 10:36 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.2)
Operating System: Mac OS X (13.1)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here.
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here.
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:145)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

**Comment by KronicDeth** [comment] 2023-02-21 22:17
Duplicate of #2904

**Closed by KronicDeth** 2023-02-21 22:17 UTC

**Comment by KronicDeth** [comment] 2023-03-17 18:08
https://github.com/KronicDeth/intellij-elixir/blob/965b94b3df226f4323d6bde46bf03838b9b6c919/src/org/elixir_lang/injection/markdown/Injector.kt#L64-L150
