### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by joetjen** [KronicDeth/intellij-elixir#2824] opened 2022-08-30 09:44 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Mac OS X (12.5.1)

# Event

### Element

```
,
```

From: `/Users/jan.oetjen/IdeaProjects/elixir/thor/apps/listener/lib/listener/broker.ex:37`

#### Context

```

  def handle_event(%{user: id}, _meta) when id != "2@15002036" do
    # ignore user
  end

  def handle_event(%{type: "user.online", user: id}, #{_meta) do
    User.update_state(id, :chat, :online)
  end

  def handle_event(%{type: "user.idle", user: id}, _meta) do
    User.update_state(id, :chat, :idle)
```

From: `/Users/jan.oetjen/IdeaProjects/elixir/thor/apps/listener/lib/listener/broker.ex:32-42`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-10 15:00
Duplicate of #2774

**Closed by KronicDeth** 2022-09-10 15:00 UTC
