### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by dog-64** [KronicDeth/intellij-elixir#1082] opened 2018-04-17 20:20 UTC
# Version

7.4.0

# Exception

## Message

Access is allowed from event dispatch thread only.

## Stacktrace

```
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@6fed7f7a Current thread: Thread[ApplicationImpl pooled thread 1562,4,Idea Thread Group] 345860701 SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1099626969

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:66)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:477)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1096)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1085)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3104)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:333)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:207)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:182)
	at org.elixir_lang.beam.chunk.code.NamespaceKt.editorComponent(namespace.kt:24)
	at org.elixir_lang.beam.chunk.code.NamespaceKt.component(namespace.kt:16)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:79)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:38)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:88)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KronicDeth** [comment] 2018-05-20 19:14
Duplicate of #1031.

**Closed by KronicDeth** 2018-05-20 19:14 UTC
