### ISSUE TITLE
Mix UnicodeConversionError ?

### ISSUE THREAD

**Issue by rogeralsing** [KronicDeth/intellij-elixir#192] opened 2015-10-14 15:42 UTC
This might be me who just doesnt know what Im doing, but I'm getting the following error when compliling on Windows:

```
C:\tools\Elixir\bin\elixir.bat C:/Users/ralsing/IdeaProjects/untitled12/mix ""
** (UnicodeConversionError) invalid encoding starting at <<150, 14, 161, 70, 186, 65, 5, 62, 50, 11, 0, 0, 12, 14, 0, 0, 16, 0, 0, 0, 109, 105, 120, 95, 101, 115, 99, 114, 105, 112, 116, 46, 98, 101, 97, 109, 125, 86, 9, 88, 19, 215, 22, 158, 100, 66, 18, 194, 54, 73, ...>>
    (elixir) lib/string.ex:1351: String.to_char_list/1
    (elixir) lib/code.ex:307: Code.require_file/2
```

**Comment by KronicDeth** [comment] 2015-10-15 00:52
Those are exceptions from elixir itself, not from the IDE or this plugin.  Why do you think this is a bug with the plugin?  Does the code run outside the IDE, but only give this error when run from the IDE?

**Comment by rogeralsing** [comment] 2015-10-15 13:18
What I have done is to:
Install the Elixir plugin
Create a new Elixir project
Added a new elixir file (I have tried all of the different file templates, empty, application etc)
When trying to start this, the above is the exception that I am seeing,

Since all of the files was created via the plugin as far as I understand, thus I assume there is some problem in the plugin not setting things up correctly(?)

**Comment by zyuyou** [comment] 2015-10-15 16:54
@rogeralsing how did you exec the command? and can you show the elixir file's content? I think it would be helpful for checking the plugin.

**Comment by KronicDeth** [comment] 2016-03-07 14:17
The `mix ""` portion may be related to #249

**Comment by KronicDeth** [comment] 2016-03-15 17:04
[Posted](https://groups.google.com/forum/#!topic/elixir-lang-talk/W2HrrZ7VMcM) to [elixir-lang-talk](https://groups.google.com/forum/#!forum/elixir-lang-talk) to see if anyone has fixed `UnicodeConversionError` elsewhere

**Comment by antani** [comment] 2016-03-15 17:06
The content of Elixir file:

    defmodule Hello do
      @moduledoc false
      IO.puts "Hello World"
    end

**Comment by KronicDeth** [comment] 2016-03-15 17:46
@antani what is the value of the following variables in the shell where `mix` works?  

* `LANG`
* `LANGUAGE`
* `LC_CTYPE`
* `LC_ALL`

Maybe IntellIJ doesn't have the same locale/language environment variables to pass to the runner process, so it is misinterpreting the on-disk encoding and trying to convert when it shouldn't.

**Comment by antani** [comment] 2016-03-15 18:36
» echo $LANG 
    C

    » echo $LANGUAGE

    » echo $LC_CTYPE
    UTF-8

    » echo $LC_ALL

**Comment by KronicDeth** [comment] 2016-03-15 18:46
I have `LC_CTYPE` as `en_US.UTF-8`, but I would think once it's in UTF-8, it doesn't matter what the language and country code are.  If it wasn't UTF-8 then the code page might matter.

Either in the file you showed me, or some other file in the project or your Elixir libraries you have a file with a 150 byte, which is outside of ASCII, so it would indicate that a different code page/encoding was used to write that file.  I'll need to find some system command to search for that file.

**Comment by KronicDeth** [comment] 2016-08-12 01:54
Closing as can't reproduce for now to groom the backlog.  Please leave new comments if you get any new information to help reproduce.

**Closed by KronicDeth** 2016-08-12 01:54 UTC
Labels: bug, can't reproduce
