### ISSUE TITLE
[auto-generated]

### ISSUE THREAD

**Issue by zoltanmaric** [KronicDeth/intellij-elixir#1070] opened 2018-04-06 08:47 UTC
# Version

7.4.0

# Exception

## Message

Access is allowed from event dispatch thread only.

## Stacktrace

```
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@18d52173 Current thread: Thread[ApplicationImpl pooled thread 11,4,Idea Thread Group] 235615439 SystemEventQueueThread: Thread[AWT-EventQueue-0 2018.1#IU-181.4203.550 IDEA, eap:false, os:Linux 4.13.0-38-generic, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b20,6,Idea Thread Group] 1447205968

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:66)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:477)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1096)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1085)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3106)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:333)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:207)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:182)
	at org.elixir_lang.beam.chunk.elixir_documentation.Panel.<init>(Panel.kt:23)
	at org.elixir_lang.beam.chunk.elixir_documentation.Splitter.<init>(Splitter.kt:13)
	at org.elixir_lang.beam.chunk.elixir_documentation.NamespaceKt.component(namespace.kt:11)
	at org.elixir_lang.beam.FileEditor.addTab(FileEditor.kt:83)
	at org.elixir_lang.beam.FileEditor.getComponent(FileEditor.kt:38)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:88)
	at com.intellij.lang.javascript.linter.JSLinterEditorNotificationPanel.createNotificationPanel(JSLinterEditorNotificationPanel.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by zoltanmaric** [comment] 2018-04-06 08:48
I didn't notice any issues, it's just something that IntelliJ reported with a blinking red exclamation mark in the bottom-left corner.

**Comment by KronicDeth** [comment] 2018-04-09 02:06
Duplicate of #1039. Subscribe to that issue.

**Closed by KronicDeth** 2018-04-09 02:06 UTC
