### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by NicolasLook** [KronicDeth/intellij-elixir#2852] opened 2022-09-13 06:00 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Linux (5.15.0-47-generic)

# Event

## Message

I'm just reporting this because Intellij told me so a couple of times now. All the context below is auto generated. It seems that there might be a problem with reading doc strings. I don't know if this is indicative of a bug or if Intellij detected something falsely. Anyhow, thank's for the great plugin and have a nice day. Cheers

### Context

```
    nameList
    |> Task.async_stream(&{&1, searchPattern(open, close, high, low, &1, solType, timeout)})
    |> merge_found_patterns()
  end

  def merge_found_patterns(result_stream) do
    Enum.reduce(result_stream, %{}, fn {, {name, indices}}, acc ->
      Map.put_new(acc, name, indices |> Enum.filter(&(&1 != -1)))
    end)
  end
end
```
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-09-16 16:28
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-09-16 16:28 UTC
