### ISSUE TITLE
[auto-generated] Exception after 'Go To Method'

### ISSUE THREAD

**Issue by AntoniBertel** [KronicDeth/intellij-elixir#710] opened 2017-06-07 11:49 UTC
I clicked on 'Mix.env' in 'config.exs' multiple times.

# Version

5.1.0

# Exception

## Message

Worker exited due to exception

## Stacktrace

```
java.lang.StackOverflowError
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:29)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageView.UsageViewTypeLocation$1.getElementDescription(UsageViewTypeLocation.java:67)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:38)
	at org.elixir_lang.FindUsagesProvider.getType(FindUsagesProvider.java:125)
	at com.intellij.usageVi

**Comment by KronicDeth** [comment] 2017-08-06 16:34
I can't reproduce this on [master](https://github.com/KronicDeth/intellij-elixir/commit/45a6863fe174009344a08bdcbe21eec1233faaf7) or [v5.1.0](https://github.com/KronicDeth/intellij-elixir/commit/90640c5431db9c7a4ab13f65bc1b0db7eff22e9a), so I'm closing as Can't Reproduce.  If you can push a repository that reproduces the issue, I'll reopen.

**Closed by KronicDeth** 2017-08-06 16:34 UTC
Labels: bug
