### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.3` is missing Erlang SDK at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)

### ISSUE THREAD

**Issue by anders-christiansen** [KronicDeth/intellij-elixir#3052] opened 2023-02-07 21:19 UTC
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Mac OS X (13.0)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.3` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.3` is missing Erlang SDK
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.Mix.commandLine$default(Mix.kt:12)
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:85)
```

</details>

**Comment by KronicDeth** [comment] 2023-02-21 21:40
Duplicate of #2747

**Closed by KronicDeth** 2023-02-21 21:40 UTC
