### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by aerovulpe** [KronicDeth/intellij-elixir#2877] opened 2022-10-01 20:19 UTC
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Windows 10 (10.0)

# Event

### Element

```
,
```

From: `C:/Users/aerov/IdeaProjects/chatkitty-web-services/chat-service-ui/lib/chat_service_ui/stompx.ex:4`

#### Context

```
defmodule ChatServiceUi.StompX do
  {:ok, callback_pid} = Mammoth.DefaultCallbackHandler.start_link
  {:ok, pid} = Mammoth.start_link(callback_pid)
  :ok = Mammoth.DefaultCallbackHandler.set_mammoth_pid(callback_pid, pid)
  Mammoth.connect(pid, , 61613, "/", "admin", "admin")
  Mammoth.subscribe(pid, "foo.bar", :client)
  Mammoth.disconnect(pid)
end

```

From: `C:/Users/aerov/IdeaProjects/chatkitty-web-services/chat-service-ui/lib/chat_service_ui/stompx.ex:0-8`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```
Details: C:\Users\aerov\IdeaProjects\chatkitty-web-services\chat-service-ui\lib\chat_service_ui\stompx.ex
defmodule ChatServiceUi.StompX do
  {:ok, callback_pid} = Mammoth.DefaultCallbackHandler.start_link
  {:ok, pid} = Mammoth.start_link(callback_pid)
  :ok = Mammoth.DefaultCallbackHandler.set_mammoth_pid(callback_pid, pid)
  Mammoth.connect(pid, {127,0,0,1}, 61613, "/", "admin", "admin")
  Mammoth.subscribe(pid, "foo.bar", :client)
  Mammoth.disconnect(pid)
end

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment] 2022-10-07 17:09
Duplicate of https://github.com/KronicDeth/intellij-elixir/issues/2774

**Closed by KronicDeth** 2022-10-07 17:09 UTC
