### ISSUE TITLE
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elixir_lang.espec.configuration.Factory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: org.elixir_lang] at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)

### ISSUE THREAD

**Issue by majmocska** [KronicDeth/intellij-elixir#2357] opened 2021-12-06 18:01 UTC
# System

Plugin Version: 12.0.0
Application: PhpStorm (2021.3)
Operating System: Windows 10 (10.0)

# Event

### Stacktrace

```
```

**Comment by tim-schilling** [comment] 2021-12-06 20:21
Duplicate of #2347, can be closed.

**Comment by KronicDeth** [comment] 2021-12-07 02:49
Duplicate of #2105

**Closed by KronicDeth** 2021-12-07 02:49 UTC
Labels: Kind:Bug
