### ISSUE TITLE
NPE org.elixir_lang.psi.impl.PresentationImpl.getPresentation(PresentationImpl.kt:30)

### ISSUE THREAD

**Issue by davit555** [KronicDeth/intellij-elixir#1253] opened 2018-09-07 08:17 UTC
# Exception

## Message

In file: file:///home/davit/IdeaProjects/betco_pusher_proxy/test/proxy/proxy_server_test.exs

## Stacktrace

```
kotlin.KotlinNullPointerException
	at org.elixir_lang.psi.impl.PresentationImpl.getPresentation(PresentationImpl.kt:30)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.getPresentation(ElixirPsiImplUtil.java:1076)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.getPresentation(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:108)
	at org.elixir_lang.annotator.Callable$Companion.referrerTextAttributesKeys(Callable.kt:378)
	at org.elixir_lang.annotator.Callable$Companion.access$referrerTextAttributesKeys(Callable.kt:357)
	at org.elixir_lang.annotator.Callable.callHighlight(Callable.kt:151)
	at org.elixir_lang.annotator.Callable.callHighlight(Callable.kt:202)
	at org.elixir_lang.annotator.Callable.callHighlight(Callable.kt:218)
	at org.elixir_lang.annotator.Callable.highlight(Callable.kt:225)
	at org.elixir_lang.annotator.Callable.access$highlight(Callable.kt:27)
	at org.elixir_lang.annotator.Callable$annotate$1.visitPlainCall(Callable.kt:110)
	at org.elixir_lang.annotator.Callable$annotate$1.visitNonModuleAttributeCall(Callable.kt:85)
	at org.elixir_lang.annotator.Callable$annotate$1.visitCall(Callable.kt:46)
	at org.elixir_lang.annotator.Callable$annotate$1.visitElement(Callable.kt:77)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.elixir_lang.psi.impl.ElixirMatchedUnqualifiedParenthesesCallImpl.accept(ElixirMatchedUnqualifiedParenthesesCallImpl.java:38)
	at org.elixir_lang.annotator.Callable.annotate(Callable.kt:38)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment] 2018-09-30 13:38
It's not in `9.0.0`.  Line 30 is a `null` check:

https://github.com/KronicDeth/intellij-elixir/blob/93edffff05b5a3725a41e5e2637fe5b2f1b039ac/src/org/elixir_lang/psi/impl/PresentationImpl.kt#L30

It's not in `8.1.0`, which is the same

https://github.com/KronicDeth/intellij-elixir/blob/a2308f87ca79e9770a51945d9adcdd3adc4ef27b/src/org/elixir_lang/psi/impl/PresentationImpl.kt#L30

8.0.0 has the check

https://github.com/KronicDeth/intellij-elixir/blob/v8.0.0/src/org/elixir_lang/psi/impl/PresentationImpl.kt#L30

7.5.0 has the `callDefinition!!`, which triggered this error

https://github.com/KronicDeth/intellij-elixir/blob/v7.5.0/src/org/elixir_lang/psi/impl/PresentationImpl.kt#L30

This is a duplicate of #1131.  Fixed in #1189, which was released in `8.0.0`, which was released on 2018-08-16.  Please upgrade to the lastest release, `9.0.0`.  You were already running an old version when you filed this bug.

**Closed by KronicDeth** 2018-09-30 13:38 UTC
Labels: Kind:Bug
