### ISSUE TITLE
Don't know if Mix.Dep option `warn_missing` is important for determining location of dependency at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)

### ISSUE THREAD

**Issue by nothingelsematters7** [KronicDeth/intellij-elixir#2669] opened 2022-05-20 15:20 UTC
# System

Plugin Version: 13.0.0
Application: PyCharm Professional Edition (2022.1)
Operating System: Mac OS X (11.6.5)

# Event

### Excerpt

```
{:exactor, "2.2.1", warn_missing: false}
```

From: `/Users/dev_il/Projects/Work/ordo/apps/ordo_monitoring/mix.exs:32`
To: `/Users/dev_il/Projects/Work/ordo/apps/ordo_monitoring/mix.exs:32`
            
### Element Class Name

```
org.elixir_lang.psi.impl.ElixirTupleImpl
```

### Stacktrace

```
java.lang.Throwable: Don't know if Mix.Dep option `warn_missing` is important for determining location of dependency
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:43)
	at org.elixir_lang.mix.Dep$Companion.from(Dep.kt:55)
	at org.elixir_lang.mix.Deps.fromTuple(Deps.kt:61)
	at org.elixir_lang.mix.Deps.from(Deps.kt:18)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt$deps$2.invoke(DepGatherer.kt:140)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:140)
	at org.elixir_lang.mix.DepGathererKt.deps(DepGatherer.kt:42)
	at org.elixir_lang.mix.DepGathererKt.access$deps(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:34)
	at org.elixir_lang.mix.DepGatherer$visitElement$1.invoke(DepGatherer.kt:33)
	at org.elixir_lang.mix.DepGathererKt.foldDepsDefinersWhile(DepGatherer.kt:62)
	at org.elixir_lang.mix.DepGathererKt.access$foldDepsDefinersWhile(DepGatherer.kt:1)
	at org.elixir_lang.mix.DepGatherer.visitElement(DepGatherer.kt:33)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.elixir_lang.psi.impl.ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedUnqualifiedNoParenthesesCallImpl.java:38)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at org.elixir_lang.mix.DepGatherer$visitFile$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at org.elixir_lang.mix.DepGatherer.visitFile(DepGatherer.kt:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$1$1.compute(Resolution.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.elixir_lang.mix.watcher.Resolution$Companion$packagePsiFileToDepSet$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packagePsiFileToDepSet(Resolution.kt:122)
	at org.elixir_lang.mix.watcher.Resolution$Companion.packageVirtualFileToDepSet(Resolution.kt:97)
	at org.elixir_lang.mix.watcher.Resolution$Companion.rootVirtualFileToDepSet(Resolution.kt:80)
	at org.elixir_lang.mix.watcher.Resolution$Companion.resolution(Resolution.kt:38)
	at org.elixir_lang.mix.watcher.TransitiveResolution.transitiveResolution(TransitiveResolution.kt:17)
	at org.elixir_lang.mix.Watcher.syncLibraries(Watcher.kt:64)
	at org.elixir_lang.mix.project.DirectoryConfigurator$configureDescendantOtpApp$1$1.run(DirectoryConfigurator.kt:92)
```

**Comment by KronicDeth** [comment] 2022-05-20 16:17
Duplicate of #1941

**Closed by KronicDeth** 2022-05-20 16:17 UTC
